### ISSUE TITLE
Case vs2013 update 5 crash while start debug mode.

### ISSUE THREAD

**Issue by woodywu** [GPUOpen-Tools/CodeXL#1]
Cause vs2013 update 5 crash while start debug mode.

**Comment by doronofek** [comment]
Thanks for this report.
Can you help to provide a log file to investigate this issue?

1. Please use the VS CodeXL menu to open the CodeXL Options dialog, set the Log Level to Debug, click OK and restart VS2013.

2. Now start a debug session and after VS crashes, find the CodeXL log file in %temp%\CodeXL-username.log

3. Upload the log file to this page.

Thanks

**Comment by woodywu** [comment]
Hi,

Attachment is the log. When I switch debug model and start debug the first time, it seems codexl works fine as I expect. And the sceond time it broken.

CodeXL(installed) : info model : broken -> broken -> broken ....
CodeXL(info -> debug) : debug model : broken -> ok -> broken -> ok -> ok -> broken .... ???
CodeXL(debug -> info) : info model : ok -> broken -> ok .... ???

A thread issue 

???

**Comment by woodywu** [comment]
[Uploading CodeXLRemoteAgent-pc255.log…]()

**Comment by woodywu** [comment]
I don't know why I can't upload the log file. 

Please download it from here. click " 下载(18KB) " button. 

http://pan.baidu.com/s/1nuPwHgH

I hope this will be help.

**Comment by doronofek** [comment]
> I don't know why I can't upload the log file.

I've uploaded the file for you.
[log.zip](https://github.com/GPUOpen-Tools/CodeXL/files/229363/log.zip)
I will investigate

**Comment by uriAMD** [comment]
Hi,

If you run the application without setting any host code breakpoints (just clear or disable all breakpoints), does the issue still happen?

If that works, try setting an API function breakpoint (e.g. on wglSwapBuffers). Does this change anything?

In addition, if you go to CodeXL > CodeXL Options and set the log level to DEBUG, the log file could be more informative.

Thanks,

**Comment by woodywu** [comment]
Clear all breakpoints will not crash, and it is crash after I set the glBindFrameBuffer breakpoint. wglSwapBuffers is always OK(works well). And it is hard to repeat the issue on log - debug mode, but easy to repeat on log - info.

After the last crash in debug mode, I got this. 

http://pan.baidu.com/s/1o8nbnfk

Still can not upload the file....

**Comment by doronofek** [comment]
> Still can not upload the file....
I uploaded the file

[log_more.zip](https://github.com/GPUOpen-Tools/CodeXL/files/229985/log_more.zip)

**Comment by uriAMD** [comment]
From the new logs, it seems that the crash happens while the CodeXL is trying to update the OpenGL static buffers.

I've also noticed in your log that you're using the 15.8 (Latest Radeon Crimson) driver, but your GPU is from the Radeon HD 6000, which is now a legacy product.
Get the latest stable driver from here:
http://support.amd.com/en-us/download/desktop/legacy?product=legacy3&os=Windows+7+-+64
And see if it helps.

Hope this helps,
Uri

**Comment by woodywu** [comment]
Not working for me... And I switch to last version of codexl ...

**Comment by uriAMD** [comment]
I forgot to ask, if you debug another OpenGL application (e.g. CodeXL's teapot sample), does the same thing happen?

If not (i.e. the problem only happens with your app), is there a chance you could share your application with us?
Just the binary would be enough (though the source would be helpful, if you can share that as well).
If not, could you try creating a smaller sample app that produces the same effect?

Thank you for your cooperation and patience.

**Comment by mirh** [comment]
Fixed by d32994ae31f0c59c4a49c3bda2695df1f8bb58a8?

**Comment by callan-amd** [comment]
Visual Studio Extension support has been removed from the latest CodeXL code. Only the standalone tool will be supported in future.
