### ISSUE TITLE
Does not compile/build on Fedora

### ISSUE THREAD

**Issue by spstarr** [GPUOpen-Tools/CodeXL#10]
- There is C++x11 ABI errors when linking
- Its hardcoded to Bin-Internal even though I tell the script to build
- Not able to use native system libraries like Boost.

Any plans to address allowing this to build using system paths?

**Comment by giladyarnitzky** [comment]
Can you please provide the full build command you use and output result so we can try and understand the exact problem.

**Comment by spstarr** [comment]
Some comments, the HSA bits I had to extract from Debian since the RPMs did not have all the files needed(?)

Getting error with the include Boost libs (can't we used the system shared boost?). if I force build system to use my boost libs and not the RHEL6 ones, it links but other problems happen.

[GpuProfilerBackend_Build.log.txt](https://github.com/GPUOpen-Tools/CodeXL/files/232844/GpuProfilerBackend_Build.log.txt)

Initial build:

/backend_build.sh skip-32bitbuild -j8 CXL_build_verbose=1 CXL_build=release
SPROOT=/home/spstarr/tmp/amd/CodeXL/CodeXL/Components/GpuProfiling/Build/..
=====Building GPU Profiler Backend======

Building infra projects
===========================
Build arguments passed to scons: 
========================================== 
----------- Start building --------------- 
Sat Apr 23 02:57:53 EDT 2016
========================================== 
scons -C /home/spstarr/tmp/amd/CodeXL/CodeXL/Components/GpuProfiling/Build/../Build CXL_prefix=/home/spstarr/tmp/amd/CodeXL/CodeXL/Components/GpuProfiling/Build/.. CXL_build_type=static 
========================================== 
scons -C /home/spstarr/tmp/amd/CodeXL/CodeXL/Components/GpuProfiling/Build/../Build CXL_prefix=/home/spstarr/tmp/amd/CodeXL/CodeXL/Components/GpuProfiling/Build/.. CXL_arch=x86 CXL_build_type=static 
========================================== 
----------- End building ----------------- 
Sat Apr 23 02:59:08 EDT 2016
========================================== 
*** SUCCESS ***
Build Common, 64-bit...
Build DeviceInfo, 64-bit...
Build CLCommon, 64-bit...
Build CLProfileAgent, 64-bit...
Build CLTraceAgent, 64-bit...
Build CLOccupancyAgent, 64-bit...
Build HSAFdnCommon, 64-bit...
Build HSAFdnTrace, 64-bit...
Build HSAFdnPMC, 64-bit...
Build sprofile, 64-bit...
Failed to build sprofile, 64 bit

**Comment by giladyarnitzky** [comment]
Can you please validate that you have under the common directory the Common\Lib\Ext\Boost with boost_1_59_0 folder which is the correct boost version that is needed.
If it does not maybe you need to get the common submodule with the following commands:
Open a command prompt, navigate to the repo root directory and type the following commands:
git submodule init
git submodule update

**Comment by spstarr** [comment]
Yes I have, those exist.

**Comment by doronofek** [comment]
Hi spstarr,
This looks like a conflict between the Boost version that CodeXL builds with and a local one.
Did you have Boost installed on your station before CodeXL? Which Boost version?
Thanks,
Doron

**Comment by spstarr** [comment]
Yes, I have 1.58.0, Fedora 23 hasn't backported 1.59.x, I could build 1.59 however against Fedora 23.

**Comment by callan-amd** [comment]
CodeXL 2.2 includes the option to build against the system Boost version. Instructions are in the Build.md file.
