### ISSUE TITLE
shaderdebuggerdevicecl.cpp was not found

### ISSUE THREAD

**Issue by russdirks** [GPUOpen-Tools/CodeXL#102]
>CodeXL requires the location of this file to display the source for the current call stack frame.

I'm debugging a kernel on Windows 10.  I set a breakpoint on the kernel name, and when it triggered, I used the step-over command (F10).  That caused the debugger to hang for about 3 or 4 minutes, and finally it gave the message above.  Where can I find this file?

**Comment by callan-amd** [comment]
This looks like you are trying to use the CPU debugger to debug into the CodeXL code itself - this file is part of the CodeXL source code.  I'm assuming this wasn't your intention.

**Comment by russdirks** [comment]
No, that was not my intention.  It has happened to me a couple of times now.  Once I was stepping through kernel code and I set a breakpoint about 5 or 6 statements ahead.  There happened to be a `barrier(CLK_LOCAL_MEM_FENCE)`  in between.  I hit Run and got the same message that I reported above.

For what it's worth, I am debugging the Ethereum mining program, which has a 2 GB data buffer that it works with.  Stepping through code takes about 3-4 minutes per statement, so as you can guess, I've been finding other ways to debug my kernel.

**Comment by bpurnomo** [comment]
The kernel debugging feature is being deprecated as the compiler model has changed.
