### ISSUE TITLE
Cannot add a new Project on a built version 2.2

### ISSUE THREAD

**Issue by kpontzolkova** [GPUOpen-Tools/CodeXL#106]
Hello everyone..

I successfully compiled the CodeXL on Ubuntu 14.04. The program starts without problems. But when I am trying to create a new project, or add an existing one the program crashes.

In the debug mode the message:

////////////////////////////////////////////
Debug Assertion Failed!
File Name: kaAnalyzeSettingsPage.cpp - 118
File Path: variant_debug/AMDTKernelAnalyzer/src/kaAnalyzeSettingsPage.cpp
Assert Reason:
Assertion failure ((m_pTargetDevicesTreeView != __null) && (m_pTargetDevicesTreeModel != __null))
//////////////////////////////////////////

When I am trying to system-wide profile, the program also crashes with the message:
Assert in:appEventObserver.cpp - Line: 316

On the other hand i know that the CpuProfiler from the command line is running perfectly, so the issue is somewhere in the visualization.

Also the pre-compiled version doesn't display the above errors, but i really need to make changes to the source code, so the ability to make changes and then compile successfully is very important.

Thank you for your time

**Comment by kpontzolkova** [comment]
So I found a solution kind of.. I deleted the .CodeXL file

**Comment by kpenujee** [comment]
Hi,
Are you trying to launch CodeXL via xterm/putty or any X11 forwarding tool?


Thanks,
Kalyan P

**Comment by kpontzolkova** [comment]
No. But i noticed that the problem occurred after i tried to launch the built-by-me CodeXL. After that I couldn't launch successfully the pre-build version. So i deleted the .CodeXL file, which solved part of the problem. 

I still can't run some features, like "importing a session", which freeses the program, but i can profile the given examples.

I think that the built-by-me version is conflicting with the original somehow, and maybe it is my fault, like a broken package or something but i cannot find out easily what is wrong. Also when the program freeses, i have to manually kill it (kill -9).

**Comment by swarup-sahoo** [comment]
Hi,
Thanks for reporting the issues, unfortunately we could not reproduce the issues at our end.

Just to summarise your description, you are observing 2 crashes in your debug build of CodeXL:
1) trying to create a new project, or add an existing one the program crashes.
2) trying to system-wide profile, the program also crashes.

CodeXL also generates a log file, please follow the below steps and attach the log file here.
a) Change the log level to EXTENSIVE at Tools > Options > General (Tab) > Debug log level (drop-down-list). Select OK.
b) Execute the steps to introduce the crash. (CodeXL would exit after this.)
c) Attach the file located at: ~/.CodeXL/CodeXL/CodeXL-<username>.log
(here the <username> is your login name)

If you run CodeXL from gdb debugger, you should be able to generate the stack-trace of the crash. That stack-trace might be helpful to us in debugging the issue.

Ubuntu 14.04 is little old. If you have access to any Ubuntu 16.x, then you may try on such systems to verify if you can reproduce crash.

**Comment by kpontzolkova** [comment]
thank you for a quick response. 

I will try to reproduse the bug on a Ubuntu 16, but it will take some time.


[backtrace.txt](https://github.com/GPUOpen-Tools/CodeXL/files/742413/backtrace.txt)

[build-by-me.log.txt](https://github.com/GPUOpen-Tools/CodeXL/files/742421/build-by-me.log.txt)
[pre-built.log.txt](https://github.com/GPUOpen-Tools/CodeXL/files/742420/pre-built.log.txt)

**Comment by kpontzolkova** [comment]
So I installed Ubuntu 16, and after running pre-compiled version and my version of CodeXL, I'm again experiencing the same issue. At first everything is fine. But after running both versions, the CodeXL crashes when I'm trying to import a session and I have to manually kill it. Thank you for your time. 

Regards,
Katerina

**Comment by kpontzolkova** [comment]
I solved the issue by installing manually qt5.7.0 and overriding the path of the CodeXL's qt libraries.

**Comment by swarup-sahoo** [comment]
From our analysis, this issue seems to be Qt-5.5 know bug (CodeXL 2.2 uses Qt-5.5). This is not always reproducible. For this issue, we have filed a Qt bug for this - https://bugreports.qt.io/browse/QTBUG-58744

Thanks for confirming our analysis by using Qt-5.7
