### ISSUE TITLE
No support for pre-GCN AMD GPU's

### ISSUE THREAD

**Issue by PV70** [GPUOpen-Tools/CodeXL#11]
Dear Administrator,

I need to use the CodeXL build and analyze functions to tune an OpenCL kernel on an AMD GPU of Northern Islands (i.e. pre-GCN) class. In my understanding, such legacy GPU's are only supported by older versions of CodeXL.

However, no version of CodeXL older than v2.0 is available on this GitHub or on AMD's tools page (even in the discontinued legacy tools section).

Could you kindly make the older versions available in either place for developers that need to address legacy GPU's? A binary distribution would be ideal.

Thanks in advance!
Paolo

**Comment by doronofek** [comment]
Hi,
Legacy AMD CodeXL 1.9 binaries are now available on [AMD's developer website](http://developer.amd.com/tools-and-sdks/opencl-zone/codexl/)

**Comment by PV70** [comment]
Well done, that's going to be helpful.

Thanks a lot!
Paolo

**Comment by leonmaxx** [comment]
Hi,
The link to AMD CodeXL 1.9 binaries are no longer valid. Google search did'nt helped.
I need it for the same reason as TS.

BR, Leon.

**Comment by callan-amd** [comment]
It looks like our web team have removed these by mistake - working to get the older builds restored.

**Comment by callan-amd** [comment]
Older builds are now available again here:  http://gpuopen.com/archive/Legacy-codexl/

**Comment by leonmaxx** [comment]
Thanks a lot!

BR, Leon.

**Comment by SuicSoft** [comment]
Could CodeXL work with HD 7000 GPUs that mix GCN and non-GCN since they might contain the needed GCN components ?
