### ISSUE TITLE
executing the CodeXL script does nothing

### ISSUE THREAD

**Issue by NateN1222** [GPUOpen-Tools/CodeXL#117]
When I do ./CodeXL it just does nothing

I'm on a brand new install of Ubuntu 14.04, so it's possible I'm missing a dependency or something but I'm not sure how to debug it if I get no output

**Comment by nevion** [comment]
nvidia system?  #150  might apply if so...

**Comment by tangjie77wd** [comment]
@NateN1222 @nevion 
I create projects with OpenCL on linux . My machine : CentOS 7.3+eclipse + AMD Rx560 + amdgpu-pro-17.30-465504 + CodeXL_Linux_x86_64_2.4.60 .

    After I installed all tools above , go into the 'CodeXL_Linux_x86_64_2.4.60' folder and open a terminal ,run the command : ./CodeXL ,then CodeXL gui will appear .
    Click the 'Help' menu and then click 'Load the Teapot Sample' .
    Click the 'Profile' menu and then clike 'GPU:Performance Counters' .
    Press 'F5' on your keyboard and wait for a while.
    Close the 'AMD Teapot Example' gui and wait for a while , you will see many performance indicators in the CodeXL gui.
But I have a question these days : the Teapot sample is provided by CodeXL not myself (It exists in CodeXL as a 'CodeXL Teapot.cxl' file ,so we can load it directly in CodeXL. ) , how can i use CodeXL to test the performance of my own OpenCL projects (.cpp file and .cl file) written in the eclipse ( no .cxl file )? The file 'CodeXL_Quick_Start_Guide.pdf' does not describe any about this. Any help will be much appriciate !
