### ISSUE TITLE
CXLPowerProfileCLI on Carrizo Windows - The driver failed to start profiling.

### ISSUE THREAD

**Issue by Woking-34** [GPUOpen-Tools/CodeXL#118]
Hi,

I'am trying to run CXLPowerProfileCLI to gather power metrics from my Carrizo APU. I got the error message: **The driver failed to start profiling. (error code 0x80004005)** - line 545, hResult = collect.StartProfiling();

I can run the pre-installed CodeXL with Power Profiling - Teapot sample, my system:
Radeon Software Version - 17.2.1
Radeon Software Edition - Crimson ReLive
Graphics Chipset - AMD Radeon R7 Graphics
Windows Version - Windows 10 (64 bit)
System Memory - 16 GB
CPU Type - AMD FX-8800P Radeon R7, 12 Compute Cores 4C+8G
VS2015 Community. Target: Win32.

Could someone please help on this issue? Thanks!

**Comment by rajeebbarman** [comment]
Hi,
 Can you please do the following steps.

1. Before you try the any new version, can you please uninstall existing CodeXL Setup and make sure AMDTPwrProf.sys, pcore.sys and CpuProf.sys are gracefully deleted from c:\windows\system32\drivers folder. You may need to restart in after cleaning the system.

2. Which git commit number from the CodeXL git repository you are trying to install? Is it 2.3 or master?

3. How did you installed the driver? Please use CodeXL\Components\CodeXLDrivers\Windows\Scripts\CodeXLInstallDriver.cmd to install the driver.

4. Please make sure all drivers are up and running before you use the power profiler.
   You can run following command to check if drivers are running
    - sc query pcore
    - sc query amdtpwrprof
    - sc query cpuprof

**Comment by Woking-34** [comment]
Hi,
Unfortunately I am getting the same error message.

1. CodeXL uninstalled, sys files removed, system rebooted.
2. Switched to branch 2.3.
3. Drivers installed via the script file, log seems ok:
- Deleting installed service files from C:\Windows\System32\drivers directory
- Copying requireds system file to C:\Windows\System32\drivers
- Creating and starting CodeXLDriversLoadService which will creates and start pcore, amdtpwrprof and cpuprof services.
- Verifing CodeXLDriversLoadService, pcore, amdtpwrprof and cpuprof services....
- CodeXLDriversLoadService is running.
- pcore is running.
- amdtpwrprof is running.
- cpuprof is running.
4. All three driver report: STATE: 4  RUNNING

What else could go wrong? Thanks for your help and time!

**Comment by bpurnomo** [comment]
The Power Profiler has been forked to https://developer.amd.com/amd-uprof/
