### ISSUE TITLE
Event callbacks never called during GPU debugging

### ISSUE THREAD

**Issue by tobbebex** [GPUOpen-Tools/CodeXL#119]
I have used clSetEventCallback on a kernel event to register a piece of code that will perform some operations on the CPU and ultimately call clSetEventCallback to mark a user event as finished. This user event is then being a dependency for a later kernel event in the same command queue. 

This arrangangement allows me to asynchronously process and stream data from the cpu to the gpu as the command queue progresses on the GPU. Running this normally works fine, but when I'm running using GPU debugging in CodeXL the system deadlocks in clFinish since the callback is never fired (and hence the user event is never set as finished, making the command queue stall indefinetly).

A work around for now instead of registering event callbacks is to just clFinishing the command queue and call my CPU code synchronously before enqueueing the rest of the command queue.

**Comment by bpurnomo** [comment]
The kernel debugging feature is being deprecated as the compiler model has changed.
