### ISSUE TITLE
Any OGL application I launch in CodeXL segfault fgrlx_dri

### ISSUE THREAD

**Issue by norsetto** [GPUOpen-Tools/CodeXL#12]
I guess the title says it all. I attach a debug log taken with the teapot sample but the same thing happens in all OGL applications I tried.
[CodeXL-cesare.log.txt](https://github.com/GPUOpen-Tools/CodeXL/files/229376/CodeXL-cesare.log.txt)

**Comment by doronofek** [comment]
Hi,
Please upload the log of the CodeXL debugging server named CodeXLServers-cesare.log located in /home/cesare/.amd
Thanks

**Comment by norsetto** [comment]
Hello there, here it is.
[CodeXLServers-cesare.log.txt](https://github.com/GPUOpen-Tools/CodeXL/files/244127/CodeXLServers-cesare.log.txt)

**Comment by uriAMD** [comment]
Hi,
From the logs it seems you have a very outdated AMD Driver (14.201 is over a year old).
Could you try updating to the latest AMD drivers and seeing if it helps?

Either way, it seems the OpenGL runtime is calling a function that is not there (the top of the call stack is a NULL pointer), so there should be some mismatch between the CodeXL OpenGL server and the OpenGL runtime.

Thank you for your report,
Uri

**Comment by norsetto** [comment]
Well, what I have installed is indeed the latest available for Linux (15.12)!?

**Comment by Yves-G** [comment]
Hi,
I also get segfaults for every application I try to debug from CodeXL on Ubuntu 14.04. CodeXL shows "Signal: SIGSEGV" in the "Debugged Process Events" window and stops running the program, but CodeXL itself does not crash.

I have tried three different applications that all work outside CodeXL, one of them is also the teapot example. This was the first time I tried CodeXL.
I have just updated fglrx to the most recent version, so the logs contain crashes from two driver versions. 

Regards,
Yves

[CodeXLServers-yves.log.txt](https://github.com/GPUOpen-Tools/CodeXL/files/278155/CodeXLServers-yves.log.txt)
[CodeXL-yves.log.txt](https://github.com/GPUOpen-Tools/CodeXL/files/278156/CodeXL-yves.log.txt)

**Comment by doronofek** [comment]
Hi,
The crash you're observing in occurring in the AMD driver (fglrx). The driver version installed on your station is 15.20.1013 which was released last year. Please try to upgrade to a more recent driver release: http://support.amd.com/en-us/download/desktop?os=Ubuntu+x86+64

**Comment by Yves-G** [comment]
As norsetto already pointed out, this is the latest version I find there (December 2015). For Windows there are much more frequent driver updates, but for Linux, that's it.

I remembered similar problems when I tested a GPU profiling and debugging tool on Windows, so I tested again today (Dualboot Windows 7 on the same machine as Ubuntu 14.04). The problem does not occur there. It even works on Windows if I downgrade the driver to version 15.12.

**Comment by Yves-G** [comment]
It's probably related to this:
https://community.amd.com/thread/160546
http://ati.cchtml.com/show_bug.cgi?id=742
http://ati.cchtml.com/show_bug.cgi?id=1191

I also get this message in Xorg.0.log:
`[     6.559] (WW) fglrx(0): Option "BlockSignalsOnLock" is not used`

I haven't yet figured out how to solve the problem, though.

**Comment by cpcdoy** [comment]
Hey,
I have the same problem with the latest CodeXL on Ubuntu 16.04 using an Intel(R) HD Graphics 5600 (Broadwell GT2).
This was my first attempt at using CodeXL.

Here are the logs:

[CodeXL-cpcdoy.log.txt](https://github.com/GPUOpen-Tools/CodeXL/files/367320/CodeXL-cpcdoy.log.txt)
[CodeXLServers-cpcdoy.log.txt](https://github.com/GPUOpen-Tools/CodeXL/files/367319/CodeXLServers-cpcdoy.log.txt)
