### ISSUE TITLE
GPU debugger is using global offset wrong

### ISSUE THREAD

**Issue by tobbebex** [GPUOpen-Tools/CodeXL#120]
If you try to debug an OpenCL kernel have a global offset larger than global size (which should be perfectly fine mind you, size is counted from offset and not from 0), then the watches inside the kernel will tell you "Work item is invalid".

Found this more than a year old bug in AMDs old forum that seems to indicate its an old issue:
https://community.amd.com/thread/191692

Workaround for now is to not use the global offset feature in OpenCl but instead set a kernel argument.

**Comment by bpurnomo** [comment]
The kernel debugging feature is being deprecated as the compiler model has changed.
