### ISSUE TITLE
How to use debug in CodeXL for openCL

### ISSUE THREAD

**Issue by ngaalexx** [GPUOpen-Tools/CodeXL#121]
I'm new to CodeXL (version 2.2.511) and i don't know how to use debugger from CodeXL standalone .
Lets say we have those sources : 

helloopenCL.cpp
kernel_file.cl
and bin file : helloopenCL 

I create a project in codeXL then  set : executable Path, 
                                            Working Directory,
                                            Command line arguments
                                            Source File Directories  
then press ok.
In the right corner i press the green arrow button Host+GPU Debug, and when i press break button (to see source and check variables,values, set brakepoints) i got this error : 

malloc.c was not found
CodeXL requires the location of this file to display the source for the current call stack frame.

How can i solve this ?

I have OS : Ubuntu 14.04 64 bit
                 openCL SDK  2.9
                 codeXL 2.2.5.1.1
GPU : AMD R9 370
CPU : i5 4460

**Comment by bpurnomo** [comment]
Hi,
To debug an OpenCL application, I'd suggest to set an OpenCL API breakpoint (using Debug -> Add/Remove breakpoints).  For example, you can set a breakpoint at clEnqueueNDRangeKernel API, then to debug the OpenCL kernel, you can select "Step In" (or press F11).
For more details, please read the CodeXL Quick Start Guide (through Help -> View Quick Start Guide).
