### ISSUE TITLE
Setting local/global work group size

### ISSUE THREAD

**Issue by SyamGadde** [GPUOpen-Tools/CodeXL#126]
I'm running a custom build on Linux of CodeXL at commit d89dbf1bddc0c9bd37c9cabd9b45eb9f0e17dd18.

I'm on the OpenCL Kernel Analysis Statistics page.  It gives me a place to set the local work group size:

![codexl1](https://cloud.githubusercontent.com/assets/1247460/25860727/775617f2-34b0-11e7-9624-db596de3316f.png)

But if I attempt to change it to, say, 20 1 1, it gives me an error:

![codexl2](https://cloud.githubusercontent.com/assets/1247460/25860776/a312ab94-34b0-11e7-9a9f-97d5515f2a00.png)

Number 1 seems like the only possible culprit but I can find no way to change the global workgroup size.  Older documentation shows a way to change the default global workgroup size when choosing which target devices to compile for, with the string defined by ```KA_STR_analsisSettingGeneralInfo```  but can't seem to find any actual use of that in the current build.

How can I change the local (and global) work sizes?  Thanks!

**Comment by AmitBM** [comment]
Thank you for reporting this issue, SyamGadde. 
We will look into it.

**Comment by githubharald** [comment]
any news on this?
