### ISSUE TITLE
CodeXLRemoteAgent fails silently

### ISSUE THREAD

**Issue by VincentSC** [GPUOpen-Tools/CodeXL#127]
Trying to do GPU-profiling of a HelloWorld program remotely. Both host and remote are Linux.

Running Remote Agent as root (else there is "Profiling is not available"):
````
CodeXL GPU Profiler V4.0.511 is enabled
CodeXL GPU Profiler V4.0.511 is Enabled
CodeXL GPU Profiler Kernel occupancy module is enabled
Failed to generate profile result /home/vincent/.CodeXL/AMD/CodeXL/HelloWorld@46.102.xxx.xxx_ProfilerOutput/May-10-2017_11-25@46.102.xxx.xxx/May-10-2017_11-25@46.102.xxx.xxx.occupancy.
Failed to generate profile result /home/vincent/.CodeXL/AMD/CodeXL/HelloWorld@46.102.xxx.xxx_ProfilerOutput/May-10-2017_11-25@46.102.xxx.xxx/May-10-2017_11-25@46.102.xxx.xxx.csv.
````
The directory _/home/vincent/.CodeXL/AMD/CodeXL/HelloWorld@46.102.xxx.xxx_ProfilerOutput/May-10-2017_11-25@46.102.xxx.xxx/_ gets created without problems, so no file-creation issue. Profiling HelloWorld locally works without problems. [Searched](https://github.com/GPUOpen-Tools/CodeXL/search?utf8=%E2%9C%93&q=Failed+to+generate+profile+result&type=) for "Failed to generate profile result" in this repo, but did not find this exact sentence.

**Comment by chesik-amd** [comment]
This should no longer be an issue in CodeXL 2.6
