### ISSUE TITLE
CodeXLRemoteAgent communication problem

### ISSUE THREAD

**Issue by VincentSC** [GPUOpen-Tools/CodeXL#128]
Upgraded to latest CodeXL 2.3 with the goal to see if #127 was solved.

First run: "Communication failure: Please verify that both client and remote machines are connected to the network." and the agent leaves the connection open.
Second run: "Unable to connect to CodeXL Remote Agent." and the agent quits.
Following sets of runs: "Unable to retrieve CodeXL version of CodeXL Remote Agent." + "Unable to connect to CodeXL Remote Agent." like above.

**Comment by chesik-amd** [comment]
This should no longer be an issue in CodeXL 2.6. Can you retest?
