### ISSUE TITLE
Unable to load timeline data after adding Ctrl-C detection

### ISSUE THREAD

**Issue by russdirks** [GPUOpen-Tools/CodeXL#130]
I've been using CodeXL to profile a CLI OpenCL program on Windows 10 and it has been working well.  Recently I added Ctrl-C detection to my program using SetConsoleCtrlHandler so as to do a more graceful shutdown.  Ever since then, I can't profile any more.  I start the profiling session, Application Timeline Trace / GPU Profile, my program runs, but when I shut it down I get the error message "Unable to load timeline data. Try enabling "Write trace data in intervals ..."".

Is this a fault in CodeXL?  Is there something I can do to make it work?

**Comment by chesik-amd** [comment]
It sounds like either the application or the profiler is terminating unexpectedly.  I'm not sure this is a scenario we've tested.  We'll take a look.  Does this only happen if you end your app with ctrl-c or does it happen even when the app terminates normally?

**Comment by russdirks** [comment]
Well actually, the program is a simple console application that just has a main processing loop.  You normally just end it by pressing Ctrl-C, or closing the console window.  The software then gets forcefully closed.  It worked ok with CodeXL in that configuration.  But now I want to do a bit of shutdown processing when the user wants to close, so that's why I added SetConsoleCtrlHandler.  Here's my shutdown handler:
```
BOOL CtrlHandler(DWORD fdwCtrlType)
{
	switch (fdwCtrlType)
	{
		case CTRL_C_EVENT:
		case CTRL_CLOSE_EVENT:
			cout << "Shutting down ..." << endl;
			// this triggers the main loop to stop
			cli_close = true;
			// give the main loop some time to respond.
			this_thread::sleep_for(chrono::milliseconds(1500));
			return(TRUE);

			// Pass other signals to the next handler. 
		case CTRL_BREAK_EVENT:
		case CTRL_LOGOFF_EVENT:
		case CTRL_SHUTDOWN_EVENT:
			cout << "Shutting down ..." << endl;
			cli_close = true;
			this_thread::sleep_for(chrono::milliseconds(1500));
			return FALSE;

		default:
			return FALSE;
	}
}
```

**Comment by qwu2-amd** [comment]
Hi, I've managed to repro this reported issue. Now it is being worked on.
