### ISSUE TITLE
Attaching profiler to .NET process

### ISSUE THREAD

**Issue by AlexBatsev** [GPUOpen-Tools/CodeXL#131]
Hi. 
I need to profile a process which uses my dll with OpenCL calls in it, but when I try to attach to it, it is marked as "non-attachable".
Process which I'm trying to attach to, is .net, though it loads my dll which is native. 
I noticed that other .net processes are "non-attachable" as well.
What can be done in order to attach and profile such a process?
It is really critical for me.
Thanks.

**Comment by bpurnomo** [comment]
The CPU profiler has been forked to https://developer.amd.com/amd-uprof/
