### ISSUE TITLE
DX shader model 5_1, 6_0 support

### ISSUE THREAD

**Issue by anttihirvonen** [GPUOpen-Tools/CodeXL#136]
Hi!

I noticed that CodeXL only supports HLSL shader models up to 5_0. Are there plans to support newer shader models? We have many shaders written against SM 5_1 (in many cases just to use the new constant buffer syntax) and converting these to SM 5_0 just for analysis is too much work.

**Comment by AmitBM** [comment]
Hi anttihirvonen,
There is currently no plan to add support for shader model 5.1 and above in CodeXL.
There is work in progress to add this support in other tools, but this is unlikely to be publicly available before Q1-Q2 '18.

**Comment by anttihirvonen** [comment]
Thanks for the info!
