### ISSUE TITLE
Ability to have multiple custom profiles

### ISSUE THREAD

**Issue by mrolle45** [GPUOpen-Tools/CodeXL#137]
[enhancement]
CodeAnalyst used to let me save a custom profile under a different name, and then select that name for a project to open sessions for the project.
I tried creating an .xml file in the CodeXL\Profiles folder, but XL did not offer this name.
It would be really nice to be able to do these things in XL.

**Comment by bpurnomo** [comment]
The CPU Profiler has been forked to https://developer.amd.com/amd-uprof/
