### ISSUE TITLE
Ability to generate a report from the GUI

### ISSUE THREAD

**Issue by mrolle45** [GPUOpen-Tools/CodeXL#138]
[Enhancement]
I'd like to have some command from the UI that will generate a report for a profile session, just as I can do with `CodeXLCpuProfiler.exe report` from the command line.
Of course, this should show a dialog with all the same features as are on the command line (except for `-i <file name>` of course).

**Comment by bpurnomo** [comment]
The CPU Profiler has been forked to https://developer.amd.com/amd-uprof/
