### ISSUE TITLE
Preserving the source code for a session after the code has been changed.

### ISSUE THREAD

**Issue by mrolle45** [GPUOpen-Tools/CodeXL#139]
I realize this might be a lot of work to remedy the problem.
When I open a session, and then examine source code for some function, I see the correct source code corresponding to all the samples.
However, if I then edit the source code, then I see the new source code, which no longer corresponds to the samples.  Thus, sessions created before the source code edit are useless for samples in the edited function.
In order to alleviate this, XL would have to keep the original version of the source code file somewhere, to be used to show the profiles.
Hopefully, XL might maintain something like a CVS or SVN repository.
And hopefully, XL could be notified before a source file is modified, so that it could enter the old version into the repository, and that way, only modified files would be involved in the repository.
Naturally, XL would only need to save source files that were associated with actual sample addresses in the session.

Perhaps a partial remedy could be to have a command in the UI for the user to tell XL to track versions of a particular source file for future use by any session that refers to that file.  When a new session is opened, that refers to that file, and if that file is more recent than the latest tracked version, then the current version will be added to the tracked versions.

Another helpful thing would be for the Source/Disassembly window to have a switch to show only the disassembly.  This would avoid the confusion about source code lines if they have been modified.  This has been submitted as a separate enhancement issue.

**Comment by bpurnomo** [comment]
The CPU Profiler has been forked to https://developer.amd.com/amd-uprof/
