### ISSUE TITLE
Unable to build OpenCL source files

### ISSUE THREAD

**Issue by JcBernack** [GPUOpen-Tools/CodeXL#14]
With CodeXL 2.0 I am unable to build OpenCL source files. The build button is greyed out, even though I'm in Analyze Mode. It was working with CodeXL Version 1.9, am I missing something?

**Comment by JcBernack** [comment]
Ok, I had to create a new "program/folder" and add the source files there. I wonder for what reason I would want to add source files to the project outside of these programs/folders now.

**Comment by giladyarnitzky** [comment]
Build now is done on a program. A source file can be used in several programs. The program concept is needed since in vulkan & opengl different shaders have mutual impact on one another ISA and performance statistics.
For more details please see the user manual.
