### ISSUE TITLE
Enhancements to the Source/Disassembly window

### ISSUE THREAD

**Issue by mrolle45** [GPUOpen-Tools/CodeXL#140]
[Enhancement]
1.  I would like XL to remember my settings for show/hide of the code bytes and address columns, as well as the column widths or all shown columns.

2. Since the non-sample columns are not scrolled by the horizontal scrollbar, the UI needs to make sure that there is at least some room to the right of these columns to show some sample columns.  Perhaps the pane could be split into two panes, the right pane being for the samples.  When I first used XL, I could not see any sample columns at all, and I didn't understand why the scrollbar did not move any samples into the window; I thought that perhaps no samples existed.  Only when I happened to remove the Address column did I see a sample column far on the right side.

3. In addition to Expand or Collapse All in the context menu, have a command to show all disassembly and hide all source code.  Possibly the disassembly could show labels along with the instructions.  When I am looking at samples with a source line expanded, then I see samples for both the entire line and the individual instructions, and I find this confusing.

4. When a source line is expanded, distinguish the samples in the source line from the samples in the instructions.  If I remember correctly, CodeAnalyst did this.

5. Select sample columns to display or hide, and rearrange the columns.  CodeAnalyst did this too.

6. Have tabs for more than one function open in the same session.

I'm not sure what the scope of saved settings for columns should be.  You could associate the changes with (1) just the function within the session, (2) all functions within the session, (3) all functions within all sessions with the same profile type.

Generally, I'd like to see everything that CodeAnalyst could do be carried over to XL.

**Comment by bpurnomo** [comment]
The CPU Profiler has been forked to https://developer.amd.com/amd-uprof/
