### ISSUE TITLE
CodeXLCpuProfiler missing from Windows install

### ISSUE THREAD

**Issue by mrolle45** [GPUOpen-Tools/CodeXL#141]
I want to export the results of a session, so that I can analyze them further, or email them to a friend, etc.  The Help file shows a command line interface to CodeXLCpuProfiler.
However, there is no such file, nor anything with a name remotely suggesting such a function.

For us Windows users, **_please_** include the .exe file.  And in the meantime, could you attach a copy (for Windows 10 amd64) to a comment below, or a link to where it can be downloaded.

**Notes:**

I do see in GitHub that CodeXLCpuProfiler is a linux bash script, calling a program called CodeXLCpuProfiler-bin.  But nothing like that for Windows.

I did find AMDTCpuProfiling.sln in the repository.  I downloaded the repository and tried opening the solution with VS 2013, and I got these errors:

`C:\Program Files (x86)\CodeXL\CodeXL-master\CodeXL\Components\CpuProfiling\AMDTCpuProfiling\AMDTCpuProfiling.vcxproj : error  : Unable to read the project file "AMDTCpuProfiling.vcxproj".`
`C:\Program Files (x86)\CodeXL\CodeXL-master\CodeXL\Components\CodeXLCommonProjectIncludes.props(4,5): The imported project "C:\Program Files (x86)\CodeXL\CodeXL-master\Common\Lib\Ext\tinyxml\Global-TinyXML.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`
``
`C:\Program Files (x86)\CodeXL\CodeXL-master\CodeXL\Components\CpuProfiling\AMDTCpuProfilingComponents\AMDTCpuProfilingComponents.vcxproj : error  : Project "C:\Program Files (x86)\CodeXL\CodeXL-master\CodeXL\Components\CpuProfiling\AMDTCpuProfilingComponents\AMDTCpuProfilingComponents.vcxproj" could not be found.
`

**Comment by bpurnomo** [comment]
The CPU Profiling tool has been forked to https://developer.amd.com/amd-uprof/
