### ISSUE TITLE
Undefined reference to elf_setshstrndx

### ISSUE THREAD

**Issue by KingDuckZ** [GPUOpen-Tools/CodeXL#145]
I'm trying to compile CodeXL on Gentoo. I ran this command:

./buildCodeXLFullLinuxProjects -j8 CXL_build=release CXL_boost_lib_dir=/usr/lib64 CXL_boost_include_dir=/usr/include

but I'm getting this error: "Undefined reference to elf_setshstrndx".
I also tried compiling libelf manually from http://www.mr511.de/software/ I ran nm/objdump/readelf on it but I can't see anything by that name. In contrast this command:

readelf -Ws Output_x86_64/release/bin/libCXLProfilingAgentsData.so | ag sets

I can clearly see that elf_setshstrndx is unresolved there.

Any help with this build error please?

**Comment by moes1** [comment]
Hi there KingDuckZ. I ran into this same issue and I think I have managed to fix it. The problem for me was that I had a libelf.so file in my /usr/lib64 directory and that is not the libelf library you need to link to, you need to link to the libelf.a file included in your CodeXL installation. For me the easiest solution was to create a directory specifically to hold symbolic links to my boost library files

```
mkdir ~usernamue/boost/
find /usr/lib64 -name "*boost*" | xargs ln -s -t ~username/boost/ 
```
then build the code like so
```
./buildCodeXLFullLinuxProjects -j8 CXL_build=release CXL_boost_lib_dir=~username/boost/ CXL_boost_include_dir=/usr/include
```

Maybe that will work for you as well?
