### ISSUE TITLE
[Question] Where can I find the source code for CpuPerf, pcore and AMDTPwrProf?

### ISSUE THREAD

**Issue by mcleary** [GPUOpen-Tools/CodeXL#146]
Hello everyone,

The CPU and Power Profiling features of CodeXL relies on drivers that are loaded by a service called ```CodeXLDriversLoadService```. The project for the service is available even in the master branch, however, I wasn't able to find the source code for the drivers itself, only the binaries (```pcore.sys```, ```CpuPerf.sys``` and ```AMDPwrProf.sys```). So here is my question:

Is the source code for those drivers available anywhere or they are proprietary?

**Comment by kpenujee** [comment]
Hi Mcleary,
Driver code is AMDs proprietary.

Thanks,
Kalyan P

**Comment by mcleary** [comment]
Thanks for the reply.
