### ISSUE TITLE
On Ryzen: "Power profiler is not supported on current hardware"

### ISSUE THREAD

**Issue by srogatch** [GPUOpen-Tools/CodeXL#149]
I'm using CodeXL v 2.4.45.0 on Windows 10. The CPU is Ryzen 1800X.  When I select "Profile"->"Power Profiling", and then try to start profiling or "Profile"->"Select Power Profiling Counters...", I get a dialog box that says "Power profiler is not supported on current hardware".
I migrated my system from Phenom 2 X6 1100T processor and reinstalled CodeXL after that. It was giving that error with that processor, but I thought that the processor was really not supported.
Now I think that Ryzen should be supported and I saw an announcement about that: http://gpuopen.com/codexl-2-3-is-released/
My GPU is NVidia Geforce GTX 1080. I don't need GPU profiling/debugging at the moment, but perhaps is it causing the error?

**Comment by kpenujee** [comment]
Hi,
CodeXL 2.4 was released primarily for StaticAnalyzer and other GPU related feature support for Vega graphics card.
For Power and CPU Profiling features, please use CodeXL 2.3v present at:
https://github.com/GPUOpen-Tools/CodeXL/releases/tag/v2.3

Thanks,
Kalyan P

**Comment by srogatch** [comment]
@kpenujee , so does this mean that a higher version. 2.4, doesn't support some features supported by a lower version, 2.3 ? In what version then do you plan to add support of Ryzen CPU permanently, so that it appears in all subsequent versions?

**Comment by bpurnomo** [comment]
The Power Profiling tool has been forked to https://developer.amd.com/amd-uprof/
