### ISSUE TITLE
Unable to find #include's in OpenCL files when using VS Extension

### ISSUE THREAD

**Issue by JcBernack** [GPUOpen-Tools/CodeXL#15]
When using CodeXL via the Visual Studio Extension I'm unable to make the OpenCL compiler find included files.

My setup is as simple as it can get: My kernel source files are all in a "source" folder with a single subfolder called "include" and the kernels contain: `#include "include/foobar.cl"`

I tried adding the path to `source` and to `source/include` in the CodeXL project settings here:
- General -> Source Files Directories
- Analyze -> Kernel/Shader Build Options -> Additional include directories

The last option works when using the standalone CodeXL application.

Any hints how to get this to work in VS would be appreciated.

**Comment by giladyarnitzky** [comment]
The Kernel/Shader build options should have worked for VS also. We will review this bug and submit a fix when possible.

To make sure that the build options are passed correctly to the OpenCL compiler there are two places they can be defined:
1: The options dialog
2: The Static Analyzer toolbar
Please try both places and see if defining at either of them solves your problem

**Comment by JcBernack** [comment]
Defining them at one place automatically adds them to the other. I played around a bit with where I enter the include path but couldn't get it to work.

**Comment by giladyarnitzky** [comment]
Several more questions:
1: Can you still succeed in building the kernel in the standalone application? The latest Driver introduced a bug that cause a bug when building with -I option when building with the offline compiler so if you installed the latest driver this might be the cause for the problem.
2: Are you giving the full path to the location of the additional include directories? In some cases the relative paths is not working correctly so giving the full path might solve this problem.

**Comment by JcBernack** [comment]
Interesting. I have the most recent non-beta driver installed (16.4.1) and I always used absolute paths.

The behavior is completely different now:
It builds both in the standalone application and the VS addon, but only for the device I have in my machine (Pitcairn). The others are failing because they can't find the #included files.
When building using the VS addon I can't see the compiler output anymore. When I click on "Build Foobar.cl" the output window comes up, but there's nothing there. I can see that the build succeeds on Pitcairn only because of the "Output" node in the CodeXL Explorer which contains proper results.

.. and here I thought this was a simple bug with the VS addon UI.
