### ISSUE TITLE
GPU Profiling: kernel time is huge when kernel is no-op

### ISSUE THREAD

**Issue by boxerab** [GPUOpen-Tools/CodeXL#151]
Kernel time is set to  `393325924.11192` when a kernel is completely optimized away ( for example, if nothing gets stored back to global memory).

**Comment by chesik-amd** [comment]
Is this for OpenCL or ROCm? Do you see this when collecting perf counters, when collecting an application trace, or in both cases?

Do you have a test case you can share where you see this?

**Comment by boxerab** [comment]
Thanks. This turned out to be "my bad", passing in a null ptr as one of my kernel arguments.
I guess the kernel never ran in that case, so CodeXL output was gibberish.

Is there a way of detecting this kind of failure ?
