### ISSUE TITLE
PowerProfile is not able to install

### ISSUE THREAD

**Issue by FalconBsp** [GPUOpen-Tools/CodeXL#152]
Install the PowerProfile driver:
$ sudo <codexl-install-dir>/ CXLTPwrProfDriver.sh install

=> Not able to find CXLTPwrProfDriver.sh  from "CodeXL_Linux_x86_64_2.4.60.tar.gz"

later i choose "sudo CodeXLPowerProfiler.sh install" but it failled with compilation error.

**Comment by kpenujee** [comment]
Hi,
can you please give us more details like:
- Snap-shot of the error that you are facing
- OS on which you are trying to install Power profiling driver
- Platform details


Thanks,
Kalyan P

**Comment by FalconBsp** [comment]
amd@amd:~$ uname -r
4.11.0-kfd-compute-rocm-rel-1.6-148

Platform details : Intel Haswell + Corjuja dGPU

`amd@amd:~/CodeXL/CodeXL_Linux_x86_64_2.3.605$ sudo ./CodeXLPwrProfDriver.sh  install
[sudo] password for amd:
Installing CodeXL Power Profiler driver.
make -C /lib/modules/4.11.0-kfd-compute-rocm-rel-1.6-148/build M=/usr/src/amdtPwrProf-6.01  EXTRA_CFLAGS="-I/usr/src/amdtPwrProf-6.01/inc -DKERNEL_MODULE -DLINUX -D_LINUX " clean
make[1]: Entering directory '/usr/src/linux-headers-4.11.0-kfd-compute-rocm-rel-1.6-148'
make[1]: Leaving directory '/usr/src/linux-headers-4.11.0-kfd-compute-rocm-rel-1.6-148'
make -C /lib/modules/4.11.0-kfd-compute-rocm-rel-1.6-148/build M=/usr/src/amdtPwrProf-6.01  EXTRA_CFLAGS="-I/usr/src/amdtPwrProf-6.01/inc -DKERNEL_MODULE -DLINUX -D_LINUX " modules
make[1]: Entering directory '/usr/src/linux-headers-4.11.0-kfd-compute-rocm-rel-1.6-148'
  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTAccessPmcData.o
  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTCommonConfig.o
  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTCounterAccessInterface.o
  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTHwAccessInterface.o
  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTPwrCommonHelper.o
  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTPwrProfCoreUtils.o
  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTPwrProfEntry.o
  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTPwrProfHelper.o
  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTPwrProfHwaccess.o
  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTPwrProfModule.o
  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.o
/usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.c:198:14: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .fault = pp_anon_inode_mmap_fault,
              ^
/usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.c:198:14: note: (near initialization for ‘sharedBuffer_mmap_vm_ops1.fault’)
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.o' failed
make[2]: *** [/usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.o] Error 1
Makefile:1492: recipe for target '_module_/usr/src/amdtPwrProf-6.01' failed
make[1]: *** [_module_/usr/src/amdtPwrProf-6.01] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.11.0-kfd-compute-rocm-rel-1.6-148'
Makefile:56: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: CodeXL Power Profiler driver build failed.
`

**Comment by kpenujee** [comment]
Hi,
For Power profiling driver installation, you will need dkms and linux headers that match exactly with the kernel version.

Also Power profiling on ROCm platform is not a supported/tested configuration at this point of time.

Thanks,
Kalyan P

**Comment by FalconBsp** [comment]
Thanks Kalyan. 

I am able to fix the error and modify CodeXL code according to 4.11 kernel  and Power profile is installed successfully .

I tried to run power profile on ROCm1.6 stack . Its working.

**Comment by nabar** [comment]
@FalconBsp Could you describe how you solved this issue? I encountered with the same issue.

**Comment by bpurnomo** [comment]
The Power Profiling feature has been forked to https://developer.amd.com/amd-uprof/
