### ISSUE TITLE
CodeXl suddenly became  not able to find the source code of a function even when building in debug mode and setting the source folders

### ISSUE THREAD

**Issue by dhiahassen** [GPUOpen-Tools/CodeXL#154]
I am running win7 os on a acer aspire laptop and using CodeXl  to profile my game engine , CodeXl was able to find the source code of each function , but suddenly it lost that ability for no obvious reasons , when i started it one time it wasnt able to do it as the previous run  , now the 'open source code'  option is not clickable ( from the call graph only !  )  and a double click on the function name takes me to disassebly but only if 'open source file' option was clickable , building the 'call graph' was used to take long when detecting the source was working  , but now it takes about a second to build a call graph  even for a long profiling session , i tried unistalling and reinstalling but that also didnt solve the issue , i even deleted the 'Appdata' folder after unistalling . now i want  CodeXl to be able again to find the source code of the functions , and i  want to note that i am pretty sure that the build is 'debug' and that the source folder are set correctly because ii am used to this ( i found many people arround the web complaining about the same issue )
Notes :
- In 'samples' when you run one of them and  when you click on a function and the source is not found ,CodeXl askes you to show him the source file , i dont know how it  knows that that functions exact bellongs to that file with that name that he is asking for , maybe i should enable that option and let it ask me for the source file , but i only can see 'enable alert when source file not found' option  :/
- the function name are displayed even with class names , ClassName::MethodName()
- On Project settings , 'Profile label' , in 'Application timeline trace' sub-label , there is : 'enable navigation to source code (heigh overhead)' option . and it is not set by default , when i set it , the problem persists
- For some functions , 'display in functions view' option became not clickable

**Comment by dhiahassen** [comment]
Is this project closed !

**Comment by dhiahassen** [comment]
still need help , after one year now , plz , it takes you only a minut to answer

**Comment by swarupsahoo** [comment]
If you are using CodeXL CpuProfiler, then the CpuProfiler component has been forked into another tool - "AMD uProf" (https://developer.amd.com/amd-uprof/). You can give a try to uProf CpuProfiler if that is what you are looking for.
