### ISSUE TITLE
Need a way to determine shader uniforms

### ISSUE THREAD

**Issue by masonwheeler** [GPUOpen-Tools/CodeXL#155]
CodeXL is a really excellent product that's saved me a lot of hassle in debugging OpenGL issues, but I've run into one I can't figure out.  I'm trying to track down a bug in which one specific element simply doesn't get drawn to the screen, despite all of the calls looking right and everything *else* I'm drawing showing up as expected.

As near as I can tell, the only way this could be happening is if the color uniform that's getting passed into the shader has an alpha of 0.  Unfortunately, it's not my code that's handling that; it's an external library.  And I can't find the place where the uniform is actually getting set, so trying to track this down is extremely frustrating.

I can pull up the number of the current shader program in the debugger, and I can see the individual shaders that it's composed of, but I can't get the values of the Uniforms for that shader, even while I'm paused in the debugger and it's the current shader.  It would really be nice if there was a way to retrieve this information.  (Or, if there is a way, if I knew where to get at it, because right now I can't see any option for it.)

**Comment by bpurnomo** [comment]
The kernel debugging feature is being deprecated as the compiler model has changed.
