### ISSUE TITLE
CodeXL 2.5 fails to start with 32+ cores in machine

### ISSUE THREAD

**Issue by breakin** [GPUOpen-Tools/CodeXL#156]
All I get is the splash screen and then nothing happens.

![splash](https://user-images.githubusercontent.com/4445503/31174596-530d704a-a90c-11e7-9f8b-52ea1b67e6e2.png)

Are there any logs I can consult or anything I can attach to help you debug this?

I have a AMD RX 480 graphics card and 40 CPU-cores (20 physical spread over two sockets and then hyper-threading activated).

**Comment by chesik-amd** [comment]
CodeXL will create a log file in C:\users\<currentuser>\AppData\Local\Temp. The log file is called "CodeXL-<username>.log"

Perhaps there will be some information in there to help diagnose this problem.

The other thing that might help would be to attach a debugger to the CodeXL process and see if the Call Stacks give any indication of what it might be doing.

**Comment by breakin** [comment]
Two good suggestions, thanks! I'll come back once I have more information.

**Comment by breakin** [comment]
Here is my log and a screenshot of the callstack. Will try to compile CodeXL from source to see if what the problem might be...

[CodeXL-anders.log](https://github.com/GPUOpen-Tools/CodeXL/files/1374417/CodeXL-anders.log)
![callstack](https://user-images.githubusercontent.com/4445503/31424923-418555bc-ae5d-11e7-94fa-030da303a240.png)

**Comment by breakin** [comment]
I managed to build in debug-32bit and it seems that at least there it gets stuck on initializing threads (due to me having more than 32 threads and CodeXL use a 32-bit bitmask for thread affinity).

This loop in CpuAffinityThread.cpp:52 never finished when m_core=32.

    //Let the thread affinity take affect
    while (GetCurrentProcessorNumber() != m_core)
    {
        osSleep(1);
    }

I noticed a TODO-message around supporting more than 32 cores in the debug output so it seems that this limitation it is known. I have 40 cores in my machine with hyper-threading turned on.

**Comment by kpenujee** [comment]
Hi,
Can you please let us know what is the processor that you  are trying to run CodeXL on and what features of CodeXL that are you trying to use.

Thanks,
Kalyan P

**Comment by breakin** [comment]
@kpenujee: Sure. So I am currently tring different tools to understand more about my application that runs DX11/DX12. I have an AMD RX 480 in my machine so it makes sense to look at the AMD tools. In CodeXL so far I've mostly found a nice UI around RGA, only thing I am missing is the live registers analysis.

For frame analysis there is https://gpuopen.com/radeon-gpu-profiler-1-0-2/ and I am still figuring out which tool does what best.

I do have an Intel processor in my machine so if I truly needed to profile CPU-code I guess I would get a VTune license so that is not what I am after. That being said, for frame analysis it might be nice to have a tool that understand that CPU as well to some extent.

I hope that gives you an overview. I haven't tried the frame analysis in CodeXL yet so I don't know if it is what i want...

**Comment by kpenujee** [comment]
Hi,
In CodeXL, Live register feature is not present. You need to use RGA for that (right now only CLI is available in RGA).
For FrameAnalysis, RGP (Radeon GPU Profiler) is recommended. 

For CPU profiling on system with more than 32-cores, i would recommend you to use "AMDµProf" available at http://developer.amd.com/amd-%CE%BCprof/ . Right now its a CLI only tool but you can use it on a system with more than 32-cores and since you are using Intel platform, you can run only Time based sampling.

For Power profiling, if you want graphical interface, you can continue using CodeXL. Otherwise, you can use "AMDµProf" for Power profiling of AMD CPUs/GPUs and Radeon Graphics cards.

Thanks,
Kalyan P

**Comment by breakin** [comment]
@kpenujee: So what I've found CodeXL useful for for me is as a nice IDE on top of RGA (except for live register then). Apart from that RGP seems to be more what I want, but it doesn't have any RGA features (nor any shader instruction profiling afaik). Either way I think this is a viable issue but it is not super important. If you already have an issue on 32+ cores you can close this one as duplicate. Thanks for the help!

**Comment by tangjie77wd** [comment]
@breakin @chesik-amd @kpenujee 
Hello!I create projects with OpenCL on linux . My machine : CentOS 7.3+eclipse + AMD Rx560 + amdgpu-pro-17.30-465504 + CodeXL_Linux_x86_64_2.4.60 .

    After I installed all tools above , go into the 'CodeXL_Linux_x86_64_2.4.60' folder and open a terminal ,run the command : ./CodeXL ,then CodeXL gui will appear .
    Click the 'Help' menu and then click 'Load the Teapot Sample' .
    Click the 'Profile' menu and then clike 'GPU:Performance Counters' .
    Press 'F5' on your keyboard and wait for a while.
    Close the 'AMD Teapot Example' gui and wait for a while , you will see many performance indicators in the CodeXL gui.
But I have a question these days : the Teapot sample is provided by CodeXL not myself (It exists in CodeXL as a 'CodeXL Teapot.cxl' file ,so we can load it directly in CodeXL. ) , how can i use CodeXL to test the performance of my own OpenCL projects (.cpp file and .cl file) written in the eclipse ( no .cxl file )? Any help will be much appriciate !
