### ISSUE TITLE
2.5 dpkg: error processing package codexl (--install)

### ISSUE THREAD

**Issue by reanimastudios** [GPUOpen-Tools/CodeXL#158]
Are we just tone-deaf on bug reports. Ubuntu doesn't exist w/o Debian, so expecting a basic deb to install on Debian is a prerequisite.

Preparing to unpack codexl_2.5-25_amd64.deb ...
Unpacking codexl (2.5-25) ...
Setting up codexl (2.5-25) ...
Installing CodeXL Power Profiler driver.
Installing AMD CodeXL Power Profiler Linux kernel module version 6.01.
Makefile:76: recipe for target 'dkms' failed
make: *** [dkms] Error 10
ERROR: CodeXL Power Profiler driver installation failed.
dpkg: error processing package codexl (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for desktop-file-utils (0.23-2) ...
Processing triggers for gnome-menus (3.13.3-9) ...
Processing triggers for mime-support (3.60) ...
Errors were encountered while processing:
 codexl

**Comment by kpenujee** [comment]
Hi,
What is the version of Ubuntu that you are trying to install CodeXL on?
CodeXL's Power Profiling feature requires same version linux kernel source/header files to match with the version of Ubuntu kernel running.

If you do not have kernel headers, you can use CodeXL tarbal for all other functionalities.

Thanks,
Kalyan P

**Comment by tangjie77wd** [comment]
@reanimastudios @kpenujee 
I create projects with OpenCL on linux . My machine : CentOS 7.3+eclipse + AMD Rx560 + amdgpu-pro-17.30-465504 + CodeXL_Linux_x86_64_2.4.60 .

1.    After I installed all tools above , go into the 'CodeXL_Linux_x86_64_2.4.60' folder and open a terminal ,run the command : ./CodeXL ,then CodeXL gui will appear .
2.    Click the 'Help' menu and then click 'Load the Teapot Sample' .
3.    Click the 'Profile' menu and then clike 'GPU:Performance Counters' .
4.    Press 'F5' on your keyboard and wait for a while.
5.    Close the 'AMD Teapot Example' gui and wait for a while , you will see many performance indicators in the CodeXL gui.
But I have a question these days : the Teapot sample is provided by CodeXL not myself (It exists in CodeXL as a 'CodeXL Teapot.cxl' file ,so we can load it directly in CodeXL. ) , how can i use CodeXL to test the performance of my own OpenCL projects (.cpp file and .cl file) written in the eclipse ( no .cxl file )? Any help will be much appriciate !

**Comment by kruftindustries** [comment]
See Issue #161 for more info
