### ISSUE TITLE
CodeXL crashed on clBuildProgram

### ISSUE THREAD

**Issue by reger-men** [GPUOpen-Tools/CodeXL#160]
CodeXL crashed on `clBuildProgram(..` when I try to debug my Project.
When I run the executable file, it work well.

**CodeXL** 2.5.25.0
**OS Ubuntu** 16.0.4
**OS-Kernel** 4.8.0
**GPU** Radeon WX7100
**Driver** amdgpu-pro 17.10

The Project that I try to debug is MatrixMult example, installed with AMD APP SDK.

![screenshot from 2017-10-11 21-23-00](https://user-images.githubusercontent.com/8779942/31461787-dd25edb6-aeca-11e7-8ded-3a80475fd61e.png)

![screenshot from 2017-10-11 21-30-55](https://user-images.githubusercontent.com/8779942/31462034-84345fa2-aecb-11e7-8474-94a58cc54aeb.png)

Does anybody have any idea?

**Comment by bpurnomo** [comment]
CodeXL requires OpenCL compiler that is no longer supported.
