### ISSUE TITLE
CodeXL 2.5 has no response after GPU profiling

### ISSUE THREAD

**Issue by wei-yuan** [GPUOpen-Tools/CodeXL#165]
# System info
CPU/GPU: AMD APU A10-7860k / AMD R9 380
OS: Ubuntu 16.04
GPU Driver: AMDGPU
OpenCV: 3.3.0
CodeXL: 2.5-15

# Problem statement
I wrote a tiny [OpenCV image processing code](https://github.com/wei-yuan/OpenCV_Playground/tree/master/01_sobel_and_threshold) with OpenCL open

It reads a video (only about 1:30) and processes at the same time.

When video is over  and CodeXL has no response at all

I checked htop, CPU usage rises to 100% in one core in the following "hours" 

But last time it only took me about an hour ~ one and half to finish profiling 

# My Question
1. Is CodeXL still working?
2. What might be the root cause?  I just re-format my computer few hours ago

Any advice would be appreciate

**Comment by mcleary** [comment]
Hi @wei-yuan, which CodeXL mode are you trying to use? If this is the **Application Timeline Trace** mode, what can be happening is that your application, even looking small, is potentially making hundreds of thousands of OpenCL calls. After the application finishes, CodeXL will start reading the ATP file, which contains the information of function calls. CodeXL will then allocate a timeline item for each line in this file. Depending on the size of your profiling session, this can take a very long time. Unfortunately, this has not been optimised for huge profiling sessions. You can check the size of your ATP file in the folder `~/.CodeXL/<your project name>_ProfileOutput`. Look for a file with `.atp` extension and check the size of it.

**Comment by wei-yuan** [comment]
@mcleary  sorry for the late reply!
Based on the history info from the Linux kernel
It seems that the os kernel has some difficulties load CodeXL related module
As a work around, I have to reload the Linux kernel and reinstall CodeXL related software (ex. AMDGPU) again.
