### ISSUE TITLE
Crash when profiling application

### ISSUE THREAD

**Issue by robinchrist** [GPUOpen-Tools/CodeXL#168]
What were you doing when the problem happened (optional)?
Profiled an OpenCL application

Email address (optional):
/

Operating System:
Win10-64

Call stack:
Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
osWin32CallStackReader::execute - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLOSWrappers.dll - 0x0f34e1b0 - 0x0f310000 - 0x0f34e285
osCallsStackReader::getCurrentCallsStack - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLOSWrappers.dll - 0x0f33d850 - 0x0f310000 - 0x0f33d8c1
appQtApplication::AppMemAllocFailureHandler - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x0f62a2e0 - 0x0f620000 - 0x0f62a32a
std::_MP_Rem - N/A - N/A - C:\Windows\SYSTEM32\MSVCP140.dll - 0x6fb2b5d0 - 0x6fb10000 - 0x6fb2b8ff
GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00dd7780 - 0x00dd0000 - 0x00e0bdd5
N/A - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - N/A - 0x00dd0000 - 0x00dd65e3
N/A - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - N/A - 0x00dd0000 - 0x00dd4fbb
GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00dd7780 - 0x00dd0000 - 0x00dd9761
GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00dd7780 - 0x00dd0000 - 0x00dd90ad
GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00dd7780 - 0x00dd0000 - 0x00dd8928
GPUSessionTreeItemData::LoadAndGetOccupancyTable - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x142cc100 - 0x14220000 - 0x142cc244
gpDetailedDataRibbon::AfterReplot - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x142dacc0 - 0x14220000 - 0x142e3fef
gpDetailedDataRibbon::AfterReplot - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x142dacc0 - 0x14220000 - 0x142e3934
gpExecutionMode::IsSessionRunning - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x14240340 - 0x14220000 - 0x1424057c
TSingleton<gpViewsCreator>::TSingleton<gpViewsCreator> - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x1423a6c0 - 0x14220000 - 0x142402b2
N/A - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - N/A - 0x00dd0000 - 0x00dd2e2c
GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00dd7780 - 0x00dd0000 - 0x00ddef85
GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00dd7780 - 0x00dd0000 - 0x00df094b
GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00dd7780 - 0x00dd0000 - 0x00df0b75
N/A - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - N/A - 0x00dd0000 - 0x00dd26cb
ParseAtpFile - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00dd7700 - 0x00dd0000 - 0x00dd7760
gpDetailedDataRibbon::AfterReplot - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x142dacc0 - 0x14220000 - 0x142e3ef6
gpDetailedDataRibbon::AfterReplot - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x142dacc0 - 0x14220000 - 0x142e1640
gpViewsCreator::LoadFileToView - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x14253990 - 0x14220000 - 0x14253a31
gpViewsCreator::GetWidgetForFilePath - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x142524a0 - 0x14220000 - 0x14252673
gpViewsCreator::createViewContent - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x142515a0 - 0x14220000 - 0x142516b3
appMainAppWindow::createSingleView - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x0f625c50 - 0x0f620000 - 0x0f625cd5
appApplicationStart::appMain - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x0f6216d0 - 0x0f620000 - 0x0f623898
appApplicationStart::appMain - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x0f6216d0 - 0x0f620000 - 0x0f62360e
apEventsHandler::notifyObservers - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x0fdd6c70 - 0x0fd30000 - 0x0fdd6d16
apEventsHandler::handleDebugEvent - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x0fdd6ab0 - 0x0fd30000 - 0x0fdd6aeb
apEventsHandler::handlePendingDebugEvent - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x0fdd6940 - 0x0fd30000 - 0x0fdd69f5
QMetaCallEvent::placeMetaCall - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Core.dll - 0x66536030 - 0x663b0000 - 0x66536081
QApplicationPrivate::notify_helper - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Widgets.dll - 0x642523b0 - 0x64240000 - 0x64252468
N/A - N/A - N/A - N/A - N/A - N/A - 0x00aff903

System DLL Versions:
 - aticfx32.dll: 8.17.10.1571
 - aticfx64.dll: 8.17.10.1571
 - OpenCL.dll: 22.19.685.0

OpenGL Renderer:
 - Renderer Vendor: ATI Technologies Inc.
 - Renderer Name: AMD Radeon (TM) R9 390 Series
 - Renderer Version: 4.5.13492 Compatibility Profile Context 22.19.685.0
 - Renderer Type: Installable client

Device 1 (GPU):
 - Platform ID: 1
 - Device Type: GPU
 - Device Name: Hawaii
 - Vendor: Advanced Micro Devices, Inc.

Device 2 (CPU):
 - Platform ID: 1
 - Device Type: CPU
 - Device Name: AMD Ryzen Threadripper 1950X 16-Core Processor
 - Vendor: AuthenticAMD

Platform 1:
 - Vendor: Advanced Micro Devices, Inc.
 - Name: AMD Accelerated Parallel Processing
 - Profile: FULL_PROFILE
 - Version: OpenCL 2.0 AMD-APP (2442.9)

**Comment by chesik-amd** [comment]
Hi,

Would it be possible to share the .atp file that was being loaded when this occurred?

Thanks,
Chris
