### ISSUE TITLE
Couldn't debug kernel on too large buffer

### ISSUE THREAD

**Issue by abizeau** [GPUOpen-Tools/CodeXL#169]
I recently tried to used CodeXL to debug one of my kernel. I need to create a buffer that is huge on the device (using AMD R7 200 series). Based on CodeXL system information, the device have 2,048mb as max global size and maximal global allocation size is 1,344mb.

But I'm trying to create a 512mb buffer for computing purpose and during kernel debugging (using Visual studio or CodeXL itself), my application doesn't crashes (continue to run), but I cannot enter in the Kernel to debug it when calling clEnqueueNDRangeKernel.

![problemcodexl](https://user-images.githubusercontent.com/4171034/32511498-ecfcd73e-c3c1-11e7-8478-4484b8592bd7.JPG)

I look around and didn't found anything about CodeXL buffer size limit or any others thing like that (if one, please can you link it to me).

So, on my side, I investigate that problem and I noticed that at 371720190 (almost 354.5mb), I can enter the kernel for debugging. But over that 371720190 + 1, the same kernel keep crashing with the same error (see above).

I push a bit more, and tried to send 2 buffers of ~354.5mb, and this is also crashing the debugger. For this test, I didn't perform as much test to get the exact crashing size, but 2x200mb is working and 2x256mb isn't. Which is weird, because 2x200mb=400mb and it is greater than the ~354.5mb I had with a single buffer.

**Comment by bpurnomo** [comment]
The kernel debugging feature is being deprecated as the compiler model has changed.
