### ISSUE TITLE
Crash reporter is not working

### ISSUE THREAD

**Issue by gcp** [GPUOpen-Tools/CodeXL#17]
I had a crash while exploring kernel statistics in the Analyze mode. This prompted to report the error, but after a while it came back with "Error report failed". So I'm not sure the crash reporter is working at all.

What were you doing when the problem happened (optional)?
N/A

Email address (optional):
N/A

Operating System:
Win10-64

Call stack:
Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
RaiseException - N/A - N/A - C:\WINDOWS\SYSTEM32\KERNELBASE.dll - 0x76b7da90 - 0x76ac0000 - 0x76b7dad7
CxxThrowException - N/A - N/A - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll - 0x5f5f4940 - 0x5f5f0000 - 0x5f5f49a4
qBadAlloc - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Core.dll - 0x660cae60 - 0x660b0000 - 0x660cae89

System DLL Versions:
- atioglxx.dll: 6.14.10.13431
- atio6axx.dll: 6.14.10.13431
- aticfx32.dll: 8.17.10.1452
- aticfx64.dll: 8.17.10.1452
- aticaldd.dll: 6.14.10.1848
- OpenCL.dll: 2.0.6.0

OpenGL Renderer:
- Renderer Vendor: ATI Technologies Inc.
- Renderer Name: AMD Radeon (TM) R9 390 Series
- Renderer Version: 4.5.13431 Compatibility Profile Context 16.150.2211.0
- Renderer Type: Installable client

Drivers versions:
- CAL version: 1.4.1848
- AMD Radeon Software version: 15.8

Device 1 (GPU):
- Platform ID: 1
- Device Type: GPU
- Device Name: Hawaii
- Vendor: Advanced Micro Devices, Inc.

Device 2 (CPU):
- Platform ID: 1
- Device Type: CPU
- Device Name: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
- Vendor: GenuineIntel

Platform 1:
- Vendor: Advanced Micro Devices, Inc.
- Name: AMD Accelerated Parallel Processing
- Profile: FULL_PROFILE
- Version: OpenCL 2.0 AMD-APP (2004.6)

**Comment by giladyarnitzky** [comment]
Can I ask for some additional information:
What devices were you building the kernel for? All possible devices? some of the devices?
Since you encountered before problems with VS did you run with the Stand alone or was this on VS also?
Did the crash happen when you opened the statistics view or did you take some other actions (like changing selected device)
Can you share the kernel so we can try to reproduce the crash here with the same kernel?
Thank you for your help

**Comment by doronofek** [comment]
In my tests the crash reporter appears to be working correctly. It would fail if the reporting station had networking problems preventing communication to the server that registers the report, or if the local firewall blocked this communication.

Regarding the crash itself, the crash stack is partial and does not provide much in the way of clues. Can you share some details about the scenario in which this crash occurred?
