### ISSUE TITLE
CodeXL crashes when OpenCL kernel file contains unused functions

### ISSUE THREAD

**Issue by FabioGibiino** [GPUOpen-Tools/CodeXL#171]
Hello
I observed that if my .cl file contains any function which is not used by any of the kernels in the file, CodeXL crashes as I try to debug the kernel.
Fabio

**Comment by bpurnomo** [comment]
The kernel debugging feature is being deprecated as the compiler model has changed.

**Comment by FabioGibiino** [comment]
CodeXL will not provide kernel debugging any longer?? Is any alternative being provided?
Kernel debugging is one of the main features we are using in CodeXL..

**Comment by bpurnomo** [comment]
Thank you for letting us know about your interest in OpenCL kernel debugging.  We are always interested to hear which features are most important for our users.  As the OpenCL compiler has moved to a different compiler technology, the CodeXL kernel debugging feature will no longer work with the new compiler.  We are working on an alternative solution to address this issue in the future.
