### ISSUE TITLE
Feature Request: Use right-click rather than double-click to display performance counters

### ISSUE THREAD

**Issue by boxerab** [GPUOpen-Tools/CodeXL#173]
If I need to go through a number of different runs to see the results, that is a lot of double-clicks,
It would be much easier to simply do a single right click on the items.

**Comment by chesik-amd** [comment]
I assume you are talking about the UI in the CodeXL Explorer vier?

Right click is the universal command to display a context menu, so I don't think we want to use that for opening sessions.

I just played around a bit in the CodeXL explorer view, and it appears to support multi-selection (using either ctrl-click to multi-select individual items or shift/shift-click to select a range).  Once you have multiple items selected, pressing "Enter" on the keyboard opens all of the selected sessions.  Is that sufficient for your needs?
