### ISSUE TITLE
No IBS or CLU on Ryzen for Custom Profile

### ISSUE THREAD

**Issue by mrolle45** [GPUOpen-Tools/CodeXL#174]
I just fired up CodeXL on a Ryzen 7 1700.  I went into the Custom Profile properties, and in the list of All Events, there is nothing for IBS op samples, IBS fetch sample, or Cache Line Utilization.  These items all appear in the list on my Steamroller CPU.
The same thing happened on a different Ryzen system, I don't know what model it was.

I don't have either Ryzen system available at the moment.  I assume that in the Profile tab in Project Settings, I'll still be able to select IBS or CLU as Profile Session Types.  If they are missing there too, I'll edit this Issue to that effect.

I'm supposing that the Cpu Profile driver for Ryzen is somehow not able to collect IBS or CLU samples at the same time as Timer or Event samples.

**Comment by kpenujee** [comment]
Hi,
On Ryzen, you need to Enable IBS from BIOS. 
Boot to BIOS, go to "Setup utility -> CBS -> Zen Common Options". You will find "Enable IBS" entry set to "Auto". Change it to "Enable" and reboot the system.
You should now start seeing IBS in custom profile events.

**Comment by bpurnomo** [comment]
The CPU profiling tool has been forked to https://developer.amd.com/amd-uprof/
