### ISSUE TITLE
Drivers fail to load on some Windows systems - check for this when installing CodeXL.

### ISSUE THREAD

**Issue by mrolle45** [GPUOpen-Tools/CodeXL#175]
I tried running CodeXL on an HP Pavillion, model 580-137C.  I ran the 2.5.67 install executable, and then launched CodeXL to run a simple time based profile on one of the samples.
I got a message "Failed to load driver. ...".
After some investigation, I saw that PCORE and CpuProf drivers were not known to the Service Manager.  I tried to start the PCORE driver manually, by first creating the service with the correct parameters, and then entering a start command.
The result of the start command was a message to the effect that the driver file did not have a valid signature.
Well, I know that pcore.sys is signed properly, and it runs on my PC at home (Windows 10 with a Steamroller CPU), and on a friend's PC (Windows 10 with a Ryzen CPU).
My conclusion is that HP, in their attempt to make a system that the user can't accidentally damage, has set their Windows to not load any third-party kernel drivers (that's my best guess, anyway).

**Enhancement Request**
As part of the install process, attempt to start pcore.sys and the other two drivers, and verify that this is successful.  If not successful, the install should alert the user that CodeXL will not be able to perform any CPU or Power profiles, only GPU profiles.  Better, also set something in CodeXL's configuration that will disable any attempts to create or run such profiles.

Having this warning would have saved me a couple of days of flailing around trying to get CodeXL to run profiles, and ultimately giving up on it.

**Comment by LeonsId** [comment]
several workarounds are described here:
https://www.maketecheasier.com/install-unsigned-drivers-windows10/
