### ISSUE TITLE
error when installing codexl2.5

### ISSUE THREAD

**Issue by ce1adon** [GPUOpen-Tools/CodeXL#176]
Hit this error when run sudo dpkg -i codexl_2.5-25_amd64.deb
system: Ubuntu 16.04

/usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.c:198:14: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .fault = pp_anon_inode_mmap_fault,
              ^
/usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.c:198:14: note: (near initialization for ‘sharedBuffer_mmap_vm_ops1.fault’)
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.o' failed
make[2]: *** [/usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.o] Error 1
Makefile:1492: recipe for target '_module_/usr/src/amdtPwrProf-6.01' failed
make[1]: *** [_module_/usr/src/amdtPwrProf-6.01] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.11.0-kfd-compute-rocm-rel-1.6-180'
Makefile:56: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: CodeXL Power Profiler driver build failed.
dpkg: error processing package codexl (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 codexl
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by kpenujee** [comment]
Hi,
Installing Power profiler driver requires matching kernel headers and kernel sources present on the system.
Currently installing power profiling driver on ROCM system is not supported.
However this failure does not stop you from using other features of CodeXL.

Thanks,
Kalyan P

**Comment by dutt** [comment]
How do I fix this? I tried getting the kernel source through `apt-get source linux-source` and headers through `apt-get install linux-headers-$(uname -r)` but I still get the same error, any help would be appreciated. Or how do I do the install without the power profiling? Currently I can't really install the tool at all.

I'm on Ubuntu 16.04.

**Comment by bpurnomo** [comment]
The power profiling feature has been forked off to https://developer.amd.com/amd-uprof/
