### ISSUE TITLE
Failed to write output file (path changed)

### ISSUE THREAD

**Issue by rNoz** [GPUOpen-Tools/CodeXL#178]
I run CodeXL, select one recent project, do GPU profiling (Profile: Application Timeline Trace), it works. 

It shows:
```
Session output path: /home/user/.CodeXL/CodeXL/BinomialOption_ProfilerOutput/Dec-13-2017_13-36/Dec-13-2017_13-36.atp
```

Then, I go to project settings and change an argument of the application. Run again the same Start profiling. It fails:
```
Failed to write output file: /CodeXL/BinomialOption_ProfilerOutput/Dec-13-2017_13-37/Dec-13-2017_13-37.atp
```

The path has changed from /home/user/.CodeXL/CodeXL to /CodeXL. Therefore, it has not permissions and fails. If I go to Tools > Options, the Log Files and Images Directory is still /home/user/.CodeXL/CodeXL.

I did another test, it failed with just opening Project Settings without modifying any argument of the application.

**Comment by chesik-amd** [comment]
This is a known issue in CodeXL 2.5.  This should be fixed in the next version of CodeXL.

**Comment by chesik-amd** [comment]
This should no longer be an issue in CodeXL 2.6
