### ISSUE TITLE
Unable to open recorded profile traces

### ISSUE THREAD

**Issue by FilipVaverka** [GPUOpen-Tools/CodeXL#179]
Opening profilling results of "GPU: Performance Counters" or "Application Timeline Trace" causes CodeXL 2.5.65 to crash with:
> Operating System:
> Win10-64
> 
> Call stack:
> Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
> memcpy - N/A - N/A - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll - 0x6da1d180 - 0x6da10000 - 0x6da1d3cf
> GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x77417780 - 0x77410000 - 0x77419761
> GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x77417780 - 0x77410000 - 0x774190ad
> GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x77417780 - 0x77410000 - 0x77418928
> GPUSessionTreeItemData::LoadAndGetOccupancyTable - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x5012c100 - 0x50080000 - 0x5012c244
> gpDetailedDataRibbon::AfterReplot - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x5013acc0 - 0x50080000 - 0x50143fef
> gpDetailedDataRibbon::AfterReplot - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x5013acc0 - 0x50080000 - 0x50143934
> gpExecutionMode::IsSessionRunning - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x500a0340 - 0x50080000 - 0x500a057c
> TSingleton<gpViewsCreator>::TSingleton<gpViewsCreator> - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x5009a6c0 - 0x50080000 - 0x500a02b2
> N/A - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - N/A - 0x77410000 - 0x77412e2c
> GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x77417780 - 0x77410000 - 0x7741ef85
> GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x77417780 - 0x77410000 - 0x7743094b
> GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x77417780 - 0x77410000 - 0x77430b75
> N/A - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - N/A - 0x77410000 - 0x774126cb
> ParseAtpFile - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x77417700 - 0x77410000 - 0x77417760
> gpDetailedDataRibbon::AfterReplot - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x5013acc0 - 0x50080000 - 0x50143ef6
> gpDetailedDataRibbon::AfterReplot - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x5013acc0 - 0x50080000 - 0x50141640
> gpViewsCreator::LoadFileToView - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x500b3990 - 0x50080000 - 0x500b3a31
> gpViewsCreator::GetWidgetForFilePath - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x500b24a0 - 0x50080000 - 0x500b2673
> gpViewsCreator::createViewContent - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x500b15a0 - 0x50080000 - 0x500b16b3
> appMainAppWindow::createSingleView - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x73735c50 - 0x73730000 - 0x73735cd5
> appApplicationStart::appMain - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x737316d0 - 0x73730000 - 0x73733898
> appApplicationStart::appMain - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x737316d0 - 0x73730000 - 0x7373360e
> apEventsHandler::notifyObservers - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x66e76c70 - 0x66dd0000 - 0x66e76d16
> apEventsHandler::handleDebugEvent - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x66e76ab0 - 0x66dd0000 - 0x66e76aeb
> apEventsHandler::handlePendingDebugEvent - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x66e76940 - 0x66dd0000 - 0x66e769f5
> QMetaCallEvent::placeMetaCall - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Core.dll - 0x68266030 - 0x680e0000 - 0x68266081
> QApplicationPrivate::notify_helper - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Widgets.dll - 0x67cb23b0 - 0x67ca0000 - 0x67cb2468
> QApplication::notify - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Widgets.dll - 0x67cb0460 - 0x67ca0000 - 0x67cb13f1
> _RTDynamicCast - N/A - N/A - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll - 0x6da13ef0 - 0x6da10000 - 0x6da13f09
> appQtApplication::notify - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x73739e20 - 0x73730000 - 0x73739e62
> appQtApplication::notify - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x73739e20 - 0x73730000 - 0x73739fbf
> QCoreApplication::notifyInternal - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Core.dll - 0x68242d60 - 0x680e0000 - 0x68242dd9
> QGuiApplicationPrivate::processMouseEvent - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Gui.dll - 0x66f96f70 - 0x66f70000 - 0x66f97856
> RtlAllocateHeap - N/A - N/A - C:\WINDOWS\SYSTEM32\ntdll.dll - 0x76f613b0 - 0x76f20000 - 0x76f61658
> _RTDynamicCast - N/A - N/A - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll - 0x6da13ef0 - 0x6da10000 - 0x6da13f3a
> _RTDynamicCast - N/A - N/A - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll - 0x6da13ef0 - 0x6da10000 - 0x6da13f09
> _RTDynamicCast - N/A - N/A - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll - 0x6da13ef0 - 0x6da10000 - 0x6da13f09
> appQtApplication::notify - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x73739e20 - 0x73730000 - 0x73739e62
> 
> System DLL Versions:
>  - aticfx32.dll: 8.17.10.1586
>  - aticfx64.dll: 8.17.10.1586
>  - OpenCL.dll: 23.20.15002.11
> 
> OpenGL Renderer:
>  - Renderer Vendor: ATI Technologies Inc.
>  - Renderer Name: Radeon RX Vega
>  - Renderer Version: 4.5.13506 Compatibility Profile Context 23.20.15002.11
>  - Renderer Type: Installable client
> 
> Device 1 (GPU):
>  - Platform ID: 1
>  - Device Type: GPU
>  - Device Name: Fiji
>  - Vendor: Advanced Micro Devices, Inc.
> 
> Device 2 (GPU):
>  - Platform ID: 1
>  - Device Type: GPU
>  - Device Name: gfx900
>  - Vendor: Advanced Micro Devices, Inc.
> 
> Device 3 (CPU):
>  - Platform ID: 1
>  - Device Type: CPU
>  - Device Name: AMD Ryzen 7 1800X Eight-Core Processor
>  - Vendor: AuthenticAMD
> 
> Platform 1:
>  - Vendor: Advanced Micro Devices, Inc.
>  - Name: AMD Accelerated Parallel Processing
>  - Profile: FULL_PROFILE
>  - Version: OpenCL 2.1 AMD-APP (2527.7)

**Comment by chesik-amd** [comment]
Were these profile sessions collected with the current version of CodeXL or with a previous version?  Would it be possible for you to zip and attach the profile data directory for the session that causes this issue? You can navigate to the session data directory by right clicking on the session in the CodeXL Explorer and choosing "Open Containing Folder" from the menu.

**Comment by FilipVaverka** [comment]
I don't have any sessions from previous versions, so I haven't tried that. It happens either right after profiling is done or when I double click on created profile data (after restarting CodeXL). Here is profile I just created: [Dec-16-2017_17-16.zip](https://github.com/GPUOpen-Tools/CodeXL/files/1564914/Dec-16-2017_17-16.zip)
and here stack trace produced by CodeXL when I attempt to open it:

> Call stack:
> Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
> osWin32CallStackReader::execute - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLOSWrappers.dll - 0x5005e1b0 - 0x50020000 - 0x5005e285
> osCallsStackReader::getCurrentCallsStack - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLOSWrappers.dll - 0x5004d850 - 0x50020000 - 0x5004d8c1
> appQtApplication::AppMemAllocFailureHandler - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x504ca2e0 - 0x504c0000 - 0x504ca32a
> std::_MP_Rem - N/A - N/A - C:\WINDOWS\SYSTEM32\MSVCP140.dll - 0x710fb660 - 0x710e0000 - 0x710fb97f
> GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00587780 - 0x00580000 - 0x005bbdd5
> N/A - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - N/A - 0x00580000 - 0x005865e3
> N/A - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - N/A - 0x00580000 - 0x00584fbb
> GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00587780 - 0x00580000 - 0x00589761
> GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00587780 - 0x00580000 - 0x005890ad
> GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x00587780 - 0x00580000 - 0x00588928
> GPUSessionTreeItemData::LoadAndGetOccupancyTable - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x158bc100 - 0x15810000 - 0x158bc244
> gpSessionTreeNodeData::DeleteSessionFilesFromDisk - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x158bd230 - 0x15810000 - 0x158be1b7
> gpSessionTreeNodeData::DeleteSessionFilesFromDisk - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x158bd230 - 0x15810000 - 0x158bdbb6
> SessionManager::CheckAndDeleteSessionFiles - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x158c16f0 - 0x15810000 - 0x158c2064
> gpViewsCreator::LoadFileToView - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x15843990 - 0x15810000 - 0x15843a31
> gpViewsCreator::GetWidgetForFilePath - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x158424a0 - 0x15810000 - 0x15842673
> gpViewsCreator::createViewContent - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x158415a0 - 0x15810000 - 0x158416b3
> appMainAppWindow::createSingleView - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x504c5c50 - 0x504c0000 - 0x504c5cd5
> appApplicationStart::appMain - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x504c16d0 - 0x504c0000 - 0x504c3898
> appApplicationStart::appMain - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x504c16d0 - 0x504c0000 - 0x504c360e
> apEventsHandler::notifyObservers - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x0f906c70 - 0x0f860000 - 0x0f906d16
> apEventsHandler::handleDebugEvent - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x0f906ab0 - 0x0f860000 - 0x0f906aeb
> apEventsHandler::handlePendingDebugEvent - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x0f906940 - 0x0f860000 - 0x0f9069f5
> QMetaCallEvent::placeMetaCall - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Core.dll - 0x50246030 - 0x500c0000 - 0x50246081
> QApplicationPrivate::notify_helper - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Widgets.dll - 0x64ea23b0 - 0x64e90000 - 0x64ea2468
> N/A - N/A - N/A - N/A - N/A - N/A - 0x008ff7db

**Comment by chesik-amd** [comment]
Sorry for the delay in responding here.  This appears to be caused by a bug in the .occupancy file parser.  Your .csv and .occupancy files use a semi-colon as the list separator due to your locale settings.  Unfortunately, the occupancy data file parser doesn't read the value of the list separator that's listed at the top of the .occupancy file.  We will get this fixed, but the workaround for now is unfortunately to not generate the .occupancy file (there's a checkbox for this in the "GPU Profile: Perf. Counters" page in the Project Settings dialog in CodeXL).

**Comment by FilipVaverka** [comment]
I see, I had some issues with CodeXL and locale before... anyways thanks for the update.

**Comment by robinchrist** [comment]
Which is the expected seperator? `,`?

**Comment by chesik-amd** [comment]
Yes, good point.  Manually editing the .occupancy file after it is generated would be another workaround.

This works here because there are no floating point numbers in the .occupancy file (which under a different locale could use a comma instead of a period as the decimal character).

**Comment by chesik-amd** [comment]
This should no longer be an issue in CodeXL 2.6
