### ISSUE TITLE
Please support alternative dbghelp.dll files

### ISSUE THREAD

**Issue by tim-lebedkov** [GPUOpen-Tools/CodeXL#184]
Please allow choosing alternative dbghelp.dll file for debug information retrieval.

I use Delphi, but CodeXL does not support its debug information.

**Comment by bpurnomo** [comment]
Please check out https://developer.amd.com/amd-uprof/

**Comment by tim-lebedkov** [comment]
I tried out uProf. It does not seem to have this functionality. Why did you close this issue?

**Comment by bpurnomo** [comment]
Hi,
   We don't have a plan to provide an alternative dbghelp.dll.  However, we would be willing to accept PR for such feature.
