### ISSUE TITLE
No results for clEnqueueReadBufferRect

### ISSUE THREAD

**Issue by robinchrist** [GPUOpen-Tools/CodeXL#185]
Hello,

It seems like this is a driver issue (updated to 18.2.1 yesterday)... However!
Before (different kernel size):
![image](https://user-images.githubusercontent.com/22774099/35767049-94e691c6-08e4-11e8-9f62-ec1d08d567c8.png)

After:
![image](https://user-images.githubusercontent.com/22774099/35767031-2cd84188-08e4-11e8-98e8-7054fb91fbd7.png)

![image](https://user-images.githubusercontent.com/22774099/35767032-35d9790a-08e4-11e8-89e7-8125036e2eb1.png)

[Feb-03-2018_13-10.zip](https://github.com/GPUOpen-Tools/CodeXL/files/1691720/Feb-03-2018_13-10.zip)

However, this seems *NOT* to be an issue with clEnqueueReadBuffer:
![image](https://user-images.githubusercontent.com/22774099/35767085-5c52b7c6-08e5-11e8-9eb4-7557933e1d86.png)

System info:
Windows 10 Pro (Version 10.0.16299 Build 16299)
Ryzen Threadripper 1950X
AMD R9 390X
Radeon Software Version 18.2.1 (Radeon Settings Version 2018.0131.1849.33856, Driver Packaging Version 17.50.17.03-180131a-323782E-RadeonSoftwareAdrenalin, OpenCL™ Version 23.20.15017.3010)

**Comment by chesik-amd** [comment]
Do you still see this issue with the most recent driver? I just took a look at a simple test case to compare the data transfer timing reported for both clEnqueueReadBufferRect and clEnqueueReadBuffer and the results look reasonable.  I haven't tried running on a Hawaii card, so it's possible I'm not seeing the issue if it is in fact ASIC-specific.

Thanks,
Chris

**Comment by bpurnomo** [comment]
Closing the issue since there is no action item on CodeXL side
