### ISSUE TITLE
OpenCL 2.0 support missing

### ISSUE THREAD

**Issue by Jasper-Bekkers** [GPUOpen-Tools/CodeXL#19]
This is (arguably) a pretty major feature request, but it's the one thing I've been looking forward to in a CodeXL release. However, it seems that CodeXL 2.0 still doesn't support OpenCL 2.0, when I try to analyze my shaders I keep getting greeted with this message:

![image](https://cloud.githubusercontent.com/assets/49594/14812424/7e1e2558-0b9d-11e6-900f-db82c2b1194d.png)

It seems to be missing since at least 2014 https://github.com/GPUOpen-Tools/CodeXL/blob/eaf371c42ff3063bba8b4196aeb59659befeb104/CodeXL/Components/ShaderAnalyzer/AMDTKernelAnalyzer/src/kaApplicationCommands.cpp#L400

**Comment by doronofek** [comment]
Hi Jasper-Bekkers,
Unfortunately CodeXL 2.0 does not support OpenCL 2.0. This feature is definitely on the wish-list but I can't share any specific dates.

**Comment by Jasper-Bekkers** [comment]
@doronofek correct, this is a feature request for proper OpenCL 2.0 support.

**Comment by VincentSC** [comment]
What is the status of this?
