### ISSUE TITLE
Crash when maximizing the window

### ISSUE THREAD

**Issue by maxvan** [GPUOpen-Tools/CodeXL#191]
I double clicked on the window title while looking at the call tree and the app crashed.

Using CodeXL version 2.5.67.0 on Windows 10 x64.

Relevant part of the logs:
```
2018.03.14	11:25:37.411	#1728153175411	#ERROR	#0	#17356	#appMsgHandler	#src\appEventObserver.cpp	#316	#Qt Fatal Message: createDIB: CreateDIBSection failed.
2018.03.14	11:25:37.457	#1728153391457	#ERROR	#0	#17356	#afPluginConnectionManager::~afPluginConnectionManager	#src\afPluginConnectionManager.cpp	#57	#Assertion failure (0 == m_runModeManagers.size())
2018.03.14	11:25:37.723	#1728153392723	#ERROR	#0	#17356	#apEventsHandler::notifyPendingEventsNotifiers	#Events\src\apEventsHandler.cpp	#674	#Assertion failure (0 < amountOfPendingEventsNotifiers)
2018.03.14	11:25:37.928	#1728153392928	#ERROR	#0	#17356	#apEventsHandler::notifyPendingEventsNotifiers	#Events\src\apEventsHandler.cpp	#674	#Assertion failure (0 < amountOfPendingEventsNotifiers)
2018.03.14	11:25:37.939	#1728153398939	#ERROR	#0	#17356	#appMsgHandler	#src\appEventObserver.cpp	#316	#Qt Warning Message: QThread: Destroyed while thread is still running
2018.03.14	11:25:37.638	#1728153401638	#INFO	#0	#17356	#osDebugLog::terminate	#src\common\osDebugLog.cpp	#395	#Debug log is terminated
```

**Comment by kpenujee** [comment]
Hi Maxvan,
Is it Instruction based sampling that you were running when the crash occurred? 
What is the memory consumption shown in taskbar for CodeXL when the crash occurred? was it exceeding 2GB?
What is the platform that you are using?

Recently, AMD has released dedicated CPU/Power profiling tool with Zen support and can be downloaded from:
https://developer.amd.com/amd-uprof/

i would suggest to try it out and let us know if you still see the tool (AMDuProf) crashing in your scenario.


Thanks,
Kalyan P

**Comment by maxvan** [comment]
Hey,
I was using sampling, I'm not sure what the memory usage was but I would expect it to be beyond 2GB yes. Running on Windows 10.

I've tried uProf. It's an interesting tool. It works well enough but isn't advanced enough for my usage. I need to be able to drill into much more detail into my app.

Thanks!
Max.

**Comment by bpurnomo** [comment]
Closing the issue as CPU profiling has been forked off to uProf.
