### ISSUE TITLE
Crash when viewing a large trace

### ISSUE THREAD

**Issue by maxvan** [GPUOpen-Tools/CodeXL#192]
Ran a profiling session on an executable that runs for ~15 mins. CodeXL started processing the trace and eventually crashed. Log:

```
2018.03.14	16:15:54.282	#1785983707282	#INFO	#0	#27568	#CommandsHandler::onStopProfiling	#src\CommandsHandler.cpp	#1552	#CPU Profile ended
2018.03.14	16:16:25.639	#1786087273639	#ERROR	#0	#14292	#PeFile::Open	#src\PeFile.cpp	#111	#Executable (PE) C:\Windows\System32\shell32.dll failed to open
2018.03.14	16:16:26.455	#1786090241455	#ERROR	#0	#18848	#MemoryMap::CreateView	#src\Windows\MemoryMap.cpp	#104	#Could not create view of the mapped file, error 0x8
2018.03.14	16:16:26.670	#1786090241670	#ERROR	#0	#18848	#PrdUserCssRcuHandlerPool::RemapPrdFile	#src\Windows\PrdUserCss.cpp	#228	#Could not create a mapped file view
2018.03.14	16:16:26.526	#1786090242526	#ERROR	#0	#10236	#MemoryMap::CreateView	#src\Windows\MemoryMap.cpp	#104	#Could not create view of the mapped file, error 0x8
2018.03.14	16:16:26.723	#1786090242723	#ERROR	#0	#10236	#PrdUserCssRcuHandlerPool::RemapPrdFile	#src\Windows\PrdUserCss.cpp	#228	#Could not create a mapped file view
2018.03.14	16:16:26.294	#1786090243294	#ERROR	#0	#23016	#MemoryMap::CreateView	#src\Windows\MemoryMap.cpp	#104	#Could not create view of the mapped file, error 0x8
2018.03.14	16:16:26.407	#1786090243407	#ERROR	#0	#23016	#PrdUserCssRcuHandlerPool::RemapPrdFile	#src\Windows\PrdUserCss.cpp	#228	#Could not create a mapped file view
[... a lot more of this....]
```

**Comment by mcleary** [comment]
Can you provide details of your machine? How much memory do you have? Are running a 32bit Windows?

**Comment by maxvan** [comment]
Windows 10 x64
Ryzen ThreadRipper 1950X 16-Core
64GB RAM

**Comment by mcleary** [comment]
So, here is the deal. Looks like you have more than enough memory in your system, however, CodeXL, on Windows is a 32bit application. This means that CodeXL cannot allocate more than 4GB of memory. Keep an eye on the memory consumption of CodeXL while loading your trace results, if you see the number approaching 4GB you will know it won't work. Alternatively, you can try to open your trace file on Linux, since under that OS, CodeXL is a 64bit application.

**Comment by maxvan** [comment]
That's good to know, thanks. Is it planned to have a 64bit Windows version?

**Comment by mcleary** [comment]
I am not a CodeXL maintainer so I cannot answer with certainty, however, I would not expect it any time soon.

On a side note, this does not mean that CodeXL cannot profile 64bit applications, it has a 64bit backend, the main problem is that the "front-end" GUI stuff, which loads the results, is a 32bit executable.

**Comment by maxvan** [comment]
Ok. If it's already 64bit on linux it shouldn't be hard to have a 64bit version on windows

**Comment by bpurnomo** [comment]
For CPU profiling tool, check out https://developer.amd.com/amd-uprof/
