### ISSUE TITLE
Crash on Fedora 27

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [GPUOpen-Tools/CodeXL#193]
Tried the latest CodeXL release (tar.gz and .rpm variants). Both crash during startup without any windows. Only dump file is available:
[CodeXL-bin.zip](https://github.com/GPUOpen-Tools/CodeXL/files/1826807/CodeXL-bin.zip)

My system:
* Fedora 27, KDE
* `uname -r` -  4.15.9-300.fc27.x86_64
* CPU - i7-3630QM

**Comment by naibaf7** [comment]
I suspect it's a Qt5 issue.
This solved it for me:
```
sudo cp /lib64/libQt* /opt/CodeXL_2.5-25/RuntimeLibs/QT/.
```
