### ISSUE TITLE
CodeXL and Visual Studio 2017

### ISSUE THREAD

**Issue by JacquesRoth** [GPUOpen-Tools/CodeXL#194]
I downloaded and installed CodeXL, but no extension was applied to my Visual Studio 2017.  I want to be able to disassemble the OpenCL AMD Radeon code in a project.  Is there any way to get a CodeXL extension for Visual Studio 2017?

**Comment by kpenujee** [comment]
Hi JacquesRoth,
At this point of time, there is no plan to add support in CodeXL for VS2017.
We will keep you posted.

Thanks,
Kalyan P

**Comment by mcleary** [comment]
If you take a look at the commits, the whole VS plugins are now deprecated. All references for the VS extension were removed, so do not expect the support to come back.
