### ISSUE TITLE
Running GPU Profile fails with CodeXL 2.5 and ROCm 1.7.1 on Ubuntu 16.04.3

### ISSUE THREAD

**Issue by iktretyakov** [GPUOpen-Tools/CodeXL#195]
I am trying to do a simple GPU profile using CodeXL 2.5 and ROCm 1.7.1 on either the HelloWorld openCL application, the teapot example, or the matrix multiply and am getting the same generic error message each time.
Unable to gather profile data. This error can occur for one of several reasons:
The active project is not an OpenCL program.
The active project is an OpenCL program, but it did not enqueue any kernels.
The active project is an OpenCL program, but it did not enqueue any kernels listed in the Profile Specific Kernels section.
The active project does not compile or run properly (try running it manually).
You do not have write access to the profile output directory.
Collecting OpenCL performance counters when running on the ROCm stack might not be supported.Try enabling the "HSA" option on the "GPU Profile: Perf. Counters" project setting page. 

In the terminal window I see the following messages:

Failed to generate profile result /root/.CodeXL/CodeXL/CodeXL Matrix Multiply_ProfilerOutput/Mar-22-2018_17-48/Mar-22-2018_17-48.occupancy.
Failed to generate profile result /root/.CodeXL/CodeXL/CodeXL Matrix Multiply_ProfilerOutput/Mar-22-2018_17-48/Mar-22-2018_17-48.csv.

I have tried changing the project settings, but still cannot get the GPU Profiling to work. My system is running Ubuntu 16.04.3 with the 4.13.0-32-generic kernel. My card is a R9 Fury running on an Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7.

Could someone please help me troubleshoot this issue and isolate the cause and fix?

**Comment by chesik-amd** [comment]
OpenCL profiling isn't supported on the ROCm platform by the version of RCP (rcprof) that is installed with CodeXL 2.5.  We are planning to add this support in a future version of RCP and CodeXL.
