### ISSUE TITLE
Request for Documentation and CPU Profiler usage

### ISSUE THREAD

**Issue by john-terraspace** [GPUOpen-Tools/CodeXL#197]
Could we please get a decent manual for CodeXL, especially for the CPU profiling that provides descriptions of the event types, nominal ranges, what is considered a high value and just something to generally help interpret the results. Ideally a way to provide some sort of suggestions, for example
if we have a high value in Inst Pipe Stall it would indicate that the operation is dependant on prior results which aren't ready.
I often notice this on RET instructions, so I assume that AMD Zen cores are not attempting to speculative execute across a ret instruction, it appears as if all results must be ready by the RET.

**Comment by john-terraspace** [comment]
In addition then it would be great if the event sample columns were colour-coded (green->red) based on their nominal / expected ranges.

Given a known reciprocal throughput and latency for an instruction ideally we want to see when we're not hitting those marks for whatever reason, some form of more detailed analysis mode that makes it easier to identify the causes, cache miss, stall, no available EU's .. etc

**Comment by swarupsahoo** [comment]
Thanks for your suggestions. We will update CpuProfiler documentation considering your suggestions in future releases. Going onwards CpuProfiler will be part of a new tool - AMD uProf. You may download it from here - https://developer.amd.com/amd-uprof/
