### ISSUE TITLE
Expose ThreadTracer

### ISSUE THREAD

**Issue by Jasper-Bekkers** [GPUOpen-Tools/CodeXL#20]
Right now ThreadTracer is marked / ifdef'ed out of public builds, but it's been an invaluable tool on other platforms, so I would love to see it in the public CodeXL builds.

**Comment by doronofek** [comment]
Hi,
Public publish of thread trace has been discussed several times. It may be published in the future but unfortunately I cannot disclose any specific plans or dates.

**Comment by Jasper-Bekkers** [comment]
Please consider opening up the roadmap to the public.
