### ISSUE TITLE
CodeXL fails to build 

### ISSUE THREAD

**Issue by JehandadKhan** [GPUOpen-Tools/CodeXL#200]
When building CodeXL on a Ubuntu 16.04 machine the following link-errors are observed:
(Truncated Output)
```
Linking: variant_release/AMDTRemoteAgent/CodeXLRemoteAgent-bin

CodeXL/Common/Lib/Ext/Boost/boost_1_59_0/boost/regex/v4/perl_matcher_non_recursive.hpp:991: undefined reference to `boost::match_results
CodeXL/Common/Lib/Ext/Boost/boost_1_59_0/boost/regex/v4/perl_matcher_common.hpp:333: undefined reference to `boost::match_results
```
The issue might be related to [this link](https://stackoverflow.com/questions/47017969/boost-regex-undefined-references-when-linking) but I am not sure since I am not familiar with scons.
The full output with all the boost template instantiations is attached.

[boost_ld_error.log](https://github.com/GPUOpen-Tools/CodeXL/files/1938911/boost_ld_error.log)

**Comment by mcleary** [comment]
For some reason, the `-isystem` include flag for the boost includes is not working.
As a temporary fix you can remove the `-Werror` flag to avoid treating warning as errors.
The file you are looking for is

> CodeXL/Components/CpuProfiling/Backend/AMDTCpuProfilingCLI/SConscript

The build scripts for Linux is not fully working, at least not the version on the master branch, so you will probably see more errors after removing -Werror

**Comment by chesik-amd** [comment]
When building on recent Ubuntu versions, you will need to pass additional parameters to the build script. Please take a look at the following info and see if it helps: https://github.com/GPUOpen-Tools/CodeXL/blob/master/BUILD.md#specific-build-instructions-recent-ubuntu-versions

**Comment by JehandadKhan** [comment]
Currently, I am not using CodeXL since it does not support ROCm.
