### ISSUE TITLE
CPU Profiling Presets not available on Threadripper

### ISSUE THREAD

**Issue by robinchrist** [GPUOpen-Tools/CodeXL#202]
Hi,

All the CPU profiling presets mentioned in the docs (like "Assess performance") are not available on my Threadripper 1950X workstation.

Is this a known issue?

**Comment by swarupsahoo** [comment]
Hi,
CodeXL CpuProfiler forked into a new tool- AMD uProf (https://developer.amd.com/amd-uprof/)
uProf supports Threadripper CPUs.

**Comment by KingDuckZ** [comment]
@swarupsahoo thanks for the info! do you know where the source code for uprof is? The tar on the page you linked only contains binary stuff.

**Comment by swarupsahoo** [comment]
@KingDuckZ uProf is not yet open sourced. Only the binaries get released.
