### ISSUE TITLE
"Break (F6)" may lead to CodeXL hanging

### ISSUE THREAD

**Issue by lobneroO** [GPUOpen-Tools/CodeXL#205]
For a certain program that I try to debug with CodeXL, everytime I "break" the application, CodeXL hangs. In the "Debugged Process Events" I get a "Break" event and maybe 1-2 "Thread Created: 0" events (I am not sure if they are from breaking or from ending the application, as the event widget doesn't scroll down to the bottom and the program already hangs). The progress bar in the bottom right corner shows me a 7 to 9% progress (depending on what is activated in my application), but it stops there and CodeXL is not responding anymore (and says so in the window title). 

I can end the debugged application in my task manager and CodeXL will then work again. I can't share the code of my application, but I have attached the log files I found.
[CodeXLRemoteAgent-TimL.log](https://github.com/GPUOpen-Tools/CodeXL/files/1994268/CodeXLRemoteAgent-TimL.log)
[CodeXLRemoteDebuggingServer-TimL.log](https://github.com/GPUOpen-Tools/CodeXL/files/1994269/CodeXLRemoteDebuggingServer-TimL.log)
[CodeXLServers-TimL.log](https://github.com/GPUOpen-Tools/CodeXL/files/1994270/CodeXLServers-TimL.log)
[CodeXL-TimL.log](https://github.com/GPUOpen-Tools/CodeXL/files/1994271/CodeXL-TimL.log)

My application uses OpenSceneGraph, which uses some Legacy OpenGL code.

Looking the Task Manager, the ram consumption rised to about 500mb for CodeXL and then stops once program freezes. CPU consumption is 0% then as well.

**Comment by lobneroO** [comment]
By chance I found out that the CodeXL does not freeze upon using "Break", if I do the following:

1. Let CodeXL reach the Breakpoint for wglSwapBuffers first
2. Disable the wglSwapBuffers Breakpoint and continue debugging (F5)
3. Let it run to the point where I want to debug and then use "Break" (F6) manually.

**Comment by bluebear94** [comment]
I'm having a similar problem, except that CodeXL hangs when I try to break on `glXSwapBuffers` (the X equivalent of `wglSwapBuffers`) as well. I've attached my own logs.

[CodeXLServers-uruwi.log](https://github.com/GPUOpen-Tools/CodeXL/files/2162886/CodeXLServers-uruwi.log)
[CodeXL-uruwi.log](https://github.com/GPUOpen-Tools/CodeXL/files/2162887/CodeXL-uruwi.log)
