### ISSUE TITLE
Cannot find vega gpu in ubuntu 16.04.1

### ISSUE THREAD

**Issue by ce1adon** [GPUOpen-Tools/CodeXL#209]
Cannot find vega gpu in ubuntu 16.04.1 with rocm 1.8.118 and opencl 1.2.0-2018050513
Attached a screenshot

![screenshot from 2018-06-11 11-17-25](https://user-images.githubusercontent.com/24684383/41250414-b8c902d6-6d6b-11e8-9bd7-0d671911217d.png)

**Comment by tekcomm** [comment]
ce1adon, Hy celdon try my live cd it has the latest vega patches/firmware  and also a patched pwr kernel module & bionic 18.04 / 4.16 kernel and is memory based live system. https://github.com/tekcomm/linux-kernel-amdgpu-binaries.
Or for the entire live bionic system
https://github.com/RadeonOpenCompute/ROCm/issues/361

**Comment by jlgreathouse** [comment]
Can you see your device outside of CodeXL? For instance, if you run `/opt/rocm/opencl/bin/x86_64/clinfo`, do you see your GPU in the device list? If you run `lspci | grep VGA`, what devices come up?

If you do see your device listed using clinfo, but not under CodeXL, then this may be a problem in CodeXL.

If you cannot see your device using clinfo, but you do see it using lspci, then this may be an issue with ROCm (which @tekcomm 's live CD may solve), or it may be an issue such as having your GPU installed on a PCIe bus that ROCm does not support (e.g. using a CPU without PCIe gen 3 atomics, having your GPU installed in a PCIe gen 2 slot, etc.). In either either case, that is likely not a CodeXL issue and keeping this bug open here (rather than in e.g. the ROCm GitHub repo) may delay finding help with your problem.

If you do not see your Vega device when running lspci, then you may have much greater hardware problems.

**Comment by ce1adon** [comment]
@jlgreathouse @tekcomm 
Here is my result to run /opt/rocm/opencl/bin/x86_64/clinfo and lspci | grep VGA

/opt/rocm/opencl/bin/x86_64/clinfo
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.1 AMD-APP.internal (2617.0)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_object_metadata cl_amd_event_callback 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 Device 687f
  Device Topology:				 PCI[ B#38, D#0, F#0 ]
  Max compute units:				 56
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1622Mhz
  Address bits:					 64
  Max memory allocation:			 7287183769
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 8
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 26751
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 8573157376
  Constant buffer size:				 7287183769
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 65536
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 2992216473
  Max global variable size:			 7287183769
  Max global variable preferred total size:	 8573157376
  Max read/write image args:			 64
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7fb104083ff0
  Name:						 gfx900
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 2617.0 (HSA1.1,LC)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 
  Extensions:					 cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program 


lspci | grep VGA
26:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 687f (rev c3)

**Comment by tekcomm** [comment]
Jing Zhou is correct.


Ji Long.

**Comment by chesik-amd** [comment]
This should no longer be an issue in CodeXL 2.6
