### ISSUE TITLE
Building without problems/Cant run CodeXL

### ISSUE THREAD

**Issue by kpontzolkova** [GPUOpen-Tools/CodeXL#21]
Hello everyone,
I have Ubuntu 14.04 and I am a relatively new user.

I have followed the insructions from the file BUILD.md for linux.

CD to local copy of /CodeXL/Util/linux/
Run ./buildCodeXLFullLinuxProjects

It runs without an error.

Then, in /Output_x86_64/release/bin, I am trying to run CodeXLAnalyser:

Output_x86_64/release/bin$ ./CodeXLAnalyzer

Error: No valid command. Please run -h for available commands.

So what am i doing wrong. Thank you for your time

p.s. the precompiled version runs without problems, but i need to compile and run :D

**Comment by kpenujee** [comment]
Hi,
You need to run ./CodeXL 
"CodeXLAnalyzer" is Commane-Line Iinterface for static analysis of OpenCL/OpenGL kernels/shaders.

Thanks,
Kalyan P

**Comment by kpontzolkova** [comment]
[README (copy).txt](https://github.com/GPUOpen-Tools/CodeXL/files/259317/README.copy.txt)
..
Running 

* Navigate to /CodeXL/Output/Release/bin or /CodeXL/Output/Debug/bin
* Run CodeXLAnalyzer or CodeXLAnalyzer-x64
* use the -h command line argument to display help information
..
these are the instructions for running after building.
Also, there in the output file there is no CodeXL file
![screenshot from 2016-05-11 16 03 01](https://cloud.githubusercontent.com/assets/19306548/15181891/4145eb9c-1792-11e6-9eab-e2e1aa6bd57d.png)

**Comment by kpenujee** [comment]
Hi Katerina,
The README.txt that you attached refers to building only CodeXLAnalyzer component. Hence you are seeing only CodeXLAnalyzer in your output folder.

For complete build of CodeXL, you need to follow instructions given at:
https://github.com/GPUOpen-Tools/CodeXL/blob/master/BUILD.md

Thanks,
Kalyan P
