### ISSUE TITLE
CodeXL crashes at GPU profiling run

### ISSUE THREAD

**Issue by fesc2000** [GPUOpen-Tools/CodeXL#213]
When ending the application to be profiled CodeXL crashes. Cant even send crash report, so doing it here ..
[report.txt](https://github.com/GPUOpen-Tools/CodeXL/files/2289676/report.txt)

**Comment by nfogh** [comment]
I seem to have sort of the same issue. CodeXL crashes after profiling run, and cannot send the crash report. The stack trace is slightly different though: 

Email address (optional):
nfogh@bkultrasound.com

Operating System:
Win7-64

Call stack:
Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
osWin32CallStackReader::execute - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLOSWrappers.dll - 0x00ade1b0 - 0x00aa0000 - 0x00ade285
osCallsStackReader::getCurrentCallsStack - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLOSWrappers.dll - 0x00acd850 - 0x00aa0000 - 0x00acd8c1
appQtApplication::AppMemAllocFailureHandler - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x56bfa2e0 - 0x56bf0000 - 0x56bfa32a
std::_MP_Rem - N/A - N/A - C:\Windows\system32\MSVCP140.dll - 0x6637c0b0 - 0x66360000 - 0x6637c3df
GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x101d7780 - 0x101d0000 - 0x1020bdd5
N/A - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - N/A - 0x101d0000 - 0x101d65e3
N/A - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - N/A - 0x101d0000 - 0x101d4fbb
GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x101d7780 - 0x101d0000 - 0x101d9761
GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x101d7780 - 0x101d0000 - 0x101d90ad
GetParserUUID - N/A - N/A - C:\Program Files (x86)\CodeXL\RCPProfileDataParser.dll - 0x101d7780 - 0x101d0000 - 0x101d8928
GPUSessionTreeItemData::LoadAndGetOccupancyTable - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x0cdfc100 - 0x0cd50000 - 0x0cdfc244
gpSessionTreeNodeData::DeleteSessionFilesFromDisk - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x0cdfd230 - 0x0cd50000 - 0x0cdfe1b7
gpSessionTreeNodeData::DeleteSessionFilesFromDisk - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x0cdfd230 - 0x0cd50000 - 0x0cdfdbb6
SessionManager::CheckAndDeleteSessionFiles - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x0ce016f0 - 0x0cd50000 - 0x0ce02064
gpViewsCreator::LoadFileToView - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x0cd83990 - 0x0cd50000 - 0x0cd83a31
gpViewsCreator::GetWidgetForFilePath - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x0cd824a0 - 0x0cd50000 - 0x0cd82673
gpViewsCreator::createViewContent - N/A - N/A - c:\program files (x86)\codexl\CXLGpuProfiling.dll - 0x0cd815a0 - 0x0cd50000 - 0x0cd816b3
appMainAppWindow::createSingleView - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x56bf5c50 - 0x56bf0000 - 0x56bf5cd5
appApplicationStart::appMain - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x56bf16d0 - 0x56bf0000 - 0x56bf3898
appApplicationStart::appMain - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x56bf16d0 - 0x56bf0000 - 0x56bf360e
apEventsHandler::notifyObservers - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x00986c70 - 0x008e0000 - 0x00986d16
apEventsHandler::handleDebugEvent - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x00986ab0 - 0x008e0000 - 0x00986aeb
apEventsHandler::handlePendingDebugEvent - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApiClasses.dll - 0x00986940 - 0x008e0000 - 0x009869f5
QMetaCallEvent::placeMetaCall - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Core.dll - 0x67016030 - 0x66e90000 - 0x67016081
QApplicationPrivate::notify_helper - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Widgets.dll - 0x647023b0 - 0x646f0000 - 0x64702468
QApplication::notify - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Widgets.dll - 0x64700460 - 0x646f0000 - 0x647013f1
_RTDynamicCast - N/A - N/A - C:\Windows\system32\VCRUNTIME140.dll - 0x665642a0 - 0x66560000 - 0x665642b9
appQtApplication::notify - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x56bf9e20 - 0x56bf0000 - 0x56bf9e62
appQtApplication::notify - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x56bf9e20 - 0x56bf0000 - 0x56bf9fbf
QCoreApplication::notifyInternal - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Core.dll - 0x66ff2d60 - 0x66e90000 - 0x66ff2dd9
QGuiApplicationPrivate::processMouseEvent - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Gui.dll - 0x0fe96f70 - 0x0fe70000 - 0x0fe97856
_RTDynamicCast - N/A - N/A - C:\Windows\system32\VCRUNTIME140.dll - 0x665642a0 - 0x66560000 - 0x665642ee
_RTDynamicCast - N/A - N/A - C:\Windows\system32\VCRUNTIME140.dll - 0x665642a0 - 0x66560000 - 0x665642ee
_RTDynamicCast - N/A - N/A - C:\Windows\system32\VCRUNTIME140.dll - 0x665642a0 - 0x66560000 - 0x665642b9
_RTDynamicCast - N/A - N/A - C:\Windows\system32\VCRUNTIME140.dll - 0x665642a0 - 0x66560000 - 0x665642b9
_RTDynamicCast - N/A - N/A - C:\Windows\system32\VCRUNTIME140.dll - 0x665642a0 - 0x66560000 - 0x665642b9
appQtApplication::notify - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplication.dll - 0x56bf9e20 - 0x56bf0000 - 0x56bf9e62

System DLL Versions:
 - atioglxx.dll: 23.20.788.0
 - atio6axx.dll: 23.20.788.0
 - aticfx32.dll: 23.20.788.0
 - aticfx64.dll: 23.20.788.0
 - aticaldd.dll: 23.20.788.0
 - ig4icd64.dll: 8.15.10.2361
 - OpenCL.dll: 23.20.788.0

OpenGL Renderer:
 - Renderer Vendor: ATI Technologies Inc.
 - Renderer Name: AMD Radeon HD 7800 Series
 - Renderer Version: 4.5.13497 Compatibility Profile Context 23.20.788.0
 - Renderer Type: Installable client

Drivers versions:
 - CAL version: 1.4.1848
 - AMD Radeon Software version: 15.8

Device 1 (GPU):
 - Platform ID: 1
 - Device Type: GPU
 - Device Name: Pitcairn
 - Vendor: Advanced Micro Devices, Inc.

Device 2 (CPU):
 - Platform ID: 1
 - Device Type: CPU
 - Device Name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
 - Vendor: GenuineIntel

Platform 1:
 - Vendor: Advanced Micro Devices, Inc.
 - Name: AMD Accelerated Parallel Processing
 - Profile: FULL_PROFILE
 - Version: OpenCL 2.0 AMD-APP (2482.5)

**Comment by nfogh** [comment]
I have tried running the same program in CodeXL 2.4, and this version does not seem to have the problem.

**Comment by chesik-amd** [comment]
Would it be possible to share the CodeXL session files so we can investigate?

You can right click on the Session name in the CodeXL Explorer view and select "Open Containing Folder", the zip up the files in the directory that is shown.

**Comment by fesc2000** [comment]
Edit: In the meantime i am getting a "Memory Allocation Failure" Error when ending the application in a profiler run.

See attached stacktrace.

Attempting to reload the profiling data after a restart causes the crash (without memory allocation error) as in the original stacktrace.

[report_oom.txt](https://github.com/GPUOpen-Tools/CodeXL/files/2319780/report_oom.txt)

**Comment by chesik-amd** [comment]
Thanks for the additional information.

This looks to be the same issue reported here: https://github.com/GPUOpen-Tools/CodeXL/issues/179

As soon as a new version of CodeXL is released, this should be fixed.  There are a couple of workarounds mentioned in the link above.

**Comment by fesc2000** [comment]
Thanks, replacing ; by , in the .occupancy file makes it work.

**Comment by chesik-amd** [comment]
This should no longer be an issue in CodeXL 2.6
