### ISSUE TITLE
General question about debugging

### ISSUE THREAD

**Issue by SailingDreams** [GPUOpen-Tools/CodeXL#220]
I'm new to opencl debugging and would like to know if setting breakpoints in CPU kernel code is possible and does it cause your video to lock up? If so, do I need two video cards and target my debugging to the unused video card?

Ubuntu 16.04
AMD Ryzen 7 Threadripper
GPU SAPPHIRE PULSE Radeon RX Vega 56

**Comment by bpurnomo** [comment]
The AMD OpenCL driver stack does not support dispatching OpenCL kernels to CPU devices.

**Comment by SailingDreams** [comment]
Sorry for my miss type. I meant to ask " would like to know if setting breakpoints in **GPU** kernel code is possible and does it cause your video to lock up? If so, do I need two video cards and target my debugging to the unused video card?"

**Comment by bpurnomo** [comment]
Setting breakpoints in GPU kernel code in CodeXL do not require two video cards.  Note that GPU kernel debugging support is deprecated due to compiler change in the driver stack.
