### ISSUE TITLE
Visual Studio Code extension

### ISSUE THREAD

**Issue by MathiasMagnus** [GPUOpen-Tools/CodeXL#224]
If the Visual Studio Add-In is no longer supported (I loved it), do you perhaps have plans to create a Visual Studio Code extension to reach a greater audience?

**Comment by kpenujee** [comment]
Hi,
Visual studio extension is no longer be supported in CodeXL 2.6v. 
You need to use earlier (CodeXL 2.5v) version for the Visual Studio plug-in.

Thanks,
Kalyan P

**Comment by MathiasMagnus** [comment]
Was that supposed to be an answer to the question? I might not have made it clear, the question targeted Visual Studio **Code** ([link](https://code.visualstudio.com/)). It's a totally different IDE than _Big Brother_ Visual Studio. It's a lot more lightweight text editor with [supreme extensibility](https://code.visualstudio.com/docs/extensions/overview).

According to a recent (2018 February) ISO CPP survey (so no bias towards any OS or IDE) it is the [3rd most popular IDE for C++ development](https://isocpp.org/files/papers/CppDevSurvey-2018-02-summary.pdf) after VS and Vim. Extensions are mostly authored in TypeScript and the rendering is done via a WebView API, so there is a fair amount of freedom in the content that can be rendered.

My guess is that CodeXL is primarily used from C/C++ languages, the Microsoft extension for C++ development is pretty much full featured, it provides an API to set up IntelliSense which other extensions can hook into. CodeXL's own project format could serve as the basis of that hook, however compile_commands.json is also available to configure IntelliSense. Perhaps the most useful hook is the CMake Tools extension, which is capable of hooking into the IntelliSense API. You might want to check out [Rong Lu's presentation from CppCon 2018](https://youtu.be/JME1i3vCRR8) on the use of VS Code in relation to C/C++ development. (She also has an intro talk from 2017) It would be awesome to get a similar experience as was the case with Visual Studio.

**Comment by bpurnomo** [comment]
Hi,
While we don't have a plan to create a Visual Studio Code extension for CodeXL, we will welcome a pull request for such feature.
