### ISSUE TITLE
CodeXL for non-AMD GPU

### ISSUE THREAD

**Issue by ghost** [GPUOpen-Tools/CodeXL#226]
just have a curious question if CodeXL can work for non-AMD GPU, e.g. on embedded VideoCore IV GPU of the Raspberry Pi? If so, how?

**Comment by kpenujee** [comment]
Hi Peter,
CodeXL requires AMD GPU and AMD's display driver to be installed on the system on which it runs.

Thanks,
Kalyan P

**Comment by mcleary** [comment]
CodeXL will not officially work on non-AMD GPUs, however, as part of the LPGPU2 project, we have a prototype version that can do Application Timeline Trace profile on any device that supports OpenCL. You can take a look here: https://github.com/codeplaysoftware/LPGPU2-CodeXL. You can also see more about the LPGPU2 project here: http://lpgpu.org/wp/.

I am not sure about the OpenCL support for the VideoCore GPU, the only limitation would be a working OpenCL driver for this particular GPU. If you have that you could try our version.

**Comment by peter73421** [comment]
Does this LPGL2 support remote device ?  So CodeXL run on host and can
profile on remote target ?

**Comment by mcleary** [comment]
Yes, it does. A new release will be available soon, so if the current version doesn't work for you wait until the next release, please.

**Comment by peter73421** [comment]
when next release is expected to available?

**Comment by mcleary** [comment]
Probably in the middle of next week.

**Comment by peter73421** [comment]
do you have something available to try?

**Comment by mcleary** [comment]
Yes, please try our version 3.9.5.
https://github.com/codeplaysoftware/LPGPU2-CodeXL/releases/tag/v3.9.5

Our project is based in the older version of CodeXL (2.4). Although projects are compatible I recommend you to create a separate project for the LPGPU2 version.

If you find any issues or bugs please let us now in the issues page of our repo: https://github.com/codeplaysoftware/LPGPU2-CodeXL/issues

Also, let us know if you got it working for you.
