### ISSUE TITLE
Error opening CodeXL 2.6 on Windows

### ISSUE THREAD

**Issue by jwwalker** [GPUOpen-Tools/CodeXL#228]
Operating System:
Win7-64

Call stack:
Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
N/A - N/A - N/A - C:\Windows\system32\amdocl.dll - N/A - 0x0a380000 - 0x0a3d7bed
N/A - N/A - N/A - C:\Windows\system32\amdocl.dll - N/A - 0x0a380000 - 0x0a3c7ab5
N/A - N/A - N/A - C:\Windows\system32\amdocl.dll - N/A - 0x0a380000 - 0x0a3c8407
N/A - N/A - N/A - C:\Windows\system32\amdocl.dll - N/A - 0x0a380000 - 0x0a38bab3
N/A - N/A - N/A - C:\Windows\system32\amdocl.dll - N/A - 0x0a380000 - 0x0a38bb27
clGetSamplerInfo - N/A - N/A - C:\Windows\system32\amdocl.dll - 0x0a759990 - 0x0a380000 - 0x0a78d435
clGetSamplerInfo - N/A - N/A - C:\Windows\system32\amdocl.dll - 0x0a759990 - 0x0a380000 - 0x0a78e887
clGetSamplerInfo - N/A - N/A - C:\Windows\system32\amdocl.dll - 0x0a759990 - 0x0a380000 - 0x0a796799
clGetSamplerInfo - N/A - N/A - C:\Windows\system32\amdocl.dll - 0x0a759990 - 0x0a380000 - 0x0a796869
clGetSamplerInfo - N/A - N/A - C:\Windows\system32\amdocl.dll - 0x0a759990 - 0x0a380000 - 0x0a785f55
clIcdGetPlatformIDsKHR - N/A - N/A - C:\Windows\system32\amdocl.dll - 0x0a74f730 - 0x0a380000 - 0x0a74f740
clRetainMemObject - N/A - N/A - C:\Windows\system32\OpenCL.dll - 0x0f811276 - 0x0f810000 - 0x0f8115c1
afSystemInformationCommand::CollectOpenCLDevicesInformation - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplicationFramework.dll - 0x0f596960 - 0x0f590000 - 0x0f5969c0
afSystemInformationCommand::getSystemInformationDataAsString - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplicationFramework.dll - 0x0f59c570 - 0x0f590000 - 0x0f59c7f0
afSystemInformationCommand::operator= - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplicationFramework.dll - 0x0f5917d0 - 0x0f590000 - 0x0f591a3b
osThread::threadEntryPoint - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLOSWrappers.dll - 0x0fd6a800 - 0x0fd30000 - 0x0fd6a8cd
crt_at_quick_exit - N/A - N/A - C:\Windows\system32\ucrtbase.DLL - 0x625161e0 - 0x62490000 - 0x625162e3
BaseThreadInitThunk - N/A - N/A - C:\Windows\syswow64\kernel32.dll - 0x7692342b - 0x76910000 - 0x7692343c
RtlInitializeExceptionChain - N/A - N/A - C:\Windows\SysWOW64\ntdll.dll - 0x772e97cf - 0x772b0000 - 0x772e9831
N/A - N/A - N/A - N/A - N/A - N/A - N/A

System Information gathering timed out after 10s

**Comment by mcleary** [comment]
What is the output of running `clinfo` in your system?
The function that is crashing is responsible for collecting OpenCL information from your system. If `clinfo` is fine then it should really be a problem with CodeXL.

**Comment by jwwalker** [comment]
When I try to run `clinfo`, it crashes ("clinfo.exe has stopped working").

I just want to use CodeXL for OpenGL, not OpenCL.  Is there a way to make CodeXL not try to mess with OpenCL?
