### ISSUE TITLE
Proceed after building

### ISSUE THREAD

**Issue by kpontzolkova** [GPUOpen-Tools/CodeXL#23]
Hello everyone,

First of all, thank you for our time.

It's been days that i have been trying to compile CodeXL.
Today i finally suceeded.. I followed the instructions,

Executed ./backend_build.sh skip-hsaprofiler
And then 
./buildCodeXLFullLinuxProjects x86
It told me that it succeeded. How nice
*** SUCCESS ***
But i can't find the executable for the program:

~/Downloads/git/CodeXL/Output_x86/release/bin$ ls
amdcodexlicon.desktop       HTML     libCXLAPIClasses.a     libstdc++.a          spies
CXLSystemInformationHelper  Images   libCXLBaseTools.a      libstdc++.so         webhelp
Data                        include  libCXLOSAPIWrappers.a  libstdc++.so.6
examples                    Legal    libCXLOSWrappers.a     libstdc++.so.6.0.20
kpontzolkova@peach:~/Downloads/git/CodeXL/Output_x86/release/bin$ ls
amdcodexlicon.desktop       HTML     libCXLAPIClasses.a     libstdc++.a          spies
CXLSystemInformationHelper  Images   libCXLBaseTools.a      libstdc++.so         webhelp
Data                        include  libCXLOSAPIWrappers.a  libstdc++.so.6
examples                    Legal    libCXLOSWrappers.a     libstdc++.so.6.0.20

What i did wrong?

Regards,
Katerina P

**Comment by ilangal-amd** [comment]
Hi Katerina, 

Thanks for the report, 
Please try to build without the “x86” switch, as the Linux runtime is in x86_64 which is the default build switch. 
The “x86” is used to build a specific project within CodeXL that should support some 32bit apps. 

Ilan.

**Comment by kpontzolkova** [comment]
Hello Ilan,
Is it possible to build CodeXL with the graphics?
Because all i can get is command version, and i thought it was open source. Maybe when building onm windows you get the ful version? Thank you for your patience

Regards,
Katerina P

**Comment by kpontzolkova** [comment]
Also when building the hsa it stops st hsa_ext_debugger.h, and i cant find it anyware

**Comment by kpontzolkova** [comment]
I;m trying to install rocm
sudo apt-get install rocm

and it can't fing it

**Comment by kpontzolkova** [comment]
SOLVED.
