### ISSUE TITLE
Profiling with performance counters crashes program

### ISSUE THREAD

**Issue by nfogh** [GPUOpen-Tools/CodeXL#231]
I am trying to profile a very simple program (HelloWorld from the amd app SDK 3.0 samples)

When trying to get GPU performance counters, the program (Not CodeXL) will crash the profiled program ("HelloWorld.exe has stopped working"), and CodeXL will return with "Unable to gather profile data...".

Debugging catches the error at the call to clEnqueueNDRangeKernel: Unhandled exception at 0x09ED79DE (amdocl12cl.dll) in HelloWorld.exe: 0xC0000005: Access violation writing location 0x0AB40000.

Application Timeline Trace works OK.

CodeXL: 2.6
Platform: Windows 10 64-bit
CPU: Intel Core i7-6700
GPU: AMD Radeon HD7800 series
Radeon SW: 18.9.3 Adrenalin

OpenCL:
Profile: FULL_PROFILE
Version: OpenCL 2.1 AMD-APP (2671.3)
Name: AMD Accelerated Parallel Processing
Vendor: Advanced Micro Devices, Inc.
Extensions: cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices

**Comment by rNoz** [comment]
I get the same error in Windows with Adrenaline 18.7.1. It supports both CPU and GPU in Timeline, but it always complains with GPU Counters. I tried disabling almost all the options and executing CodeXL also as admin.

Any clue?

PS. In Linux currently it is impossible to get the AMD (catalyst) drivers working (tried for days without luck).
