### ISSUE TITLE
CodeXL crashes when opening profiling trace

### ISSUE THREAD

**Issue by sudden6** [GPUOpen-Tools/CodeXL#236]
I guess it's the same problem as in: https://github.com/GPUOpen-Tools/CodeXL/issues/179

The `.occupancy` files column headers are written with `,` instead of `;`. I guess this is due to my locale being set to `de_AT`.

CodeXL Version is `2.6.302`

**Comment by chesik-amd** [comment]
This issue should have been fixed in the 2.6 release.  If you hand-edit the .occupancy file to use a comma instead of a semi-colon, does the trace load correctly?

**Comment by sudden6** [comment]
Yes.

Also setting my locale to `en_US` for all entries in `/etc/default/locale` fixed the problem for generating traces.

**Comment by chesik-amd** [comment]
OK, thanks for this info.  We'll take a look.
