### ISSUE TITLE
issues in teapot

### ISSUE THREAD

**Issue by sidtharthpalanisami** [GPUOpen-Tools/CodeXL#237]
Operating System:
Win10-64

Call stack:
Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
N/A - N/A - N/A - N/A - N/A - N/A - 0xffffffff
clGetPipeInfo - N/A - N/A - C:\WINDOWS\System32\DriverStore\FileRepository\c0338885.inf_amd64_648d9ae54bb276d8\B338884\amdocl.dll - 0x56de17c0 - 0x56b70000 - 0x56e0f935
clGetPipeInfo - N/A - N/A - C:\WINDOWS\System32\DriverStore\FileRepository\c0338885.inf_amd64_648d9ae54bb276d8\B338884\amdocl.dll - 0x56de17c0 - 0x56b70000 - 0x56e0bfe0
clGetPipeInfo - N/A - N/A - C:\WINDOWS\System32\DriverStore\FileRepository\c0338885.inf_amd64_648d9ae54bb276d8\B338884\amdocl.dll - 0x56de17c0 - 0x56b70000 - 0x56df1ef2
clGetPipeInfo - N/A - N/A - C:\WINDOWS\System32\DriverStore\FileRepository\c0338885.inf_amd64_648d9ae54bb276d8\B338884\amdocl.dll - 0x56de17c0 - 0x56b70000 - 0x56df203a
clGetPipeInfo - N/A - N/A - C:\WINDOWS\System32\DriverStore\FileRepository\c0338885.inf_amd64_648d9ae54bb276d8\B338884\amdocl.dll - 0x56de17c0 - 0x56b70000 - 0x56de1993
clCreateContext - c:\jenkins\workspace\codexl-gerrit-2.6\codexl\components\gpudebugging\amdtopenclserver\src\csopenclwrappers.cpp - 303 - c:\program files (x86)\codexl\spies\OpenCL.dll - 0x54b28110 - 0x54b00000 - 0x54b281e8
AMDTTeapotOCLSmokeSystem::initOpenCLResources - c:\jenkins\workspace\codexl-gerrit-2.6\codexl\examples\amdtteapot\amdtteapotlib\src\amdtteapotoclsmokesystem.cpp - 1168 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x00b9e1e0 - 0x00b90000 - 0x00b9e545
AMDTTeapotOCLSmokeSystem::draw - c:\jenkins\workspace\codexl-gerrit-2.6\codexl\examples\amdtteapot\amdtteapotlib\src\amdtteapotoclsmokesystem.cpp - 1661 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x00b9eee0 - 0x00b90000 - 0x00b9f0ae
AMDTTeapotOGLCanvas::paintWindow - c:\jenkins\workspace\codexl-gerrit-2.6\codexl\examples\amdtteapot\amdtteapotlib\src\amdtteapotoglcanvas.cpp - 434 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x00b96be0 - 0x00b90000 - 0x00b96c97
AMDTTeapotOGLCanvas::onPaint - c:\jenkins\workspace\codexl-gerrit-2.6\codexl\examples\amdtteapot\amdtteapotlib\src\amdtteapotoglcanvas.cpp - 160 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x00b965c0 - 0x00b90000 - 0x00b965ce
MainWin::onPaint - c:\jenkins\workspace\codexl-gerrit-2.6\codexl\examples\amdtteapot\amdtteapot\src\amdtmainwin.cpp - 146 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x00b91690 - 0x00b90000 - 0x00b916a8
WndProc - c:\jenkins\workspace\codexl-gerrit-2.6\codexl\examples\amdtteapot\amdtteapot\amdtteapot.cpp - 508 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x00b933b0 - 0x00b90000 - 0x00b9399f
AddClipboardFormatListener - N/A - N/A - C:\WINDOWS\System32\USER32.dll - 0x75cf6310 - 0x75cb0000 - 0x75cf635a
CallWindowProcW - N/A - N/A - C:\WINDOWS\System32\USER32.dll - 0x75ce6770 - 0x75cb0000 - 0x75ce729b
CallWindowProcW - N/A - N/A - C:\WINDOWS\System32\USER32.dll - 0x75ce6770 - 0x75cb0000 - 0x75ce6e39
IsRectEmpty - N/A - N/A - C:\WINDOWS\System32\USER32.dll - 0x75cf35e0 - 0x75cb0000 - 0x75cf37ee
KiUserCallbackDispatcher - N/A - N/A - C:\WINDOWS\SYSTEM32\ntdll.dll - 0x774428a0 - 0x773d0000 - 0x774428ec
DispatchMessageW - N/A - N/A - C:\WINDOWS\System32\USER32.dll - 0x75ce61a0 - 0x75cb0000 - 0x75ce61af
wWinMain - c:\jenkins\workspace\codexl-gerrit-2.6\codexl\examples\amdtteapot\amdtteapot\amdtteapot.cpp - 325 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x00b92b00 - 0x00b90000 - 0x00b9327a
__scrt_common_main_seh - f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl - 264 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x00ba65c6 - 0x00b90000 - 0x00ba66c2
BaseThreadInitThunk - N/A - N/A - C:\WINDOWS\System32\KERNEL32.DLL - 0x76bf0160 - 0x76bd0000 - 0x76bf0178
RtlGetAppContainerNamedObjectPath - N/A - N/A - C:\WINDOWS\SYSTEM32\ntdll.dll - 0x77436540 - 0x773d0000 - 0x7743662c
N/A - N/A - N/A - N/A - N/A - N/A - N/A

System DLL Versions:
 - aticfx32.dll: 8.17.10.1653
 - aticfx64.dll: 8.17.10.1653
 - OpenCL.dll: 25.20.15017.1010

OpenGL Renderer:
 - Renderer Vendor: Intel
 - Renderer Name: Intel(R) UHD Graphics 620
 - Renderer Version: 4.5.0 - Build 23.20.16.4973
 - Renderer Type: Installable client

Device 1 (GPU):
 - Platform ID: 1
 - Device Type: GPU
 - Device Name: Intel(R) UHD Graphics 620
 - Vendor: Intel(R) Corporation

Device 2 (CPU):
 - Platform ID: 1
 - Device Type: CPU
 - Device Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
 - Vendor: Intel(R) Corporation

Device 3 (GPU):
 - Platform ID: 2
 - Device Type: GPU
 - Device Name: Iceland
 - Vendor: Advanced Micro Devices, Inc.

Platform 1:
 - Vendor: Intel(R) Corporation
 - Name: Intel(R) OpenCL
 - Profile: FULL_PROFILE
 - Version: OpenCL 2.1 

Platform 2:
 - Vendor: Advanced Micro Devices, Inc.
 - Name: AMD Accelerated Parallel Processing
 - Profile: FULL_PROFILE
 - Version: OpenCL 2.1 AMD-APP (2766.5)

Additional Information:
- OpenCL Engine loaded:Yes
- OpenGL Engine loaded:Yes
- Kernel Debugging Entered:No

**Comment by adevaykin** [comment]
+1
Cannot even start application after first installation

Operating System:
Win10-64

Call stack:
Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
clGetKernelSubGroupInfoKHR - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\igdrclneo32.dll - 0x10a2adc0 - 0x10a10000 - 0x10a36203
N/A - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\igdrclneo32.dll - N/A - 0x10a10000 - 0x10a2394a
clGetKernelSubGroupInfoKHR - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\igdrclneo32.dll - 0x10a2adc0 - 0x10a10000 - 0x10a6c725
clGetPlatformIDs - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\igdrclneo32.dll - 0x10a24400 - 0x10a10000 - 0x10a24470
clEnqueueTask - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\igdrclneo32.dll - 0x10a2acc0 - 0x10a10000 - 0x10a2ad9e
clUnloadPlatformCompiler - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\IntelOpenCL32.dll - 0x0eff6c12 - 0x0eff0000 - 0x0f029695
clUnloadPlatformCompiler - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\IntelOpenCL32.dll - 0x0eff6c12 - 0x0eff0000 - 0x0effc9c2
N/A - N/A - N/A - C:\Windows\system32\OpenCL.dll - N/A - 0x0f360000 - 0x0f361313
clWaitForEvents - N/A - N/A - C:\Windows\system32\OpenCL.dll - 0x0f363e60 - 0x0f360000 - 0x0f363f97
RtlRunOnceExecuteOnce - N/A - N/A - C:\Windows\SYSTEM32\ntdll.dll - 0x77ec6560 - 0x77e70000 - 0x77ec65da
InitOnceExecuteOnce - N/A - N/A - C:\Windows\System32\KERNELBASE.dll - 0x773362c0 - 0x77230000 - 0x773362d6
clWaitForEvents - N/A - N/A - C:\Windows\system32\OpenCL.dll - 0x0f363e60 - 0x0f360000 - 0x0f364023
afSystemInformationCommand::CollectOpenCLDevicesInformation - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplicationFramework.dll - 0x00be6af0 - 0x00be0000 - 0x00be6b3f
afSystemInformationCommand::CollectOpenCLDevicesInformation - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplicationFramework.dll - 0x00be6960 - 0x00be0000 - 0x00be69c0
afSystemInformationCommand::getSystemInformationDataAsString - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplicationFramework.dll - 0x00bec570 - 0x00be0000 - 0x00bec7f0
afSystemInformationCommand::operator= - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLApplicationFramework.dll - 0x00be17d0 - 0x00be0000 - 0x00be1a3b
osThread::threadEntryPoint - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLOSWrappers.dll - 0x0f21a800 - 0x0f1e0000 - 0x0f21a8cd
o____lc_collate_cp_func - N/A - N/A - C:\Windows\System32\ucrtbase.dll - 0x761de830 - 0x761a0000 - 0x761de87e
BaseThreadInitThunk - N/A - N/A - C:\Windows\System32\KERNEL32.DLL - 0x748a8460 - 0x74890000 - 0x748a8483
RtlAreBitsSet - N/A - N/A - C:\Windows\SYSTEM32\ntdll.dll - 0x77ed4140 - 0x77e70000 - 0x77ed41c7
N/A - N/A - N/A - N/A - N/A - N/A - N/A

System Information gathering timed out after 10s
