### ISSUE TITLE
GUI: fix dialog contrast for dark color schemes

### ISSUE THREAD

**Issue by EvilMav** [GPUOpen-Tools/CodeXL#241]
CodeXL seems to override background colors e.g. for the "Create a new project" dialog, while keeping system-color fonts. This leads to unreadable dialogs for dark themes like KDE's breeze dark on linux:

![Screenshot_20190326_012206](https://user-images.githubusercontent.com/6803717/54962581-adf02b00-4f65-11e9-88a6-37155ad48de2.png)

**Comment by Boris-Barboris** [comment]
The simplest workaround under Plasma is just to use custom home:
mkdir ~/.codexlhome
XDG_CONFIG_HOME=$HOME/.codexlhome ./CodeXL
