### ISSUE TITLE
how to transplant the existed opencl project based on VS2015 to codeXL

### ISSUE THREAD

**Issue by GeneralLeeLi** [GPUOpen-Tools/CodeXL#243]
I tried to move the existed VS2015 project to codeXL, I set the executable path, working directory and source files directories. But it didn't working when doing ether debug or profile mode. It will pop up "Unable to gather profile data. This error can occur for one of several reasons" like the following. 
. The active project is not an OpenCL program.
. The active project does not compile or run properly(try running it manually).
. You do not have write access the profile output directory.
. ...

Could anyone help me? 

Thanks for advance.

**Comment by mcleary** [comment]
This usually happens when CodeXL is not able to intercept OpenCL function calls.
* Can you run the application manually (in the command line)?
* Where is your OpenCL.dll located?

**Comment by IamGeneralLee** [comment]
> This usually happens when CodeXL is not able to intercept OpenCL function calls.
> 
> * Can you run the application manually (in the command line)?
> * Where is your OpenCL.dll located?

Hello Mnleary,
Thank you very much for your reply.

1. I can manually run the application ether via directly clicking the executive file or running it from command line.
2. Opencl.dll is used with Loadlibrary() function in my project.

BTW, even if I loaded the Teapot Sample in codeXL, it will also occur issues above  when do GPU profile mode. But it was OK when did Debug mode.

**Comment by mcleary** [comment]
> > This usually happens when CodeXL is not able to intercept OpenCL function calls.
> > 
> > * Can you run the application manually (in the command line)?
> > * Where is your OpenCL.dll located?
> 
> Hello Mnleary,
> Thank you very much for your reply.
> 
> 1. I can manually run the application ether via directly clicking the executive file or running it from command line.
> 2. Opencl.dll is used with Loadlibrary() function in my project.

This is the issue. CodeXL won't be able to intercept the OpenCL function calls because it expects the DLL to be loaded before the `main` function of your program executes. CodeXL uses the windows `DLLMain` mechanism to set up hooks for OpenCL functions since you are explicitly loading the library, there is no way for CodeXL to intercept the calls and that's why you are getting a message saying your application *is not a valid OpenCL application*.

The only solution to this is to link against OpenCL.lib and stop using `LoadLibrary`.

> 
> BTW, even if I loaded the Teapot Sample in codeXL, it will also occur issues above when do GPU profile mode. But it was OK when did Debug mode.

**Comment by IamGeneralLee** [comment]
> > BTW, even if I loaded the Teapot Sample in codeXL, it will also occur issues above when do GPU profile mode. But it was OK when did Debug mode.

Thank you very much. But why the sample from AMD failed to do Profile mode while Debug mode can work with the same settings.

Are there any different settings between Debug mode and Profile mode?

**Comment by mcleary** [comment]
Unfortunately, I don't know the answer to that. There should be no difference on the CodeXL side. For some reason, CodeXL is not able to install hooks in your Teapot profiling mode.

**Comment by mcleary** [comment]
Thinking about this, maybe there is a way to keep using `LoadLibrary` for OpenCL functions.

CodeXL places a *fake* OpenCL DLL between the application the real `OpenCL.dll`. If you use `LoadLibrary` to load the symbols from the *fake* DLL, everything should theoretically work. It is just a guess, but if you want, you could give it a shot.

**Comment by IamGeneralLee** [comment]
> Thinking about this, maybe there is a way to keep using `LoadLibrary` for OpenCL functions.
> 
> CodeXL places a _fake_ OpenCL DLL between the application the real `OpenCL.dll`. If you use `LoadLibrary` to load the symbols from the _fake_ DLL, everything should theoretically work. It is just a guess, but if you want, you could give it a shot.

Thanks for helping me discuss this issue.

In my project, it invoked OpenCL DLL via LoadLibrary(TEXT("OpenCL.dll")). As per your suggestion, It can invoke the fake OpenCL DLL instead of the real OpenCL DLL in my project. Am I correct?
The question is what the symbols of fake OpenCL DLL is, where does it locate?

A thousand of thanks.,

**Comment by mcleary** [comment]
That is correct, the symbols are the same, they have to be in order for the injection to work.

If you have installed CodeXL using the installer, it should be located in `C:\Program Files (x86)\CodeXL\spies64` for the 64bit version. 

Again, I am not sure if this will work, but it should.

**Comment by IamGeneralLee** [comment]
Sorry for late replay. Thanks so much. I tried your solution, but still a little confused.

 In my VS project, Firstly it uses WIX to build an installation file at work computer. Then, I install the software with the installation file at AMD test unit (Because the software is used to test AMD GPU).  So how could I use CodeXL to debug my project?  Or was it reasonable to move my project to the test unit on which the software installed.?

**Comment by IamGeneralLee** [comment]
I have another project which is similar with the upper project. A little difference is opencl.dll maybe implicit invocation in this project (see glut32.dl under the folder). Following shows this project screen shot. I set the executable path, working directory and source files directories in CodeXL to import the project. It works with Debug mode, the application can be started in CodeXL. What made me depressed is it still failed with Profile Mode.  I prefer the Profile Mode to analylize my kernel at AMD GPU.
![image](https://user-images.githubusercontent.com/46989828/57599799-79264a80-758a-11e9-97bb-89ca0eff5374.png)

Thank you

**Comment by IamGeneralLee** [comment]
> That is correct, the symbols are the same, they have to be in order for the injection to work.
> 
> If you have installed CodeXL using the installer, it should be located in `C:\Program Files (x86)\CodeXL\spies64` for the 64bit version.
> 
> Again, I am not sure if this will work, but it should.

Sorry for late replay. Thanks so much. I tried your solution, but still a little confused.

In my VS project, Firstly it uses WIX to build an installation file at work computer. Then, I install the software with the installation file at AMD test unit (Because the software is used to test AMD GPU). So how could I use CodeXL to debug my project? Or was it reasonable to move my project to the test unit on which the software installed.?

**Comment by IamGeneralLee** [comment]
> > That is correct, the symbols are the same, they have to be in order for the injection to work.
> > If you have installed CodeXL using the installer, it should be located in `C:\Program Files (x86)\CodeXL\spies64` for the 64bit version.
> > Again, I am not sure if this will work, but it should.
> 
> Sorry for late replay. Thanks so much. I tried your solution, but still a little confused.
> 
> In my VS project, Firstly it uses WIX to build an installation file at work computer. Then, I install the software with the installation file at AMD test unit (Because the software is used to test AMD GPU). So how could I use CodeXL to debug my project? Or was it reasonable to move my project to the test unit on which the software installed.?

I have another project which is similar with the upper project. A little difference is opencl.dll maybe implicit invocation in this project (see glut32.dl under the folder). Following shows this project screen shot. I set the executable path, working directory and source files directories in CodeXL to import the project. It works with Debug mode, the application can be started in CodeXL. What made me depressed is it still failed with Profile Mode. I prefer the Profile Mode to analylize my kernel at AMD GPU.
![image](https://user-images.githubusercontent.com/46989828/57600249-e25a8d80-758b-11e9-9f91-7656b4eb4cbf.png)

**Comment by IamGeneralLee** [comment]
> > > That is correct, the symbols are the same, they have to be in order for the injection to work.
> > > If you have installed CodeXL using the installer, it should be located in `C:\Program Files (x86)\CodeXL\spies64` for the 64bit version.
> > > Again, I am not sure if this will work, but it should.
> > 
> > 
> > Sorry for late replay. Thanks so much. I tried your solution, but still a little confused.
> > In my VS project, Firstly it uses WIX to build an installation file at work computer. Then, I install the software with the installation file at AMD test unit (Because the software is used to test AMD GPU). So how could I use CodeXL to debug my project? Or was it reasonable to move my project to the test unit on which the software installed.?
> 
> I have another project which is similar with the upper project. A little difference is opencl.dll maybe implicit invocation in this project (see glut32.dl under the folder). Following shows this project screen shot. I set the executable path, working directory and source files directories in CodeXL to import the project. It works with Debug mode, the application can be started in CodeXL. What made me depressed is it still failed with Profile Mode. I prefer the Profile Mode to analylize my kernel at AMD GPU.
> ![image](https://user-images.githubusercontent.com/46989828/57600249-e25a8d80-758b-11e9-9f91-7656b4eb4cbf.png)

This is the error message with Profile Mode
![image](https://user-images.githubusercontent.com/46989828/57601137-467e5100-758e-11e9-9635-7c3d3fb474a2.png)

**Comment by mcleary** [comment]
> > That is correct, the symbols are the same, they have to be in order for the injection to work.
> > If you have installed CodeXL using the installer, it should be located in `C:\Program Files (x86)\CodeXL\spies64` for the 64bit version.
> > Again, I am not sure if this will work, but it should.
> 
> Sorry for late replay. Thanks so much. I tried your solution, but still a little confused.
> 
> In my VS project, Firstly it uses WIX to build an installation file at work computer. Then, I install the software with the installation file at AMD test unit (Because the software is used to test AMD GPU). So how could I use CodeXL to debug my project? Or was it reasonable to move my project to the test unit on which the software installed.?

In my opinion, there is no need to generate the installer using WIX, that's for distribution only. Since you are building CodeXL from source, all you have to do is copy the contents of the build folder into the machine you want to run your project. In that machine, you run the CodeXL Remote Agent (`CodeXLRemoteAgent.exe`). This will open a command line window and it will give you an IP Address and a port to connect.

In your development machine, you launch `CodeXL.exe` and create a new project using `Remote Host` in the `General` tab. Then you type the IP of the machine and click connect. Fill in the information required to launch the application in the remote machine.

**Comment by mcleary** [comment]
> > > > That is correct, the symbols are the same, they have to be in order for the injection to work.
> > > > If you have installed CodeXL using the installer, it should be located in `C:\Program Files (x86)\CodeXL\spies64` for the 64bit version.
> > > > Again, I am not sure if this will work, but it should.
> > > 
> > > 
> > > Sorry for late replay. Thanks so much. I tried your solution, but still a little confused.
> > > In my VS project, Firstly it uses WIX to build an installation file at work computer. Then, I install the software with the installation file at AMD test unit (Because the software is used to test AMD GPU). So how could I use CodeXL to debug my project? Or was it reasonable to move my project to the test unit on which the software installed.?
> > 
> > 
> > I have another project which is similar with the upper project. A little difference is opencl.dll maybe implicit invocation in this project (see glut32.dl under the folder). Following shows this project screen shot. I set the executable path, working directory and source files directories in CodeXL to import the project. It works with Debug mode, the application can be started in CodeXL. What made me depressed is it still failed with Profile Mode. I prefer the Profile Mode to analylize my kernel at AMD GPU.
> > ![image](https://user-images.githubusercontent.com/46989828/57600249-e25a8d80-758b-11e9-9f91-7656b4eb4cbf.png)
> 
> This is the error message with Profile Mode
> ![image](https://user-images.githubusercontent.com/46989828/57601137-467e5100-758e-11e9-9635-7c3d3fb474a2.png)

For this project, I think you are a little confused on which libraries you're depending upon. `glut32.dll` has nothing to do with `OpenCL.dll`. A couple of things to bare in mind when using CodeXL:

* Make sure you understand the different modes of operation
    * Profiling OpenCL and OpenGL are two different things in CodeXL
    * OpenCL Profiling -> `Profile`/`Application Timeline Tracing`
    * Debbuging is not the same as Profiling
        * Do want to how long each command is taking or do you want to find an issue in the code logic?

**Comment by IamGeneralLee** [comment]
> > > That is correct, the symbols are the same, they have to be in order for the injection to work.
> > > If you have installed CodeXL using the installer, it should be located in `C:\Program Files (x86)\CodeXL\spies64` for the 64bit version.
> > > Again, I am not sure if this will work, but it should.
> > 
> > 
> > Sorry for late replay. Thanks so much. I tried your solution, but still a little confused.
> > In my VS project, Firstly it uses WIX to build an installation file at work computer. Then, I install the software with the installation file at AMD test unit (Because the software is used to test AMD GPU). So how could I use CodeXL to debug my project? Or was it reasonable to move my project to the test unit on which the software installed.?
> 
> In my opinion, there is no need to generate the installer using WIX, that's for distribution only. Since you are building CodeXL from source, all you have to do is copy the contents of the build folder into the machine you want to run your project. In that machine, you run the CodeXL Remote Agent (`CodeXLRemoteAgent.exe`). This will open a command line window and it will give you an IP Address and a port to connect.
> 
> In your development machine, you launch `CodeXL.exe` and create a new project using `Remote Host` in the `General` tab. Then you type the IP of the machine and click connect. Fill in the information required to launch the application in the remote machine and you should be good to go. Select the `Application Timeline Trace` mode from the `Profile` menu and click in the `GPU Profile` button in the CodeXL interface. This will send a command to the remote agent to launch your application in the target machine.
> 
> If everything is fine, you should see the application running in the target machine. When the application finishes (or you close it), the profiling data will be displayed by CodeXL in your development machine.

Thank you. I did it according to your instruction.  Something went wrong. Following are my steps.
1. Connected the two units with internet cable. Unit 1 is for testing GPU, Unit 2 is for code development.
2. Copied the content of the build folder to Unit 1, turned off the firewall, and launched "CodeXLRemoteAgent.exe" with administration privilege. A command window appeared as picture 1 shown.
![image](https://user-images.githubusercontent.com/46989828/57766085-4ff7ec80-7739-11e9-9fb9-7f10148d8cd5.png)

3. Launched "CodeXL.exe" at Unit 2, and typed the IP address as shown in picture 1. Filled the executable path and source files directorys where it located in Unit 1. 
4. When I hit "Test Connection", it seems the connection is OK as shown in picture 2. Then I tried to click "OK" button, something then went wrong as Picture 3 shown. Actually, the executable file is working when it is started at Unit 1. I was wondering if the connection is OK?  I found it will display "Disconnenction ... " in command window at Unit 1 every time I hit "Test Connection" or "OK".
![image](https://user-images.githubusercontent.com/46989828/57766496-01971d80-773a-11e9-819b-6c8937309b21.png)

![image](https://user-images.githubusercontent.com/46989828/57766645-4f138a80-773a-11e9-8ec8-17c73f721a9a.png)

**Comment by IamGeneralLee** [comment]
> > > > > That is correct, the symbols are the same, they have to be in order for the injection to work.
> > > > > If you have installed CodeXL using the installer, it should be located in `C:\Program Files (x86)\CodeXL\spies64` for the 64bit version.
> > > > > Again, I am not sure if this will work, but it should.
> > > > 
> > > > 
> > > > Sorry for late replay. Thanks so much. I tried your solution, but still a little confused.
> > > > In my VS project, Firstly it uses WIX to build an installation file at work computer. Then, I install the software with the installation file at AMD test unit (Because the software is used to test AMD GPU). So how could I use CodeXL to debug my project? Or was it reasonable to move my project to the test unit on which the software installed.?
> > > 
> > > 
> > > I have another project which is similar with the upper project. A little difference is opencl.dll maybe implicit invocation in this project (see glut32.dl under the folder). Following shows this project screen shot. I set the executable path, working directory and source files directories in CodeXL to import the project. It works with Debug mode, the application can be started in CodeXL. What made me depressed is it still failed with Profile Mode. I prefer the Profile Mode to analylize my kernel at AMD GPU.
> > > ![image](https://user-images.githubusercontent.com/46989828/57600249-e25a8d80-758b-11e9-9f91-7656b4eb4cbf.png)
> > 
> > 
> > This is the error message with Profile Mode
> > ![image](https://user-images.githubusercontent.com/46989828/57601137-467e5100-758e-11e9-9635-7c3d3fb474a2.png)
> 
> For this project, I think you are a little confused on which libraries you're depending upon. `glut32.dll` has nothing to do with `OpenCL.dll`. A couple of things to bare in mind when using CodeXL:
> 
> * Make sure you understand the different modes of operation
>   
>   * Profiling OpenCL and OpenGL are two different things in CodeXL
>   * OpenCL Profiling -> `Profile`/`Application Timeline Tracing`
>   * Debbuging is not the same as Profiling
>     
>     * Do want to how long each command is taking or do you want to find an issue in the code logic?

Hello, this tool is to stress the GPU (just like FurMark), including AMD GPUs. Currently, I found it cannot stress at AMD Vega GPU at all. I suspected my kernel algorithm (Ray tracing) is weak at Vega GPU. So I need CodeXL to analyze my kernel and find the bottleneck.  I am stuck at optimizing the kernel for several months. I knew it's a huge task. So I have tried many solutions, but it still not working. Using CodeXL is now the only way I can focus on.
Do you have any suggestions about my project?

**Comment by mcleary** [comment]
> > > > That is correct, the symbols are the same, they have to be in order for the injection to work.
> > > > If you have installed CodeXL using the installer, it should be located in `C:\Program Files (x86)\CodeXL\spies64` for the 64bit version.
> > > > Again, I am not sure if this will work, but it should.
> > > 
> > > 
> > > Sorry for late replay. Thanks so much. I tried your solution, but still a little confused.
> > > In my VS project, Firstly it uses WIX to build an installation file at work computer. Then, I install the software with the installation file at AMD test unit (Because the software is used to test AMD GPU). So how could I use CodeXL to debug my project? Or was it reasonable to move my project to the test unit on which the software installed.?
> > 
> > 
> > In my opinion, there is no need to generate the installer using WIX, that's for distribution only. Since you are building CodeXL from source, all you have to do is copy the contents of the build folder into the machine you want to run your project. In that machine, you run the CodeXL Remote Agent (`CodeXLRemoteAgent.exe`). This will open a command line window and it will give you an IP Address and a port to connect.
> > In your development machine, you launch `CodeXL.exe` and create a new project using `Remote Host` in the `General` tab. Then you type the IP of the machine and click connect. Fill in the information required to launch the application in the remote machine and you should be good to go. Select the `Application Timeline Trace` mode from the `Profile` menu and click in the `GPU Profile` button in the CodeXL interface. This will send a command to the remote agent to launch your application in the target machine.
> > If everything is fine, you should see the application running in the target machine. When the application finishes (or you close it), the profiling data will be displayed by CodeXL in your development machine.
> 
> Thank you. I did it according to your instruction. Something went wrong. Following are my steps.
> 
> 1. Connected the two units with internet cable. Unit 1 is for testing GPU, Unit 2 is for code development.
> 2. Copied the content of the build folder to Unit 1, turned off the firewall, and launched "CodeXLRemoteAgent.exe" with administration privilege. A command window appeared as picture 1 shown.
>    ![image](https://user-images.githubusercontent.com/46989828/57766085-4ff7ec80-7739-11e9-9fb9-7f10148d8cd5.png)
> 3. Launched "CodeXL.exe" at Unit 2, and typed the IP address as shown in picture 1. Filled the executable path and source files directorys where it located in Unit 1.
> 4. When I hit "Test Connection", it seems the connection is OK as shown in picture 2. Then I tried to click "OK" button, something then went wrong as Picture 3 shown. Actually, the executable file is working when it is started at Unit 1. I was wondering if the connection is OK?  I found it will display "Disconnenction ... " in command window at Unit 1 every time I hit "Test Connection" or "OK".
>    ![image](https://user-images.githubusercontent.com/46989828/57766496-01971d80-773a-11e9-819b-6c8937309b21.png)
> 
> ![image](https://user-images.githubusercontent.com/46989828/57766645-4f138a80-773a-11e9-8ec8-17c73f721a9a.png)

The connection seems to be fine, but you need to make sure the path to the executable is valid on the "server" side.
