### ISSUE TITLE
FLAT ops get classified incorrectly in Analyze Mode

### ISSUE THREAD

**Issue by Jasper-Bekkers** [GPUOpen-Tools/CodeXL#25]
It looks like FLAT ops get classified as Vector ALU in Code XL Analyze Mode.

I'm on version 2.0.12406.0, it's an OpenCL kernel compiled for 64-bit Fiji.

![image](https://cloud.githubusercontent.com/assets/49594/15510883/954ea0e8-21d9-11e6-9172-cc7d63ff300a.png)

**Comment by AmitBM** [comment]
Thanks for reporting this issue.

**Comment by Jasper-Bekkers** [comment]
Also it looks like the cycle counts for v_min_f32, v_max_f32, v_min_i32 etc are incorrectly marked as Varies instead of 4.

**Comment by AmitBM** [comment]
Thanks. It seems like this is the case for the following instructions as well - 
VOP1_V_FRACT_F32
VOP1_V_TRUNC_F32
VOP2_V_MAX_LEGACY_F32
VOP2_V_MIN_LEGACY_F32
VOP2_V_CEIL_F32
VOP2_V_RNDNE_F32
VOP2_V_FLOOR_F32
VOP2_V_MOV_FED_B32
VOP2_V_MAX_U32
VOP2_V_MIN_U32
VOP2_V_ASHR_I32

**Comment by AmitBM** [comment]
This issue should be resolved in version 2.4, which was released today.
