### ISSUE TITLE
AMD must quickly react to this disruptive change.

### ISSUE THREAD

**Issue by LifeIsStrange** [GPUOpen-Tools/CodeXL#253]
https://news.ycombinator.com/item?id=20629174

This is not a codeXL issue but please reach AMD engeeners / managers about this Nvidia innovation, it will provide them a potentially massive competitive advantage until AMD catch up. 

It would be nice to let me know what you will do about it. 
Anyway you can close the issue.

**Comment by mcleary** [comment]
What about this:

https://rocm-documentation.readthedocs.io/en/latest/Remote_Device_Programming/Remote-Device-Programming.html#rocmrdma

**Comment by LifeIsStrange** [comment]
@mcleary awesome!
The only thing lacking seems to be public benchmarcks results. 

Btw I see you work at codeplay which is really cool!
I hope SYCL has a bright future :)
