### ISSUE TITLE
no devices available when profiling

### ISSUE THREAD

**Issue by LosevMikhail** [GPUOpen-Tools/CodeXL#257]
Hello everyone.
When i try to profile my executable (which does work correct when not profiled) i get a popup telling me "unable to gather the profile data". In the terminal it says clGetDeviceIDs returned -1, which means no devices available. I am using Radeon RX550 on ubuntu 18.04 with amggpu-pro 19.30 driver, CodeXL 2.6 launched in root mode.  Could anybody tell me please, what can be the reason why my executable can get device ids when not being profiled, but cant do it being profiled?

**Comment by LosevMikhail** [comment]
It works with CodeXL 2.5, but it requires an old version of libpng

**Comment by songyupeng** [comment]
Hi,
Any progress? I met the same problem
ubuntu 18.04, amdgpu-pro 19.50, CodeXL2.6, Amd Radeon RX580
