### ISSUE TITLE
Crash when checking ISA for OpenCL kernel

### ISSUE THREAD

**Issue by Woking-34** [GPUOpen-Tools/CodeXL#28]
CodeXL always crashes when I try to analyze OpenCL kernels after building and clicking on the specific Graphics IP to check the ISA - CodeXL_Win_2.0.12406

Operating System:
Win7-64

Call stack:
Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
RaiseException - N/A - N/A - C:\Windows\syswow64\KERNELBASE.dll - 0x7598c4f7 - 0x75980000 - 0x7598c54e
CxxThrowException - N/A - N/A - C:\Windows\system32\VCRUNTIME140.dll - 0x67944930 - 0x67940000 - 0x67944994
qBadAlloc - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Core.dll - 0x662fae60 - 0x662e0000 - 0x662fae89

System DLL Versions:
 - atioglxx.dll: 6.14.10.13440
 - atio6axx.dll: 6.14.10.13440
 - aticfx32.dll: 8.17.10.1460
 - aticfx64.dll: 8.17.10.1460
 - aticaldd.dll: 6.14.10.1848
 - nvoglv32.dll: 10.18.13.6447
 - nvoglv64.dll: 10.18.13.6447
 - NVCUDA.dll: 6.14.13.6447
 - OpenCL.dll: 2.0.6.0

OpenGL Renderer:
 - Renderer Vendor: ATI Technologies Inc.
 - Renderer Name: AMD Radeon R9 200 Series
 - Renderer Version: 4.5.13440 Compatibility Profile Context 16.200.1013.0
 - Renderer Type: Installable client

Drivers versions:
 - CAL version: 1.4.1848
 - AMD Radeon Software version: 15.8

Device 1 (CPU):
 - Platform ID: 1
 - Device Type: CPU
 - Device Name: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
 - Vendor: Intel(R) Corporation

Device 2 (CPU):
 - Platform ID: 2
 - Device Type: CPU
 - Device Name: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
 - Vendor: Intel(R) Corporation

Device 3 (GPU):
 - Platform ID: 3
 - Device Type: GPU
 - Device Name: Hawaii
 - Vendor: Advanced Micro Devices, Inc.

Device 4 (CPU):
 - Platform ID: 3
 - Device Type: CPU
 - Device Name: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
 - Vendor: GenuineIntel

Platform 2:
 - Vendor: Intel(R) Corporation
 - Name: Experimental OpenCL 2.0 CPU Only Platform
 - Profile: FULL_PROFILE
 - Version: OpenCL 2.0 

Platform 1:
 - Vendor: Intel(R) Corporation
 - Name: Intel(R) OpenCL
 - Profile: FULL_PROFILE
 - Version: OpenCL 1.2 

Platform 3:
 - Vendor: Advanced Micro Devices, Inc.
 - Name: AMD Accelerated Parallel Processing
 - Profile: FULL_PROFILE
 - Version: OpenCL 2.0 AMD-APP (2079.4)

**Comment by AmitBM** [comment]
Hi, 

1. Can you please post an archive containing the contents of the relevant project's output folder (you should find it under %APPDATA%\CodeXL).
2. Can you please share the .cl file that you are trying to analyze? If you prefer not to publicly post your code, we can contact you privately via email.

Thanks.

**Comment by Woking-34** [comment]
It seems I can't really reproduce the crash every time, but it definitely happens - 32bit target for Hawaii, and open the generated ISA. Attached kernel and proj files.

[test-hawaii.zip](https://github.com/GPUOpen-Tools/CodeXL/files/289102/test-hawaii.zip)

Thanks.

**Comment by AmitBM** [comment]
This issue is not being reproduced with the CodeXL 2.2 and above.
