### ISSUE TITLE
[Vulkan] cube.exe recognized as DXGI.

### ISSUE THREAD

**Issue by vinjn** [GPUOpen-Tools/CodeXL#3]
![image](https://cloud.githubusercontent.com/assets/558657/14668457/f3524510-0716-11e6-8f9b-7e018d7f575c.png)

**Comment by doronofek** [comment]
Thanks for this report. CodeXL 2.0 does not support Vulkan frame analysis. Detecting DXGI in a Vulkan app is obviously a bug.

**Comment by vinjn** [comment]
Thanks.
What features are Vulkan supported?

**Comment by doronofek** [comment]
This is fixed in CodeXL 2.1 which supports Vulkan Frame Analysis on Windows OS.

**Comment by vinjn** [comment]
Awesome
