### ISSUE TITLE
APU not supported

### ISSUE THREAD

**Issue by deepankarsharma** [GPUOpen-Tools/CodeXL#30]
CodeXL complains that the gpu on my Carrizo laptop is unsupported (The chip in question is the 8800B carrizo and the laptop in question is the 745 G3 from HP).

**Comment by kpenujee** [comment]
Hi Deepankar Sharma,
Please let us know the display driver version installed on your Carrizo laptop. Also, what component (GPU Profiling or Static Analyzer or GPU Debugging) of CodeXL is throwing this error.

Thanks,
Kalyan P

**Comment by deepankarsharma** [comment]
I am running Ubuntu 16.04 64 bit with the following driver - amdgpu-pro_16.20.3-294842.tar.xz. Opengl is correctly working as shown by the following output using glxinfo -

OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon R7 Graphics
OpenGL core profile version string: 4.5.13439 Core Profile Context 16.20.3
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

![initial_launch](https://cloud.githubusercontent.com/assets/840385/15659677/b62ee940-269c-11e6-93f4-08c43dd125d6.png)
![profile_menu](https://cloud.githubusercontent.com/assets/840385/15659676/b62e7384-269c-11e6-9c0f-b4d3ae8864b5.png)

**Comment by deepankarsharma** [comment]
Any updates on this? Were you able to replicate the issue?

**Comment by doronofek** [comment]
We're in the midst of adding support for the amdgpu-pro driver. The fixes should be available on the master branch in a few days.

**Comment by doronofek** [comment]
Did you try to build and run with a recent clone from the master branch?
