### ISSUE TITLE
Builds for 2.1 missing?

### ISSUE THREAD

**Issue by SwooshyCueb** [GPUOpen-Tools/CodeXL#31]
It would seem that the binaries for 2.1 have been unpublished? The GPUOpen blog post still directs me to github to download the builds. I thought at first perhaps someone forgot to upload them, but looking at the [AUR package](https://aur.archlinux.org/cgit/aur.git/commit/?h=amdapp-codexl&id=c7967fff32432a39ef874179c5da8a0d8f5fa971) it would seem that they were available to download at some point in the past few days. There's even an md5 hash of 1eddbd59062815776f24ad2f41fd4676 for the Linux build archive.

**Comment by callan-amd** [comment]
This is now fixed.
