### ISSUE TITLE
Installer fails to complete

### ISSUE THREAD

**Issue by sergioafeo** [GPUOpen-Tools/CodeXL#32]
Dear all,
we have encountered a further issue with the installer. The latest version fails to complete with the following message: 

![image](https://cloud.githubusercontent.com/assets/9351519/15805689/1316b338-2b32-11e6-8e3a-bfa7f4a148f7.png)

The installer log says: `Custom action Enable_VS12_Extension script error -2146827864, Microsoft VBScript runtime error: Object required: 'objFolder.Items.Item(...)' Line 6, Column 1,` (see attached file)

The issue appears to occur when installing the VS2013 plugin. Any information would be greatly appreciated.

Cheers,
Sergio
[MSI80b22.LOG.txt](https://github.com/GPUOpen-Tools/CodeXL/files/299348/MSI80b22.LOG.txt)

**Comment by callan-amd** [comment]
VS plugins are no longer supported - only standalone CodeXL builds will be provided in future
