### ISSUE TITLE
Installation Failure - Missing Group "Users"

### ISSUE THREAD

**Issue by paulozaffari** [GPUOpen-Tools/CodeXL#37]
While using Windows 10 in Brazilian Portuguese, the installer fails due to missing group "Users".
In Brazilian Portuguese this group is called "Usuários".
A workaround for the problem is manually creating the "Users" group.

Seems to be a problem on the way to fetch the reference to the "Users" in the installer.

**Comment by JcBernack** [comment]
This should have been fixed in the most recent release v2.1.
Did you try that one or an older version?

**Comment by doronofek** [comment]
As @JcBernack noted, this was fixed in CodeXL 2.1. Were you trying to install CodeXL 2.1 or an older release?

**Comment by paulozaffari** [comment]
IIRC, I tried to install CodeXL 2.1.
100% sure it was not 1.9.

2016-06-15 8:28 GMT-03:00 Doron Ofek <notifications@github.com>:
