### ISSUE TITLE
GPU not detected

### ISSUE THREAD

**Issue by edrickhong** [GPUOpen-Tools/CodeXL#39]
I cannot do any gpu profiling or debugging because codexl claims that it does not detect an AMD supported gpu. 

This is the output log file:

```
2016.06.19      11:07:30.055    #1466305650055  #INFO   #0      #140430741342848        #outputLogFileHeader    #/data/jenkins/workspace/CodeXL-2.1-Linux/Common/Src/AMDTOSWrappers/src/common/osDebugLog.cpp   #669    #This File contains debug printouts for CodeXL. http://gpuopen.com/
2016.06.19      11:07:30.055    #1466305650055  #INFO   #0      #140430741342848        #outputSessionHeader    #/data/jenkins/workspace/CodeXL-2.1-Linux/Common/Src/AMDTOSWrappers/src/common/osDebugLog.cpp   #723    #OpenGL Renderer:
2016.06.19      11:07:30.055    #1466305650055  #INFO   #0      #140430741342848        #outputSessionHeader    #/data/jenkins/workspace/CodeXL-2.1-Linux/Common/Src/AMDTOSWrappers/src/common/osDebugLog.cpp   #723    # - Renderer Vendor: ATI Technologies Inc.
2016.06.19      11:07:30.055    #1466305650055  #INFO   #0      #140430741342848        #outputSessionHeader    #/data/jenkins/workspace/CodeXL-2.1-Linux/Common/Src/AMDTOSWrappers/src/common/osDebugLog.cpp   #723    # - Renderer Name: AMD Radeon (TM) R9 380 Series
2016.06.19      11:07:30.055    #1466305650055  #INFO   #0      #140430741342848        #outputSessionHeader    #/data/jenkins/workspace/CodeXL-2.1-Linux/Common/Src/AMDTOSWrappers/src/common/osDebugLog.cpp   #723    # - Renderer Version: 4.5.13439 Compatibility Profile Context 16.20.3
2016.06.19      11:07:30.055    #1466305650055  #INFO   #0      #140430741342848        #outputSessionHeader    #/data/jenkins/workspace/CodeXL-2.1-Linux/Common/Src/AMDTOSWrappers/src/common/osDebugLog.cpp   #723    # - Renderer Type: Hardware renderer
2016.06.19      11:07:30.055    #1466305650055  #INFO   #0      #140430741342848        #outputSessionHeader    #/data/jenkins/workspace/CodeXL-2.1-Linux/Common/Src/AMDTOSWrappers/src/common/osDebugLog.cpp   #747    #Application=CodeXL-bin, Product=Standalone, OS=LinuxUbuntu-64, Version=2.1.228.0 Release Version
2016.06.19      11:07:30.055    #1466305650055  #INFO   #0      #140430741342848        #executeSpecificCommand #AMDTApplicationFramework/commands/src/afInitializeApplicationCommand.cpp       #109    #Application initialization started
2016.06.19      11:07:30.056    #1466305650056  #INFO   #0      #140430741342848        #InitializeUnicodeCharactersUserFilePath        #/data/jenkins/workspace/CodeXL-2.1-Linux/Common/Src/AMDTOSWrappers/src/common/osFilePath.cpp   #902    #User app data folder. Original location: /home/pluto/.CodeXL. Current location: /home/pluto/.CodeXL
2016.06.19      11:07:30.056    #1466305650056  #ERROR  #0      #140430741342848        #oaGetDriverVersion     #/data/jenkins/workspace/CodeXL-2.1-Linux/Common/Src/AMDTOSAPIWrappers/src/linux/oaDriver.cpp   #110    #Assertion failure (rcLoadedModule && (driverModuleHandle != __null))
2016.06.19      11:07:30.107    #1466305650107  #ERROR  #0      #140430741342848        #osExecAndGrabOutput    #/data/jenkins/workspace/CodeXL-2.1-Linux/Common/Src/AMDTOSWrappers/src/linux/osProcess.cpp     #1242   #Failed to read output
2016.06.19      11:07:30.158    #1466305650158  #INFO   #0      #140430741342848        #FindInstalledAMDComponents     #AMDTApplicationFramework/src/afGlobalVariablesManager.cpp      #1096   #CodeXL GPU Profiler: AMD GPU was not detected. Local GPU Profiling will be disabled.
```

The OpenGL renderer is able to detect my graphics card though. I am running Ubuntu Mate 16.04 with the AMDGPU-Pro driver with a R9 380.

EDIT: I noticed it "failed to collect OpenCL devices information", but clinfo was able to get my gpu info.

**Comment by doronofek** [comment]
Support for the amdgpu-pro driver is currently being added in the master branch as part of the development going into CodeXL 2.2.
If you build CodeXL from the master branch you'll get the bleeding edge level of support. GPU Profiling should work and GPU Debugging of OpenCL apps, but only if they're not using OpenGL.

**Comment by edrickhong** [comment]
Thanks. I tried as you suggested but I am having problems building the backend. The build fails at sprofile. The log file contains mostly errors like this : 

> ./obj/release/x64/ParseCmdLine.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueIccEE[_ZTVN5boost15program_options11typed_valueIccEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'

Looks like the problem is with boost. I do have boost 1.58 on my system and thought it might be that
but I read the scons files and it looks like the boost library was specified by path to use the one provided. Unless I am mistaken. I am familiar with neither scons nor python so I'm sorry if I read it wrong :p

**Comment by bhsomegowda** [comment]
Similar issue! I am running Ubuntu 16.04 on AMD Embedded R-Series RX-421BD Radeon R7, installed amdgpu pro driver and CodeXL 2.2. CodeXL fails to detect the GPU and collect opencl device and platform information. But the clinfo application collects and displays the platform and opencl device information. Any help is greatly appreciated!

**Comment by tangjie77wd** [comment]
@edrickhong @doronofek @bhsomegowda 
Hello!I create projects with OpenCL on linux . My machine : CentOS 7.3+eclipse + AMD Rx560 + amdgpu-pro-17.30-465504 + CodeXL_Linux_x86_64_2.4.60 .

1.    After I installed all tools above , go into the 'CodeXL_Linux_x86_64_2.4.60' folder and open a terminal ,run the command : ./CodeXL ,then CodeXL gui will appear .
2.    Click the 'Help' menu and then click 'Load the Teapot Sample' .
3.   Click the 'Profile' menu and then clike 'GPU:Performance Counters' .
4.   Press 'F5' on your keyboard and wait for a while.
5.   Close the 'AMD Teapot Example' gui and wait for a while , you will see many performance indicators in the CodeXL gui.
But I have a question these days : the Teapot sample is provided by CodeXL not myself (It exists in CodeXL as a 'CodeXL Teapot.cxl' file ,so we can load it directly in CodeXL. ) , how can i use CodeXL to test the performance of my own OpenCL projects (.cpp file and .cl file) written in the eclipse ( no .cxl file )? Any help will be much appriciate !

**Comment by bhsomegowda** [comment]
You can do performance evaluations of your .cl or final executable files 
regardless if its written in Eclipse IDE or any other IDE as long as it 
sits on the disk. You just have to go to that path where they are 
located and import them.

**Comment by tangjie77wd** [comment]
@bhsomegowda  Unfortunately,when i click 'File' in CodeXL-Gui 、'Open Project' of this menu , it assigns the files of type must be '*.cxl' . As you know, the files of type I written in Eclipse is '.cpp' and '.cl' which means there is no '.cxl'.Therefore,how could i load a project being compose of '.cpp' and '.cl' in CodeXL-GUI ?

**Comment by bpurnomo** [comment]
Please check out the Project Settings documentation within the CodeXL User Guide (Using CodeXL -> General GUI Controls -> Project Settings).  You can open the CodeXL User Guide within the CodeXL tool by pressing F1.

Basically, you need to create a CodeXL project and set it up to point to your application executable binary.

**Comment by tangjie77wd** [comment]
@bpurnomo  Thank you very much! 'set it up to point to your application executable binary' helpd me a lot ! And now I can load my own project into CodeXL-GUI ! Thanks very very much!

**Comment by bpurnomo** [comment]
You are welcome.  Next time, please open a new ticket for such question instead of responding on many other unrelated tickets.
