### ISSUE TITLE
New CodeXL backend

### ISSUE THREAD

**Issue by PeterCarragher** [GPUOpen-Tools/CodeXL#41]
Hey there, 

Im currently researching into the possibility of adding in another backend for CodeXL (similar to OpenCL). What would be the best way to go about this? I have been reading through the OCL, HSA, Vulkan and DX12 backend files and although they share quite a bit in common, I am not sure exactly what is necessary, as I do not fully understand how the profiling and tracing code works. 

The backend we are trying to add is basically a layer over OpenCL, so it seems like it should be possible to add another backend for it. 

Any help, hints or explanations would be appreciated, 

Thanks, 
Peter

**Comment by doronofek** [comment]
Hi Peter,
Your initiative is very welcome!
I'll make a brief note here and later I'll ask the team to add more details:
The CodeXL GPU Profiler backend supports OpenCL, HSA and DirectCompute.
The CodeXL Frame Analysis backend supports DX12 and Vulkan.
The GPU Profiler and Frame Analysis are 2 separate components and while their frontend uses a common codebase and reuses a lot of modules, their backends are separate. 
It is my understanding that you're looking to enhance the GPU Profiler backend. It runs as a command line executable which launches the profiled app, collects the data and stores it in files. Then the frontend reads those files and presents them graphically to the user. If you retain the current data files format the frontend should require little work to display the data collected by the new backend.

Doron

**Comment by chesik-amd** [comment]
Hi Peter,

If you're just trying to support a layer that sits on top of OpenCL, another possibility would be to instrument that layer using the AMDTActivityLogger library.  Using that library, you can add extra items into the timeline view in CodeXL.  They will be displayed alongside the OpenCL calls in the timeline. It might be worth looking into this to see if it would meet your needs (as it will likely be less work to integrate than adding a whole new backend).

The documentation of the AMDTActivityLogger library can be found here:  https://github.com/GPUOpen-Tools/CodeXL/blob/master/Common/Src/AMDTActivityLogger/Doc/AMDTActivityLogger.pdf

**Comment by PeterCarragher** [comment]
Hi Doron and Chris,

Thanks for the tips, especially the ActivityLogger idea (it would be a lot easier). As it turns out Chris a colleague of mine (Simon Brand) was going to put me in touch with you anyway! The backend we are trying to add is for SYCL (https://www.khronos.org/sycl). However, just adding to the timeline may not be enough, we want to add support for performance counters also, and from my understanding the ActivityLogger wouldn't achieve this. 

So, focusing on the GPU profiling backend, like HSA and OpenCL, I would assume this involves creating a SYCL Occupancy, Profile and Trace agent, following the format of the current OpenCL backend so that we can generate both the .CounterFile and the .atp file for the frontend. I was wondering why OpenCL requires a server and HSA does not and whether this would be necessary for SYCL. 

Thanks again for the help, 
Peter
