### ISSUE TITLE
System Information dialog fails to display device information

### ISSUE THREAD

**Issue by lukase** [GPUOpen-Tools/CodeXL#42]
When selecting the "OpenCL Devices" tab in the system information dialog, no information is shown. The status reads "Failed to collect OpenCL devices information".

The relevant excerpt from the log file:

> 2016.06.27    13:59:56.437    #571295437  #ERROR  #0  #2908   #afSystemInformationCommand::CollectOpenCLDevicesInformation    #commands\afSystemInformationCommand.cpp    #1361   #Assertion failure (filePath.exists())
> 2016.06.27    13:59:56.670    #571295670  #ERROR  #0  #2908   #afSystemInformationCommand::CollectOpenCLDevicesInformation    #commands\afSystemInformationCommand.cpp    #1361   #Assertion failure (filePath.exists())
> 2016.06.27    13:59:56.730    #571295730  #ERROR  #0  #2908   #afSystemInformationCommand::CollectAllOpenCLDevicesInformation #commands\afSystemInformationCommand.cpp    #1169   #Assertion failure (res32bit || res64bit)
> 2016.06.27    13:59:56.764    #571295764  #INFO   #0  #2908   #afOpenCLDeviceInformationCollector::entryPoint #src\afOpenCLDeviceInformationCollector.cpp #35 #m_dataCollectedOk = 0, m_openCLDevicesInfoData.size = 0
> 2016.06.27    13:59:56.505    #573203505  #INFO   #0  #4112   #afSystemInformationDialog::timerEvent  #dialogs\afSystemInformationDialog.cpp  #358    #rcGetInfo=0, _openCLDevicesInfoData.size = 0
> 2016.06.27    13:59:56.588    #573203588  #ERROR  #0  #4112   #afSystemInformationDialog::timerEvent  #dialogs\afSystemInformationDialog.cpp  #360    #Assertion failure (rcGetInfo)

This error occurs on multiple machines running the german version of Windows 8.1 x64 using the standalone CodeXL application 2.1.223.0

**Comment by FrozenKiwi** [comment]
I have the same issue: Windows 10, Canada, 480 RX

I have a message in the log (maybe related?)
"Please verify that firewall settings allow CodeXL and CodeXLRemoteAgent to communicate over the network, even for local scenarios."

I can't find rules blocking in my firewall though

**Comment by kpenujee** [comment]
Hi,
firewall error occurs when you try to run a FrameAnalysis session while firewall is turned ON.
Windows firewall can be turned off by opening "Control Panel -> Windows firewall".

Thanks,
Kalyan P
