### ISSUE TITLE
CodeXL Remote immediately disconnects

### ISSUE THREAD

**Issue by tobig** [GPUOpen-Tools/CodeXL#43]
Dear all,

I just tried CodeXLRemote for remote profiling and unfortunately at each connection attempt CodeXL immediately disconnects. The only messages I see on the CodeXLRemote prompt are:

```
*** Connection: Received a connection from <xxx.xxx.xxx.39:8138> ***
*** Disconnection: <xxx.xxx.xxx.39:8138>ended a session and disconnected ***
```

CodeXL itself says: "Could not create debugged process. Unable to connect to CodeXL Remote Agent."

Obviously, it was able to build up some connection, but for whatever reason it is not able to proceed. I am using the official AMD build 2.1.228.0. What would be the best way to debug this further?

Some context information:

I started CodeXLRemote from an SSH shell using a normal user account. I use a little hack to make the X11 context available to the user by running the following script as root:

```
#! /bin/bash
XAUTHPORT=$(echo $DISPLAY | cut -d'.' -f1 |  cut -d':' -f2)
xauth extract /tmp/x11-auth-file ":$XAUTHPORT"
chmod 660 /tmp/x11-auth-file
chgrp amdgroup /tmp/x11-auth-file

cat > /tmp/enable-amd-compute <<EOF
export COMPUTE=$DISPLAY
export DISPLAY=$COMPUTE
export XAUTHORITY=/tmp/x11-auth-file
EOF
```
This hack works well. Meaning after I source /tmp/enable-amd-compute, I can run OpenCL programs without any trouble on my AMD GPU.

**Comment by doronofek** [comment]
Hi,
We've addressed this issue in CodeXL 2.2 which was released yesterday. Cay you give it a try?
Thanks,
Doron

**Comment by Conradin94** [comment]
Thank you!
There are no more unexpected disconnects with CodeXL 2.2.
Conradin

**Comment by tobig** [comment]
Thank you!

A minor remark. I would have been happy to compile my own CodeXL. Hence, I would have been happy to test (or just know) about commits that fixed this issue, even before the actual release took place.

Best
