### ISSUE TITLE
CodeXL for non AMD hardware ( help needed) 

### ISSUE THREAD

**Issue by psharma187** [GPUOpen-Tools/CodeXL#44]
Hi All,

Not sure if this is the correct place to ask this question. I am trying to see if we can use CodeXL for non AMD GPUs( example mobile ) . It would be great if someone can answer below question. 

1. Can CodeXL open source be extended to support other platforms ? I assume other GPU vendors should support the GPU hardware counters etc. , but right now I am interested in seeing if the source can be easily extended and also all relevant sources  are open.  
2. If 1 is difficult to do, Is it possible to understand the GPU profile binary format ? Idea is to generate that file using some other profiler or tool and view it using CodeXL.  For example systrace file in android can be viewed using chrome javascript. Aim is covert that file ( or re capture ) in a format which CodeXL can understand. So we can use viewing functionality from CodeXL but capture the counters using some other tool.

Any help is appreciated ! .

Regards,
Prashant

**Comment by chesik-amd** [comment]
Hi Prashant,

The GPU Profiler's output files are all text files, not binary files.  When collecting an Application Timeline Trace for an OpenCL or ROCm application, the output file is an .atp file.  When collecting Performance Counters, the output file is a .csv file.  There is a topic in the CodeXL help file that describes the file formats.  See "Help > Using CodeXL > GPU Profiler > Using the GPU Profiler > Description of Output Files" in the CodeXL Help file.

Chris

**Comment by psharma187** [comment]
Thanks Chris, 

I was able to see some details on the .apt file format. I was just wondering if this feature is only for the compute applications. What about GPU counters etc. while running OpenGL or Vulkan applications ? 
http://gpuopen.com/compute-product/codexl/ mention support of " DirectX 12 and Vulkan Frame Analysis" . but is this same software ? and does it also support OpenGL along with Vulkan & DirectX ? 
My aim is to explore if we can use CodeXL viewer for embedded graphics applications written with OpenGLES, vulkan with different GPUs & CPUs.

Cheers,
Prashant

**Comment by yrouban** [comment]
I have a similar question about the CPU Profiler for non-AMD. Why did not CodeXL team implement other than time-based profiling for non-AMD processors. The linux perf tool seems to be a good mean for this. Do you think it is possible to use the linux perf tool with the current design of CodeXL?

**Comment by swarup-sahoo** [comment]
Hi Prashant,
CodeXL uses AMD Model Specific Registers (MSR) to perform other than time-based profiling (TBP). To support CodeXL on non-AMD platforms, CodeXL need to utilise non-AMD MSRs. Yes, you are right, PERF interface can be used on Linux platforms (of course with some additional code changes) to achieve the same, but on Windows platforms, CodeXL need to implement non-AMD MSRs support. For TBP, it doesn't use any MSRs, hence it is supported on both AMD & non-AMD platforms. Support of non-AMD platforms is not in the CodeXL feature planning list yet.

Thanks,
Swarup
