### ISSUE TITLE
CodeXL doesn't allow me to step into kernel source

### ISSUE THREAD

**Issue by lonelygoat** [GPUOpen-Tools/CodeXL#47]
When I tried to step into a kernel, a dialog box popped up and saying IL instruction uav_read_cmp_xchg is not yet supported. see the attached. Tracing into other kernels is ok... I have no idea what in that kernel triggered this error. can I avoid this by modify my kernel ?

![codexl](https://cloud.githubusercontent.com/assets/11893467/16725072/2f3a7fdc-4788-11e6-8c3f-4b7f279fe29b.jpg)

**Comment by doronofek** [comment]
The CodeXL GPU Debugger does not support debugging of OpenCL kernels that use atomic operations. Avoid *atomic_** and *atom_** instructions to allow kernel debugging.
