### ISSUE TITLE
Bundling issues: version `PNG12_0' not found

### ISSUE THREAD

**Issue by LebedevRI** [GPUOpen-Tools/CodeXL#50]
When i try to run CodeXL-2.1 on debian sid, i get:

```
$ ./CodeXL
/opt/CodeXL_2.1-228/./CodeXL-bin: /usr/lib/x86_64-linux-gnu/libpng12.so.0: version `PNG12_0' not found (required by /opt/CodeXL_2.1-228/./RuntimeLibs/QT/libQt5Gui.so.5)
/opt/CodeXL_2.1-228/./CodeXL-bin: /usr/lib/x86_64-linux-gnu/libpng12.so.0: version `PNG12_0' not found (required by /opt/CodeXL_2.1-228/./RuntimeLibs/QT/libQt5WebKit.so.5)
```

There is no libpng12, and the only libpng in debian sid is `libpng16-16`

**Comment by ilangal-amd** [comment]
Hi Roman, 

Which exact operation system you are using?
Most Ubuntu repositories contain the package [libpng12-0](http://packages.ubuntu.com/search?keywords=libpng12-0&searchon=names&suite=all&section=all) .

Thanks, 
Ilan.

**Comment by LebedevRI** [comment]
I'm using `debian gnu/linux`, sid aka unstable.
https://wiki.debian.org/DebianUnstable
https://www.debian.org/releases/sid/

**Comment by LebedevRI** [comment]
Still an issue with CodeXL 2.2

**Comment by SilverNexus** [comment]
Exists in Debian testing (Stretch) on CodeXL 2.3 as well.

**Comment by chesik-amd** [comment]
CodeXL no longer relies on libpng, so I think this should no longer be an issue
