### ISSUE TITLE
codexl crashes visual studio modelling project when not running

### ISSUE THREAD

**Issue by drewskinz** [GPUOpen-Tools/CodeXL#51]
I'm using vs 2015 enterprise and occasionally (and seemingly randomly) I get the codexl error message pop up and VS crashed and quits. See below
Currently working on a c# modelling project so not actually doing anything with codexl at all, but have it installed. It wont even send the error log.

Operating System:
Win7-64

Call stack:
Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
N/A - N/A - N/A - N/A - N/A - N/A - N/A

System DLL Versions:
- atioglxx.dll: 6.14.10.13399
- atio6axx.dll: 6.14.10.13399
- aticfx32.dll: 8.17.10.1404
- aticfx64.dll: 8.17.10.1404
- aticaldd.dll: 6.14.10.1848
- OpenCL.dll: 2.0.4.0

OpenGL Renderer:
- Renderer Vendor: ATI Technologies Inc.
- Renderer Name: AMD Radeon HD 7520G
- Renderer Version: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
- Renderer Type: Installable client

Drivers versions:
- CAL version: 1.4.1848
- AMD Radeon Software version: 15.7.1

Device 1 (GPU):
- Platform ID: 1
- Device Type: GPU
- Device Name: Scrapper
- Vendor: Advanced Micro Devices, Inc.

Device 2 (CPU):
- Platform ID: 1
- Device Type: CPU
- Device Name: AMD A6-4400M APU with Radeon(tm) HD Graphics
- Vendor: AuthenticAMD

Platform 1:
- Vendor: Advanced Micro Devices, Inc.
- Name: AMD Accelerated Parallel Processing
- Profile: FULL_PROFILE
- Version: OpenCL 2.0 AMD-APP (1800.8)

**Comment by drewskinz** [comment]
I think it is related to checking for updates.At one stage and an error message (which I didnt capture) said that it it has crashed while updating a plug-in, but whenever I go to the 'check for updates' in codeXL it seems to revert to checked and every day, regardless of whether I untick 'check for updates' of change it to months. Is there any way to turn off updates somewhere else (a config file?), otherwise I guess its uninstall so I can work.

**Comment by callan-amd** [comment]
The Visual Studio plugin functionality has been deprecated. Future builds of CodeXL will be standalone only
