### ISSUE TITLE
Visibility of inlined (intrinsic) functions in CPU profile

### ISSUE THREAD

**Issue by jmcebriangonzalez** [GPUOpen-Tools/CodeXL#52]
Dear all.

This is not a bug report, but some question/comments to improve the usability of the tool. I cannot find any other way to communicate with the developers/user community.

I've been trying to analyze some codes using version 2.1 of CodeXL that include both inlined functions and intrinsics. Timing information per function is provided even for inlined functions. When I was using Code Analyzer a while ago I don't think this feature was available.

While this is great for some cases, for me is a pain in the ass. I have manually vectorized sections of the code using intrinsics, and I need the timing information of those intrinsics and other inlined functions (manually implemented SIMD code) to be accounted as part of the original function, so that I can compare performance against the original scalar code. 

Is there any way to force CodeXL to profile inlined functions as part of the code that calls the function?. I do not want/need them to be profiled independently.

Best regards, Juan Manuel.

**Comment by swarup-sahoo** [comment]
Hi Juan,

This is the right place to discuss CodeXL related questions/comments.

Are you running CodeXL on Windows or Linux?

If it is on Windows platform, there is a way to disable profiling for inline functions.
If it is on Linux platform, we have not added the support to disable profiling of inline functions.

On Windows platform, please add a environment variable "AMDT_CPUPROFILE_PROCESS_INLINE" with value as "NO". This should disable profiling on inline functions on Windows platform.

Regards,
Swarup

**Comment by jmcebriangonzalez** [comment]
Thank you for your quick reply.

I'm glad to hear you have considered this case. Sadly, I'm working on a Linux platform, so I guess I'll have to wait.

Nevertheless, I seem to have found a work-around that may be useful for other users. If you build the application without debugging information, run the profile, rebuild with -g or -g3 and open the profile, you get per-function timing information without accounting for inlined functions nor intrinsics. I guess it could lead to a mismatching of timing information to source code, but we have to live with that for the moment.

Anyway, I'd like to take this opportunity to thank you for this great tool, it is much more stable and usable than years ago. Hopefully, it will continue to improve in the future.

Regards, 
Juan Manuel.

**Comment by swarup-sahoo** [comment]
We will submit similar fix for Linux next week, but it will not be available to you in the downloaded CodeXL. If you can build CodeXL from github source, you might be able suppress inline profiling.

For the time being, you may continue by disabling inlining using GCC flags as suggested by you.

Thank you for all the appreciations. We will keep on improving CodeXL to make it more and more useful.
