### ISSUE TITLE
Memory leak after raw data translation

### ISSUE THREAD

**Issue by jmcebriangonzalez** [GPUOpen-Tools/CodeXL#54]
Hi.

I've noticed that CodeXL 2.1.228.0 is using 3.121g of memory to do the translation when using intrinsics, that are never freed. So if I profile several times without closing the application I eventually crash the system. Please let me know if there is something else I can provide to solve this issue.

I'm attaching an example project with the binary that causes the problems, you need to adjust the routes of the project and LD_PRELOAD the .SO files (ldd vips).

[app_and_libs.zip](https://github.com/GPUOpen-Tools/CodeXL/files/397252/app_and_libs.zip)
[project.zip](https://github.com/GPUOpen-Tools/CodeXL/files/397253/project.zip)

The input is too big to be provided here, it can be downloaded from here:

http://parsec.cs.princeton.edu/download/3.0/parsec-3.0-input-native.tar.gz

You need to untar vips/input_native.tar to the run folder you select in the project.

I'm running:

Linux 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
# H/W path       Device     Class          Description

```
                      system         Latitude E7440 (Latitude E7440)
```

/0                        bus            07F3F4
/0/0                      memory         64KiB BIOS
/0/42                     processor      Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
/0/42/43                  memory         128KiB L1 cache
/0/42/44                  memory         512KiB L2 cache
/0/42/45                  memory         4MiB L3 cache
/0/46                     memory         8GiB System Memory
/0/46/0                   memory         DIMM [empty]
/0/46/1                   memory         8GiB SODIMM DDR3 Synchronous 1600 MHz (0.6 ns)
/0/100                    bridge         Haswell-ULT DRAM Controller
/0/100/2                  display        Haswell-ULT Integrated Graphics Controller
/0/100/3                  multimedia     Haswell-ULT HD Audio Controller
/0/100/14                 bus            8 Series USB xHCI HC
/0/100/16                 communication  8 Series HECI #0
/0/100/19      eth0       network        Ethernet Connection I218-LM
/0/100/1b                 multimedia     8 Series HD Audio Controller
/0/100/1c                 bridge         8 Series PCI Express Root Port 1
/0/100/1c.3               bridge         8 Series PCI Express Root Port 4
/0/100/1c.3/0  wlan0      network        Wireless 7260
/0/100/1c.4               bridge         8 Series PCI Express Root Port 5
/0/100/1c.4/0             generic        SD/MMC Card Reader Controller
/0/100/1d                 bus            8 Series USB EHCI #1
/0/100/1f                 bridge         8 Series LPC Controller
/0/100/1f.2               storage        8 Series SATA Controller 1 [AHCI mode]
/0/100/1f.3               bus            8 Series SMBus Controller
/0/1           scsi1      storage  
/0/1/0.0.0     /dev/sda   disk           256GB SAMSUNG SSD PM85
/0/1/0.0.0/1   /dev/sda1  volume         29GiB EXT4 volume
/0/1/0.0.0/2   /dev/sda2  volume         8189MiB Linux swap volume
/0/1/0.0.0/3   /dev/sda3  volume         200GiB EXT4 volume
/1                        power          DELL 909H538

Best regards, Juan Manuel.

**Comment by swarup-sahoo** [comment]
Hi Juan,
Thank you for bringing up this issue. Most probably we have fixed this type of issues in next release of CodeXL. We will still look into this. If possible could you please provide following information:

1) Which CPU Profiling session used? (ex. Time-based, Assess, etc.)
2) Was it a System-wide profiling?
3) How many old sessions were present in the session navigation pane (i.e. left side pane)?
4) How much memory is consumed if you just launch CodeXL and don't do anything. Can you delete any used old sessions and observe any reduction in memory consumption?

Regards,
Swarup

**Comment by jmcebriangonzalez** [comment]
Hi Swarup.

- Time-based Sampling, for all cores, with call stack details (every sample). 
- It's Single Application Profile (vips), 
- I've tried both with a project with several sessions and one that was empty and created a new session. Both behave the same.
- When you open CodeXL the application uses ~100MB of RAM, regardless of the number of sessions active, I have a project with 7 sessions and no trouble once they are translated from raw data if I re-open the application (closing the project or deleting a session does not free the memory, you need to close the tool). 

The amount of memory consumed goes from 100MB to 170 when running the application, then it starts rapidly rising up to 3GB -6GB when performing the translation after finishing running the application (around 1 minute of profile). It uses 3GB for both the base code without SIMD intrinsics and 3.2GB for the intrinsic-based AVX versions with single-precission floating point. However, it uses 6GB for the double-precission ones. I guess this is reasonable, since it the code runs twice the instructions from float to double to compute the same input, and CodeXL allocates double the statistics. 

When I run the application built without the -g3/-g flag, it goes back to 140MB after raw data translation.

**Comment by swarup-sahoo** [comment]
Hi Juan,
New CodeXL version 2.2 is recently released. It would be great if you can try this scenario on 2.2 and let us know your observations.

https://github.com/GPUOpen-Tools/CodeXL/releases/tag/v2.2 

Regards,
Swarup

**Comment by jmcebriangonzalez** [comment]
I've tried upgrading to version 2.2.

I've got the same problems as in the previous version. I've tried with a new project and with the old project, in both cases the memory leak persists when running the -g/-g3 built codes.

Regards, Jm.

**Comment by swarup-sahoo** [comment]
Thank you, Juan. We will look into this issue.

**Comment by bpurnomo** [comment]
The CPU Profiler has been forked into https://developer.amd.com/amd-uprof/
