### ISSUE TITLE
Power Profiling Requirements 

### ISSUE THREAD

**Issue by PeterCarragher** [GPUOpen-Tools/CodeXL#55]
Hello, 

I currently have the Radeon R7 240 card. When I build CodeXL on windows and try switch to Power Profiling mode, its says this is not supported. However on the release notes it says Power Profiling is enabled for the codename 'sea island' chips, including Radeon and FirePro. Surely then Power Profiling should be enabled for the Radeon R7 240?

If it is just that the requirements were incorrect, then what are the actual requirements? Would I be able to get a list of compatible cards somehow?

Thanks in advance, 
Peter

**Comment by doronofek** [comment]
Hi Peter,
In order to use Power Profiling you must install the CodeXL Power Profiling driver.
The easiest way to do this is to download the pre-built installer from the Releases section and run it.
Doron

**Comment by doronofek** [comment]
The CodeXL installer for Windows installs the power profiling driver:
https://github.com/GPUOpen-Tools/CodeXL/releases/download/v2.2/CodeXL_Win_2.2.733.exe

**Comment by PeterCarragher** [comment]
Thanks again. Just as a note for people in the future, maybe this should be documented? Also the name CodeXL_Win_xxxx.exe makes it seem like a CodeXL installer rather then a Power Profiling driver.

**Comment by aalok-agarwal** [comment]
Hi Peter, 

In case of Linux, you can download the CodeXL installer for the respective Linux distro from 
https://github.com/GPUOpen-Tools/CodeXL/releases/download/v2.2/

For detailed instruction on how to install and use power profiler in Linux and Windows OS please refer User guide located at 
https://github.com/GPUOpen-Tools/CodeXL/releases/download/v2.2/CodeXL_User_Guide.chm

If you have already installed CodeXL using the windows installer, yes you should be able to use it with source version of CodeXL.

In case of Linux, please refer section: Using CodexL > Power Profiler > Installing the Power Profiler Linux Driver in CodeXL_User_Guide.chm.

Help let us know if any other info is required.

Regards
Aalok
