### ISSUE TITLE
Install problem with CodeXL_Win_2.1.223

### ISSUE THREAD

**Issue by db2ugitthis** [GPUOpen-Tools/CodeXL#56]
When trying to install CodeXL_Win_2.1.223.exe on an AMD Piledriver PC with Windows 7 64 bit, I receive the error "Warning 4154. Microsoft Debuggers And Tools x86 prerequisite was not correctly installed.  Continue installation of CodeXL?".  I did not continue.  What are the details of this problem?  Where do I find a log of details on my PC?  What is the solution?  I am not using DirectX 12 or an AMD APU yet, so will this program and version still be very useful?  Will an older version of CodeXL work?  Reply soon, and thanks for any assistance.

**Comment by kpenujee** [comment]
Hi,
Its a warning and not an error. You can continue installation of CodeXL without this re-distribute from MSFT.
It is used for CPU profiling of .Net/CLR applications.

**Comment by db2ugitthis** [comment]
Thanks for the comment!  However, I would still like to know what are the details of this problem? Also, where do I find a log of details on my PC? What is the solution without warnings? I am not using DirectX 12 or an AMD APU yet, so will this program and version still be very useful? Will an older version of CodeXL work?

**Comment by kpenujee** [comment]
Hi,
In order to generate logfile, you need to run CodeXL installer from command-prompt with "/L*V log_file.txt" string. 

Without the re-distribute, you can still use all the features of CodeXL. 

Using latest version of CodeXL is always advisable as latest version contains new features, enhancements and bug fixes. 

What features of CodeXL are you using?

**Comment by db2ugitthis** [comment]
I was just about to comment that I installed AMD_CodeXL_Win_1.9.10103.exe and received no warnings or errors.  I am not sure what complete set of features I will use, but I will be learning CodeXL.  I like the idea of increased general computing performance (ie floating-point. etc.) with CPU-GPU combination.  I have been using CodeAnalyst for CPU code optimization occasionally for a long time.  I still use it for K10 and earlier architectures.  I really hope AMD wins big with HSA and especially Zen.  Intel needs competition in the enthusiast, high performance, and IPC areas.  I want a current competitive AMD system.  It might be APU or it might be Zen.  My last was Intel and the previous 2 were AMD.  Prior to that was a good mix.  It seems there is an installer bug in this latest CodeXL, which I will need with the new (yet unowned) system.
