### ISSUE TITLE
Cant profile GPU on Ubuntu 

### ISSUE THREAD

**Issue by leemorgan-mobile** [GPUOpen-Tools/CodeXL#57]
Hi 

I have R7 360(with intel CPU) and I'm not seeing any GL GPU profiling data.

I'm using the teapot example that shows CL profiling data but no GL.

Is Ubuntu supported?

PS I've tried with glmark2 with a dialog error of no data available.

Thanks!

**Comment by chesik-amd** [comment]
The GPU Profiler in CodeXL supports only OpenCL, DX11 DirectCompute, and ROCm (HSA).  To profile a frame-based OpenGL application, take a look at GPU PerfStudio (http://developer.amd.com/tools-and-sdks/graphics-development/gpu-perfstudio/)

Chris
