### ISSUE TITLE
Error during kernel debugging

### ISSUE THREAD

**Issue by gbeatty** [GPUOpen-Tools/CodeXL#58]
I have a kernel that gives the very generic error:
"Could not debug kernel. Error during kernel debugging"
 Is there any way to determine why I'm getting this error. Other kernels debug without any problem.

This particular kernel is passing image2d_t (shared from OpenGL) as well as a couple custom structs as arguments if that makes a difference.

CodeXL 2.2
Radeon R9 380
Crimson 16.8.2 drivers

**Comment by bpurnomo** [comment]
Could you share a simple kernel to reproduce the issue?

**Comment by gbeatty** [comment]
Unfortunately I can't. I can't seem to reproduce the problem with simpler kernels. That's why I was hoping that there was some additional debug info i could get as to why this one kernel can't be debugged. Somehing more than informative than "Error during kernel debugging"

**Comment by tobbebex** [comment]
I also got this and finally found that you are not allowed to have any memory objects with CL_MEM_HOST_WRITE_ONLY or CL_MEM_HOST_NO_ACCESS when debugging kernels.
