### ISSUE TITLE
CodeXL 2.2 & Win7 : Installation failure - CXClrProfAgent.dll failed to register

### ISSUE THREAD

**Issue by Scr3amer** [GPUOpen-Tools/CodeXL#61]
Hello everyone,

I hope I didn't do a duplicate, I checked previous issues but we never know. Sorry if it is the case.

I installed the last version of CodeXL 2.2.733 (without Detours) on Windows 10, it works fine.
I tried on Windows 7 Pro x64 and it fails. I tried the Detours version, same issue.

But the legacy version 1.9 works fine. Is it just the fact that CodeXL 2 does not support windows 7 ? Because I didn't see anything related to that in the new features  of the new versions on the blog.

Thanks in advance for any help !

![codexl](https://cloud.githubusercontent.com/assets/9144188/18275760/aac0ea96-7448-11e6-928c-651212480027.png)

**Comment by swarup-sahoo** [comment]
Are you able to complete the installation if you select "Ignore"? Please try and let us know if it works.  Somehow CXLClrProfAgent.dll registration is failing on Windows 7 at your side, which is only needed by CpuProfiler for C# app profiling.

**Comment by Scr3amer** [comment]
Thanks for your help :) !
So I clicked on Ignore and I had afterwards 3 other message boxes. 2 with the same error but different DLL and the last one tells me that we cannot process further the installation.

![err2](https://cloud.githubusercontent.com/assets/9144188/18347602/c3810834-75c6-11e6-89c7-260f8d453896.png)
![err3](https://cloud.githubusercontent.com/assets/9144188/18347601/c3800506-75c6-11e6-8d51-8f3008a4ff94.png)
![err4](https://cloud.githubusercontent.com/assets/9144188/18347603/c381159a-75c6-11e6-9970-4b4fd8290728.png)

**Comment by stremin** [comment]
I had the same issue and was able to resolve it by installing KB2999226.
https://support.microsoft.com/en-us/kb/2999226

Those DLLs have dependencies on new microsoft libraries.
