### ISSUE TITLE
Missing and misplaced OpenCL commands on Timeline

### ISSUE THREAD

**Issue by ex-rzr** [GPUOpen-Tools/CodeXL#62]
Here is a minimal example:
https://gist.github.com/ex-rzr/9f845561c5b38ffc2c2776a34f39d6fb
`gcc bug1.c -o bug1 -lOpenCL`
One device, **multiple** command queues.
CodeXL 2.2.511 (on Linux with Catalyst 15.12).

How it looks in CodeXL:
1. Missing kernel executions
![codexl-missing-command](https://cloud.githubusercontent.com/assets/203967/18427475/2f57b35c-78ea-11e6-8a61-cc9f39ca5eff.png)
2. Misplaced kernel executions
![codexl-misplaced-command](https://cloud.githubusercontent.com/assets/203967/18427965/0ab41cea-78ed-11e6-8af4-2b4eccbe8c89.png)

There are many other places with these issues on the timeline.

CodeXL project:
[bug1.zip](https://github.com/GPUOpen-Tools/CodeXL/files/466736/bug1.zip)
clinfo output:
[clinfo.out.zip](https://github.com/GPUOpen-Tools/CodeXL/files/466738/clinfo.out.zip)

**Comment by chesik-amd** [comment]
Thanks for the concise test case.  We will take a look at this issue.

**Comment by VincentSC** [comment]
Any update on this?

**Comment by VincentSC** [comment]
Any update on this?

**Comment by VincentSC** [comment]
Any update on this? :)

**Comment by tangjie77wd** [comment]
@ex-rzr 
Hello! Where is the ' Application Timeline Trace' ,I can not find it in CodeXL ,just found 'GPU:Performance Counters' in Profile menu.
Another question:
I create projects with OpenCL on linux . My machine : CentOS 7.3+eclipse + AMD Rx560 + amdgpu-pro-17.30-465504 + CodeXL_Linux_x86_64_2.4.60 .

    After I installed all tools above , go into the 'CodeXL_Linux_x86_64_2.4.60' folder and open a terminal ,run the command : ./CodeXL ,then CodeXL gui will appear .
    Click the 'Help' menu and then click 'Load the Teapot Sample' .
    Click the 'Profile' menu and then clike 'GPU:Performance Counters' .
    Press 'F5' on your keyboard and wait for a while.
    Close the 'AMD Teapot Example' gui and wait for a while , you will see many performance indicators in the CodeXL gui.
But I have a question these days : the Teapot sample is provided by CodeXL not myself (It exists in CodeXL as a 'CodeXL Teapot.cxl' file ,so we can load it directly in CodeXL. ) , how can i use CodeXL to test the performance of my own OpenCL projects (.cpp file and .cl file) written in the eclipse ( no .cxl file )? The file 'CodeXL_Quick_Start_Guide.pdf' does not describe any about this.How did you debug yours ?  Any help will be much appriciate !

**Comment by chesik-amd** [comment]
Sorry for not reporting back here sooner.  This issue should be fixed in recent drivers. If you have not already, please upgrade to a recent GPU driver and try the test case again.
