### ISSUE TITLE
CodeXL hangs when trying to profile big apps

### ISSUE THREAD

**Issue by bog-dan-ro** [GPUOpen-Tools/CodeXL#64]
Hi,

I was trying to test CodeXL with a big application (oad) on linux (I'm using codexl_2.2-511_amd64.deb on a debian linux).

CodeXL  hangs (or it take way too much) when I click on "Call graph", is it a know issue?

Let me know if you want to reproduce it and I'll give you all the steps you need.

**Comment by swarup-sahoo** [comment]
Hi,
Call Graph view generation processes huge amount of data in case of big application. This is a known behaviour. In future CodeXL releases we would try to optimize this issue.

If you are not interested in the Call Graph report, then you may disable call Graph which would make the profiling and viewing faster. Go to Profile > Profile Settings > Profile (left bar) > CPU Profile (left bar) > Disable Collect call stack details (right pane). This should disable Call Graph.

Thanks,
Swarup

**Comment by bpurnomo** [comment]
The CPU Profiler has been forked into https://developer.amd.com/amd-uprof/
