### ISSUE TITLE
Vulkan frame analysis doesn't work at all/properly on linux with non AMD video cards

### ISSUE THREAD

**Issue by bog-dan-ro** [GPUOpen-Tools/CodeXL#65]
Hi,

I'm trying to use frame analysis on (debian) linux with some examples from https://github.com/SaschaWillems/Vulkan but it seems it doesn't work. 
Some time it even crashes my X.org server :).
I tried it on  intel and on nvidia video cards (sadly I need to wait until the end of oct. for my radeon rx 480), is it a know issue for non AMD video cards?

P.S. I was trying to debug the problem myself, but I can't compile/build CodeXL on Debian Linux :(

**Comment by callan-amd** [comment]
Our recommended solution from Frame Analysis functionality on Vulkan is now to use RenderDoc.
