### ISSUE TITLE
CodeXL doesn't uses the system libraries

### ISSUE THREAD

**Issue by bog-dan-ro** [GPUOpen-Tools/CodeXL#67]
CodeXL should use system libraries (e.g. qt, boost, sqlite, etc.) where available, instead to use its own prebuilt libs ...

**Comment by bog-dan-ro** [comment]
This is the reason why it fails to compile on debian (check https://paste.kde.org/pzpsmfgsk )

**Comment by callan-amd** [comment]
There is already an option to use the system boost library - it is documented in Build.md.  There is still more work to be done to factor out the other libraries.
