### ISSUE TITLE
GCN ISA assembly output from amdspv.exe is incorrect

### ISSUE THREAD

**Issue by dys129** [GPUOpen-Tools/CodeXL#68]
Testing for a simple shader, taken from vulkan tutorials page:
"#version 450
# extension GL_ARB_separate_shader_objects : enable

layout(location = 0) in vec2 inPosition;
layout(location = 1) in vec3 inColor;

layout(location = 0) out vec3 fragColor;

out gl_PerVertex {
    vec4 gl_Position;
};

void main() {
    gl_Position = vec4(inPosition, 0.0, 1.0);
    fragColor = inColor;
}"

using the same commands as codexl uses, gives:

"shader main
  asic(VI)
  type(VS)

  v_mov_b32     v1, 0                                   // 000000000000: 7E020280
  v_mov_b32     v2, 1.0                                 // 000000000004: 7E0402F2
  **exp           pos0, v0, v0, v1, v2 done               // 000000000008: C40008CF 02010000**
  exp           param0, v2, v2, v2, v2                  // 000000000010: C400020F 02020202
  s_endpgm                                              // 000000000018: BF810000
end"

The output position is incorrect.

**Comment by AmitBM** [comment]
Hi dys129,

You are correct. There is a known issue with the shader input, since amdspv currently does not generate a Fetch shader automatically, and the Analyzer does not enable setting a manual fetch shader. This will be fixed in a future release.

Thanks for reporting this issue.

**Comment by AmitBM** [comment]
Hi dys129,

The Vulkan backend was updated to generate a Fetch shader automatically. Can you please confirm that this has solved your problem?
Please make sure to copy amdspv and spvgen from under .../Common/Lib/AMD/Vulkan/rev_1_0_0/Release to the output directory (place it under the relevant sub-directory on Windows (either x86 or x64), or simply at the CodeXL binaries directory on Linux).

**Comment by dys129** [comment]
Thanks! It now works perfectly.
