### ISSUE TITLE
CodeXL crash after profiling stop

### ISSUE THREAD

**Issue by mirh** [GPUOpen-Tools/CodeXL#69]
What were you doing when the problem happened (optional)?
More precisely at least in TBS after "translating raw profile data"

Operating System:
Win10-64

Call stack:
Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
fnMigrateEBPToDB - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLCpuProfilingTranslation.dll - 0x6586e270 - 0x65850000 - 0x6587c32a
fnMigrateEBPToDB - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLCpuProfilingTranslation.dll - 0x6586e270 - 0x65850000 - 0x65877891
fnWriteSetToFile - N/A - N/A - C:\Program Files (x86)\CodeXL\CXLCpuProfilingTranslation.dll - 0x6586d920 - 0x65850000 - 0x6586db9c
initializeIndependentWidgets - N/A - N/A - c:\program files (x86)\codexl\CXLCpuProfiling.dll - 0x0f6a4ea0 - 0x0f6a0000 - 0x0f6bebb4
QThread::start - N/A - N/A - C:\Program Files (x86)\CodeXL\Qt5Core.dll - 0x663aab60 - 0x66380000 - 0x663aae89
o__CIpow - N/A - N/A - C:\WINDOWS\System32\ucrtbase.dll - 0x77b7d5a0 - 0x77b40000 - 0x77b7d5ee
BaseThreadInitThunk - N/A - N/A - C:\WINDOWS\System32\KERNEL32.DLL - 0x765462a0 - 0x76530000 - 0x765462c3
RtlSubscribeWnfStateChangeNotification - N/A - N/A - C:\WINDOWS\SYSTEM32\ntdll.dll - 0x77e001d0 - 0x77da0000 - 0x77e00608
N/A - N/A - N/A - N/A - N/A - N/A - N/A

System DLL Versions:
- aticfx32.dll: 8.17.10.1484
- aticfx64.dll: 8.17.10.1484
- OpenCL.dll: 21.19.137.1

OpenGL Renderer:
- Renderer Vendor: ATI Technologies Inc.
- Renderer Name: AMD Radeon HD 7700 Series
- Renderer Version: 4.5.14008 Compatibility Profile Context 21.19.137.1
- Renderer Type: Installable client

Device 1 (GPU):
- Platform ID: 1
- Device Type: GPU
- Device Name: Capeverde
- Vendor: Advanced Micro Devices, Inc.

Device 2 (CPU):
- Platform ID: 1
- Device Type: CPU
- Device Name: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
- Vendor: GenuineIntel

Platform 1:
- Vendor: Advanced Micro Devices, Inc.
- Name: AMD Accelerated Parallel Processing
- Profile: FULL_PROFILE
- Version: OpenCL 2.0 AMD-APP (2117.13)

**Comment by swarup-sahoo** [comment]
Hi,
Thanks for reporting the issue. We checked the above Call stack, but it doesn't match with the usecase. Please provide below info which might help in our analysis.

1) Which version of CodeXL is used?
2) What was the exact usecase when this crash occurred? Can you please provide the steps?
3) This Call stack is expected when doing "EBP import" operation. Were you trying to import any EBP file? Can you share the EBP file/folder (if it is ok to share) with us?

Thanks,
Swarup

**Comment by mirh** [comment]
I used latest Windows release, 2.2.733.0. 
I didn't do anything special, really. Just open, then close. 

[This is the program](https://github.com/GPUOpen-Tools/CodeXL/files/493123/GSDumpGUI.zip). Sources are [here](https://github.com/PCSX2/pcsx2/tree/master/tools/GSDumpGUI).

**Comment by bpurnomo** [comment]
The CPU Profiler has been forked into https://developer.amd.com/amd-uprof/
