### ISSUE TITLE
Binary is broken on Linux

### ISSUE THREAD

**Issue by edrickhong** [GPUOpen-Tools/CodeXL#71]
The binary executable for Linux will not run. 

./CodeXL-bin: error while loading shared libraries: libCXLBaseTools.so: cannot open shared object file: No such file or directory

Running grep shows that the file is present.

ls | grep "Base"
libCXLBaseTools.so

I'm just surprised nobody has brought this up yet or maybe I'm just an isolated case. This is on Ubuntu 16.04 . I have tried both the .deb and .tar binaries provided with the same results.

**Comment by AmitBM** [comment]
Hi,
You should either prepend the CodeXL bin directory to the LD_LIBRARY_PATH environment variable and then retry, or, alternatively, you can simply run the "CodeXL" script which should do that for you. This script should be found in the CodeXL bin directory.

**Comment by edrickhong** [comment]
I have tried that and it still crashes. When using the C++ run time provided, it starts to complain about the ABI "/opt/CodeXL_2.2-511/RuntimeLibs/x86_64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicuuc.so.55)" so I'm guessing that the problem now is incompatible ABI's. Suggestions?

**Comment by chesik-amd** [comment]
The current CodeXL release and codebase should work fine on both Ubuntu 16.04 and 18.04
