### ISSUE TITLE
Maybe use MinHook instead of MS Detours ?

### ISSUE THREAD

**Issue by Nucleoprotein** [GPUOpen-Tools/CodeXL#72]
[MinHook](https://github.com/TsudaKageyu/minhook) is more robust than mhooks and is GPL compatible. For my experience works same or even better than MS Detours.

**Comment by callan-amd** [comment]
Thanks for the feedback.  I believe we investigated MinHook when we selected mhooks and for our test cases we found mhooks to be more robust.  However we're always open to alternatives.  The interception functionality is abstracted behind an interface that can be switched easily so it would be relatively straightforward for anyone to implement a MinHook version of this interface.
