### ISSUE TITLE
CodeXL needs OpenGL(ES) backend

### ISSUE THREAD

**Issue by TheMartynBliss** [GPUOpen-Tools/CodeXL#76]
I've seen from other comments that users who are looking for GL(ES) API support are being pointed towards GPUPerf Studio however this is not an open source application.

It would be very useful if GL had equivalent support to Vulkan (in CodeXL) - can anyone from AMD comment on the likelihood of this being added?

Thanks,
Martyn

**Comment by callan-amd** [comment]
AMD has no plans at the moment to add GL(ES) support to CodeXL.
