### ISSUE TITLE
Question: Can I use CodeXL with Mesa open source drivers?

### ISSUE THREAD

**Issue by sandy-8925** [GPUOpen-Tools/CodeXL#77]
Can I use CodeXL to profile an app's/game's OpenGL operations on Linux, with the AMD Mesa open source drivers? Or will this work on the Catalyst driver only?

**Comment by gerboland** [comment]
I've just tried CodeXL on my Ubuntu machine with a 4.9 kernel using the Radeon open source driver and MESA. CodeXL reports that an "AMD GPU was not detected. Local GPU Profiling will be disabled" and also "AMD Radeon software was not detected. Static Analysis will be disabled".

So I think the answer is no.

I plan to try the open source amdgpu with MESA next, but my GPU has experimental support so I may not have luck there either! Let's see

**Comment by eloraiby** [comment]
I have a similar issue, stating my GPU is not supported! any updates ?
