### ISSUE TITLE
Debian path (debain/main)

### ISSUE THREAD

**Issue by reanimastudios** [GPUOpen-Tools/CodeXL#8]
Is there an inside joke I'm missing with **debain**/main under the Installer-Linux path?

I'm only assuming you meant, debian/main.

The build scripts for general Debian package management via debmake will probably not work. Then again I'm not seeing any standard debian/rules work flow.

**Comment by giladyarnitzky** [comment]
This will be fixed but it will take time to validate this. Thank you for reporting this.

**Comment by doronofek** [comment]
Fixed in master branch.
