### ISSUE TITLE
CodeXL debuging problem 

### ISSUE THREAD

**Issue by ghost** [GPUOpen-Tools/CodeXL#80]
Hello. I buy Radeon RX 480 8 Gb and try to crate OpenCL program for my Course work. I wont to debug my OpenCL code. I use VS 2015 Community, Windows 10 (64 bit) and latest driver for my RX 480 (16.10.1). When I try debug kernel code in CodeXL (by making breakpoints in kernel code) I get error message: "Could not debug kernel Error during kernel debugging". [SCREEN](https://community.amd.com/servlet/JiveServlet/showImage/2-2755700-112332/123.png)
In VS 2015 debug also not work (when I click "Start debug" my program execute and close). What I should do for debug my OpenCL code? 
p.s: sorry for my English :)

**Comment by tobbebex** [comment]
I also got this and finally found that you are not allowed to have any memory objects with CL_MEM_HOST_WRITE_ONLY or CL_MEM_HOST_NO_ACCESS when debugging kernels.

**Comment by tangjie77wd** [comment]
@tobbebex 
Hello!I create projects with OpenCL on linux . My machine : CentOS 7.3+eclipse + AMD Rx560 + amdgpu-pro-17.30-465504 + CodeXL_Linux_x86_64_2.4.60 .

    After I installed all tools above , go into the 'CodeXL_Linux_x86_64_2.4.60' folder and open a terminal ,run the command : ./CodeXL ,then CodeXL gui will appear .
    Click the 'Help' menu and then click 'Load the Teapot Sample' .
    Click the 'Profile' menu and then clike 'GPU:Performance Counters' .
    Press 'F5' on your keyboard and wait for a while.
    Close the 'AMD Teapot Example' gui and wait for a while , you will see many performance indicators in the CodeXL gui.
But I have a question these days : the Teapot sample is provided by CodeXL not myself (It exists in CodeXL as a 'CodeXL Teapot.cxl' file ,so we can load it directly in CodeXL. ) , how can i use CodeXL to test the performance of my own OpenCL projects (.cpp file and .cl file) written in the eclipse ( no .cxl file )? Any help will be much appriciate !

**Comment by bpurnomo** [comment]
It seems that the original question has been answered.
