### ISSUE TITLE
GPU profiling using CodeXL remote agent

### ISSUE THREAD

**Issue by aarshad** [GPUOpen-Tools/CodeXL#81]
Hello,

We are currently trying to collect the GPU profiling data from an AMD board equipped with AMD Embedded G-Series GX-217GI Radeon R6E.
We are able to cross compile an run codeXL remote agent on it.
Our complete setup involves one host machine Running CodeXL and one AMD target machine Running CodeXL remote agent.
Till now we are successfully able to debug the Teapot example using this setup, but not able to successfully collect the GPU profiling data yet.

When we start the profiling session although it does get started but when we terminate the Teapot program we receive the debug messages on remote agent side that it fails to generate the profile results.

root@amdfalconx86:~# /media/sdb6/Output_x86_64/release/bin/CodeXLRemoteAgent
/media/sdb6/Output_x86_64/release/bin/CodeXLRemoteAgent

---
## CodeXL Remote Agent settings were extracted successfully

Agent version is: 2.3.0.0
Read  timeout is: Infinite Timeout
Write timeout is: Infinite Timeout
Agent IP:Port is: 137.202.156.241:27015

---

CodeXL Remote Agent is listening on 137.202.156.241:27015

Press any key to terminate CodeXL Remote Agent. . .

**\* Connection: Received a connection from 137.202.157.168:13726 ***
libCXLGpuProfilerHSAProfileAgent.so is missing
Make sure you have libCXLGpuProfilerHSAProfileAgent.so under /media/sdb6/Output_x86_64/release/bin/
XRequest.152: BadMatch (invalid parameter attributes) 0x1400006
.
.
.
Failed to generate profile result /home/root/.CodeXL/AMD/CodeXL/CXLTeaPot-bin@137.202.156.241_ProfilerOutput/Oct-20-2016_16-40@137.202.156.241_1/Oct-20-2016_16-40@137.202.156.241_1.occupancy.
Failed to generate profile result /home/root/.CodeXL/AMD/CodeXL/CXLTeaPot-bin@137.202.156.241_ProfilerOutput/Oct-20-2016_16-40@137.202.156.241_1/Oct-20-2016_16-40@137.202.156.241_1.csv.
## **\* Disconnection: 137.202.157.168:13726ended a session and disconnected ***

And on host side we receive the following message.
"
Unable to gather profile data. This error can occur for one of several reasons:
The active project is not an HSA program.
The active project is an OpenCL program, but it did not enqueue any kernels.
The active project is a DirectCompute program, but you are not running as administrator. Administrator rights are required when profiling DirectCompute applications.
The active project is an OpenCL program, but it did not enqueue any kernels listed in the Profile Specific Kernels section.
The active project does not compile or run properly (try running it manually).
Either the profile output directory or the target executable do not exist on the remote machine.
The remote agent does not have write access to the profile output directory on the remote machine.
"

Our first question is that will we receive any profiling data if hsa/rocm and opencl both are not available on the target side, whereas openGL/vulkan is available on target.
Are we missing some components on the target side ?

**Comment by chesik-amd** [comment]
Hi,

The GPU Profiler in CodeXL only supports collecting performance counters for ROCm, OpenCL and DirectCompute applications.  If you want to collect performance counter data for OpenGL applications, you should be able to use GPUPerfStudio for that.  We don't yet have a solution available for collecting performance counters for Vulkan applications.  The Frame Analysis component in CodeXL supports Vulkan, but it does not have support for collecting performance counter data.

Chris

**Comment by aarshad** [comment]
Hi Chris,

Thank you for these details. So that means we will not be able to see any profile results if we do not have opencl or rocm installed on our target machine... correct ?
My expectation was that though it will generate the profile data/results but an empty one but instead it says that it failed to generate the profile results that creates doubt of some error.

I tried running the CodeXLGpuProfiler tool directly and it also resulted in the same behavior.

root@amdfalconx86:~# /media/sdb6/Output_x86_64/release/bin/CodeXLGpuProfiler -o /media/sdb6/Output_x86_64/release/bin/gpuprofdata -t -w /media/sdb6/Output_x86_64/release/bin/examples/Teapot/release/ /media/sdb6/
Output_x86_64/release/bin/examples/Teapot/release/CXLTeaPot-bin --device gpu
XRequest.152: BadMatch (invalid parameter attributes) 0x1400006
Failed to generate profile result /media/sdb6/Output_x86_64/release/bin/gpuprofdata.atp.
root@amdfalconx86:~#

**Comment by chesik-amd** [comment]
If the application you are profiling does not use OpenCL or ROCm (or DirectCompute on Windows), then the profiler will not generate results.

Normally, the teapot sample uses OpenCL, but if you don't have an OpenCL implementation on the target machine, then I think the sample will fall back to a non-OpenCL CPU-implementation rather than using OpenCL on the GPU.

Chris

**Comment by aarshad** [comment]
Thank you Chris for the further confirmation.
 
Yes Chris, you are right the teapot sample application fall back to teapot revolve only and its portion that simulates the smoke based on openCL is disabled.
