### ISSUE TITLE
could not debug kernel

### ISSUE THREAD

**Issue by yunpengzhu** [GPUOpen-Tools/CodeXL#82]
I install the codexl 2.2.733 in windows8.
It fails to debug the opencl kernel.
The message is that "Could not debug kernel. The kernel is not debuggable.
Please create the program with clcreateprogramwithsource and clbuildprogram".

The kernel is created with these 2 opencl API.
What's the problem?

**Comment by ItalyToast** [comment]
This happens for me too.
I'm using: 
-codexl 2.2.733.
-Radeon Software Version: 16.12.2
-Windows 7 SP1 64bit
-C# with Cloo.net bindings
-GPU R9 390
-driver version: 21.19.407.0WHQL (Crimson 16.12.2)

[Image of the Error](https://gyazo.com/217b14ba58d630c8b7560c8449fa65bc)

Fixed it now:
This error is caused by using #include "insertfilename.cl" on a file that have a Byte Order Mark

**Comment by reger-men** [comment]
I had the same problem. 
Apparently CodeXL does not work well with ROCm. If you use ROCm you have to boot linux with generic kernel `(uname -r to check that)`.

**Comment by tangjie77wd** [comment]
@yunpengzhu @ItalyToast @reger-men 
Hello!I create projects with OpenCL on linux . My machine : CentOS 7.3+eclipse + AMD Rx560 + amdgpu-pro-17.30-465504 + CodeXL_Linux_x86_64_2.4.60 .

1.    After I installed all tools above , go into the 'CodeXL_Linux_x86_64_2.4.60' folder and open a terminal ,run the command : ./CodeXL ,then CodeXL gui will appear .
2.    Click the 'Help' menu and then click 'Load the Teapot Sample' .
3.    Click the 'Profile' menu and then clike 'GPU:Performance Counters' .
4.    Press 'F5' on your keyboard and wait for a while.
5.    Close the 'AMD Teapot Example' gui and wait for a while , you will see many performance indicators in the CodeXL gui.
But I have a question these days : the Teapot sample is provided by CodeXL not myself (It exists in CodeXL as a 'CodeXL Teapot.cxl' file ,so we can load it directly in CodeXL. ) , how can i use CodeXL to test the performance of my own OpenCL projects (.cpp file and .cl file) written in the eclipse ( no .cxl file )? Any help will be much appriciate !

**Comment by bpurnomo** [comment]
It seems that the original question has been answered.
