### ISSUE TITLE
Visual Studio extension breaks the window functionality of Visual Studio.

### ISSUE THREAD

**Issue by yusuf-gunaydin** [GPUOpen-Tools/CodeXL#83]
When you install the extension, it closes all the windows such as "Solution Explorer", "Team Explorer", "Output", "Error List", etc.
Some of these windows cannot be opened ever after. Enabling a window from view menu does nothing.

**Comment by russdirks** [comment]
I can confirm this issue.  Thanks a lot CodeXL.  You've COMPLETELY SCREWED UP MY VS2015 INSTALLATION!!!

**Comment by kpenujee** [comment]
Hi,
Can you please provide more details like:
- VS15 Update1 installed?
- VS15 Professional or Enterprise or Professional with MSDN?
- What application language are you using (C, C++, C#..)?


Thanks,
Kalyan P

**Comment by russdirks** [comment]
VS2015 Community Edition, Update 3
C++

Further symptom description:
- After installing the extension, I opened a C++ project I had been working on.  
- All source files were closed, all VS windows (Solution Explorer, Properties, etc,) were closed.  
- Only the CodeXL window was open.
- I opened Solution Explorer to try to open up some of my source files.  Some of them would open, some wouldn't

**Comment by neilDGD** [comment]
Hi,

Encountered problems with 2015 Update 3 too.

When CodeXL visual studio integration installed, Visual studio launch from Unity failed with "the application cannot start", also rmb on visual studio tab then select a past project/solution and it gave the same message.  Could only start visual studio and load manually.

had to uninstall the vs integration.

**Comment by callan-amd** [comment]
The Visual Studio plugin functionality has been deprecated. Future builds of CodeXL will be standalone only
