### ISSUE TITLE
GPU profile counters mode not working

### ISSUE THREAD

**Issue by boxerab** [GPUOpen-Tools/CodeXL#85]
When I try to profile my application, it hangs. Works better with timeline tracing.

I use a lot of user events in my code, by the way.

**Comment by chesik-amd** [comment]
Hi,

If we recognize a dispatch that is dependent on a user event, we will not try to profile it.  However, it seems something else is going on here if you are seeing your application hanging when trying to profile it.  

Would you be able to share your application so that we can debug the issue?

Thanks,
Chris

**Comment by boxerab** [comment]
Thanks. If I send you a binary, would you still be able to debug ?

**Comment by chesik-amd** [comment]
Yes, a binary should be fine

**Comment by boxerab** [comment]
Thanks,  When I create a binary, I compile my OpenCL kernels, and follow these steps to strip the 
.source
.llvmir
.amdil

from the ELF files:

http://developer.amd.com/knowledge-base/?ID=115

Can you recommend anything else I should do to protect the kernel binaries ?

**Comment by boxerab** [comment]
@chesik-amd I am getting my binary ready - what is the best way of getting this to you directly?  Thanks!

**Comment by boxerab** [comment]
anyways..... I am not sure why, but everything is working fine now, after a few more weeks of kernel development.  I didn't update CodeXL , but it now is happy with my kernels, even though I am heavily using user events.

**Comment by boxerab** [comment]
Woops, my bad, still hanging. :(

**Comment by boxerab** [comment]
Well, fortunately I am able to profile my kernel without user events. Are there plans to support profiling of kernels with user events, in the future ?
