### ISSUE TITLE
CodeXL Crash when Debugging + Error reporting failed

### ISSUE THREAD

**Issue by robinchrist** [GPUOpen-Tools/CodeXL#86]
What were you doing when the problem happened (optional)?
Opened CodeXL, Opened Teapot Example, built it / Let CodeXL Debug it -> Crash

Operating System:
Win10-64

Call stack:
Function name - File path - Line number - Module path - Function Start address - Module Start address - Instruction counter address
N/A - N/A - N/A - N/A - N/A - N/A - 0x0cbc5a67
aclLoader_OnUnload - N/A - N/A - C:\Program Files (x86)\AMD APP SDK\3.0\bin\x86\amdocl12cl.dll - 0x0aec5b40 - 0x0aec0000 - 0x0aecb3aa
aclLoader_OnUnload - N/A - N/A - C:\Program Files (x86)\AMD APP SDK\3.0\bin\x86\amdocl12cl.dll - 0x0aec5b40 - 0x0aec0000 - 0x0aece3ae
aclLoader_OnUnload - N/A - N/A - C:\Program Files (x86)\AMD APP SDK\3.0\bin\x86\amdocl12cl.dll - 0x0aec5b40 - 0x0aec0000 - 0x0aeca5f3
aclLoader_OnUnload - N/A - N/A - C:\Program Files (x86)\AMD APP SDK\3.0\bin\x86\amdocl12cl.dll - 0x0aec5b40 - 0x0aec0000 - 0x0aee65a1
aclInsertSection - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\c0308000.inf_amd64_ec35706f0b87e751\amdocl.dll - 0x57b78990 - 0x578e0000 - 0x57b789f5
clSetKernelExecInfo - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\c0308000.inf_amd64_ec35706f0b87e751\amdocl.dll - 0x57b16930 - 0x578e0000 - 0x57b35867
clSetKernelExecInfo - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\c0308000.inf_amd64_ec35706f0b87e751\amdocl.dll - 0x57b16930 - 0x578e0000 - 0x57b20516
clSetKernelExecInfo - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\c0308000.inf_amd64_ec35706f0b87e751\amdocl.dll - 0x57b16930 - 0x578e0000 - 0x57b2c195
clBuildProgram - N/A - N/A - C:\Windows\System32\DriverStore\FileRepository\c0308000.inf_amd64_ec35706f0b87e751\amdocl.dll - 0x57b12b20 - 0x578e0000 - 0x57b12c1d
clBuildProgram - c:\jenkins\workspace\codexl-2.2\codexl\components\gpudebugging\amdtopenclserver\src\csopenclwrappers.cpp - 1515 - d:\codexl\spies\OpenCL.dll - 0x0f8b2840 - 0x0f880000 - 0x0f8b2a35
AMDTTeapotOCLSmokeSystem::createOpenCLKernelProgramResource - c:\users\public\documents\codexl\examples\teapot\amdtteapotlib\src\amdtteapotoclsmokesystem.cpp - 3769 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x011c2e60 - 0x011b0000 - 0x011c318a
AMDTTeapotOCLSmokeSystem::createOpenCLResources - c:\users\public\documents\codexl\examples\teapot\amdtteapotlib\src\amdtteapotoclsmokesystem.cpp - 1383 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x011be850 - 0x011b0000 - 0x011be89c
AMDTTeapotOCLSmokeSystem::draw - c:\users\public\documents\codexl\examples\teapot\amdtteapotlib\src\amdtteapotoclsmokesystem.cpp - 1661 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x011becc0 - 0x011b0000 - 0x011bee9d
AMDTTeapotOGLCanvas::paintWindow - c:\users\public\documents\codexl\examples\teapot\amdtteapotlib\src\amdtteapotoglcanvas.cpp - 434 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x011b6ac0 - 0x011b0000 - 0x011b6b77
AMDTTeapotOGLCanvas::onPaint - c:\users\public\documents\codexl\examples\teapot\amdtteapotlib\src\amdtteapotoglcanvas.cpp - 160 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x011b64d0 - 0x011b0000 - 0x011b64de
MainWin::onPaint - c:\users\public\documents\codexl\examples\teapot\amdtteapot\src\amdtmainwin.cpp - 146 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x011b1690 - 0x011b0000 - 0x011b16a8
WndProc - c:\users\public\documents\codexl\examples\teapot\amdtteapot\amdtteapot.cpp - 508 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x011b33b0 - 0x011b0000 - 0x011b399f
SetManipulationInputTarget - N/A - N/A - C:\Windows\System32\USER32.dll - 0x774ed260 - 0x774c0000 - 0x774ed2b2
DispatchMessageW - N/A - N/A - C:\Windows\System32\USER32.dll - 0x774cdf90 - 0x774c0000 - 0x774ce889
DispatchMessageW - N/A - N/A - C:\Windows\System32\USER32.dll - 0x774cdf90 - 0x774c0000 - 0x774ce4bf
MsgWaitForMultipleObjectsEx - N/A - N/A - C:\Windows\System32\USER32.dll - 0x774d8800 - 0x774c0000 - 0x774d8b08
KiUserCallbackDispatcher - N/A - N/A - C:\Windows\SYSTEM32\ntdll.dll - 0x77adffd0 - 0x77a70000 - 0x77ae0005
DispatchMessageW - N/A - N/A - C:\Windows\System32\USER32.dll - 0x774cdf90 - 0x774c0000 - 0x774cdf9f
wWinMain - c:\users\public\documents\codexl\examples\teapot\amdtteapot\amdtteapot.cpp - 325 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x011b2b00 - 0x011b0000 - 0x011b3275
__scrt_common_main_seh - f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl - 253 - C:\Users\Public\Documents\CodeXL\examples\Teapot\Release\CXLTeaPot.exe - 0x011c62cf - 0x011b0000 - 0x011c63c4
BaseThreadInitThunk - N/A - N/A - C:\Windows\System32\KERNEL32.DLL - 0x761062a0 - 0x760f0000 - 0x761062c3
RtlSubscribeWnfStateChangeNotification - N/A - N/A - C:\Windows\SYSTEM32\ntdll.dll - 0x77ad02e0 - 0x77a70000 - 0x77ad0718
N/A - N/A - N/A - N/A - N/A - N/A - N/A

System DLL Versions:
 - aticfx32.dll: 8.17.10.1484
 - aticfx64.dll: 8.17.10.1484
 - OpenCL.dll: 21.19.155.4

OpenGL Renderer:
 - Renderer Vendor: ATI Technologies Inc.
 - Renderer Name: AMD Radeon (TM) R9 390 Series
 - Renderer Version: 4.5.13456 Compatibility Profile Context 21.19.155.4
 - Renderer Type: Installable client

Device 1 (GPU):
 - Platform ID: 1
 - Device Type: GPU
 - Device Name: Hawaii
 - Vendor: Advanced Micro Devices, Inc.

Device 2 (CPU):
 - Platform ID: 1
 - Device Type: CPU
 - Device Name: AMD Phenom(tm) II X4 840 Processor
 - Vendor: AuthenticAMD

Platform 1:
 - Vendor: Advanced Micro Devices, Inc.
 - Name: AMD Accelerated Parallel Processing
 - Profile: FULL_PROFILE
 - Version: OpenCL 2.0 AMD-APP (2117.14)

Additional Information:
- OpenCL Engine loaded:Yes
- OpenGL Engine loaded:Yes
- Kernel Debugging Entered:No

Running the Binary without Debugging WORKS!

**Comment by unaplugin** [comment]
Same error. Have you solve it? @robinchrist
