### ISSUE TITLE
CodeXL does not find or ask for the source code and takes me to assembly

### ISSUE THREAD

**Issue by alphastint** [GPUOpen-Tools/CodeXL#87]
When I try to find the hotspot after profiling, CodeXL complains, that it could not find the source code and takes me directly to binary. If I run the teapot example, then CodeXL asks me for the source file. So far so good, and you would say I needed to compile the project in debug mode, but there is a catch:
if I recompile the teapot example with 
`BUILD=debug make all`
The behavior is the same: 
`The source file was not found. Cannot annotate source. Only disassembly will be available.`
It appears to be an issue with the compiler. Is there a specific version CodeXL supports (I use gcc 4.8.5)? The only indication that I have found was in the header file:
`readelf --debug-dump=info CXLTeaPot-bin | head -n 30`
gives me 
`DW_AT_name        : ../sysdeps/x86_64/start.S` for the broken file
and
`<11>   DW_AT_name        : (indirect string, offset: 0x1044): Examples/AMDTTeaPot/AMDTTeaPot/src/Teapot.cpp` for the correct one. 

I would also like to mention that gdb and kdbg have no problem finding the source files.

Does anyone know how to solve this issue?

**Comment by dhiahassen** [comment]
Any reply !!

**Comment by tangjie77wd** [comment]
@dhiahassen 
I create projects with OpenCL on linux . My machine : CentOS 7.3+eclipse + AMD Rx560 + amdgpu-pro-17.30-465504 + CodeXL_Linux_x86_64_2.4.60 .

    After I installed all tools above , go into the 'CodeXL_Linux_x86_64_2.4.60' folder and open a terminal ,run the command : ./CodeXL ,then CodeXL gui will appear .
    Click the 'Help' menu and then click 'Load the Teapot Sample' .
    Click the 'Profile' menu and then clike 'GPU:Performance Counters' .
    Press 'F5' on your keyboard and wait for a while.
    Close the 'AMD Teapot Example' gui and wait for a while , you will see many performance indicators in the CodeXL gui.
But I have a question these days : the Teapot sample is provided by CodeXL not myself (It exists in CodeXL as a 'CodeXL Teapot.cxl' file ,so we can load it directly in CodeXL. ) , how can i use CodeXL to test the performance of my own OpenCL projects (.cpp file and .cl file) written in the eclipse ( no .cxl file )? The file 'CodeXL_Quick_Start_Guide.pdf' does not describe any about this. Any help will be much appriciate !

**Comment by dhiahassen** [comment]
@tangjie77wd  These guys never answer , still need help for source !

**Comment by swarupsahoo** [comment]
If you are using CodeXL CpuProfiler, then the CpuProfiler tool has been forked into another tool - "AMD uProf" (https://developer.amd.com/amd-uprof/). You can give a try to uProf CpuProfiler if that is what you are looking for.
