### ISSUE TITLE
Breaks editor windows in MSVC 2015

### ISSUE THREAD

**Issue by gcp** [GPUOpen-Tools/CodeXL#9]
The MSVC 2015 extension seems to break MSVC's ability to show editor windows with source code. This pretty much makes MSVC unusable so I had to uninstall immediately.

It also changes the default layout so the CodeXL view comes up by default (instead of the solution view).

**Comment by jdahl** [comment]
I have the same issue. Tried to restore old settings to see if that fixed it but it didn't help. The only way was to uninstall.

**Comment by glcoder** [comment]
Same issue here, after installing CodeXL plugin VS2015 looks like https://i.imgur.com/Qbj0vOA.png and nothing helps but plugin uninstall.

**Comment by giladyarnitzky** [comment]
Thank you for the report. Can you please provide so additional information to help us fix this bug?
Which update of VS15 are you using?
Can you please send us the CodeXL log file after trying to open a source file? The log file is at %temp% folder and is named CodeXL-username.log.
Can you also provide the extensions for the files that are failing?

**Comment by giladyarnitzky** [comment]
A fix for CodeXL view so it will no longer be default view was submitted. As for the Editor break down we are still looking into it

**Comment by gcp** [comment]
This was MSVC2015 Update 2. I'll try and get that log for you.

**Comment by lukeforeman** [comment]
I had this issue after installing over CodeXL 1.9. Uninstalling then installing 2.0 again fixed it for me

**Comment by callan-amd** [comment]
Support for the VS extension has been deprecated. Only the standalone version of CodeXL will be supported in future.
