### ISSUE TITLE
Codexl crash in Ubuntu with Rx480

### ISSUE THREAD

**Issue by Ethan999** [GPUOpen-Tools/CodeXL#91]
I install the CodeXL  in ubuntu 16.04, but when I open it, it crash.

[_opt_CodeXL_2.1-228_CodeXL-bin.1000.crash.tar.gz](https://github.com/GPUOpen-Tools/CodeXL/files/626195/_opt_CodeXL_2.1-228_CodeXL-bin.1000.crash.tar.gz)

**Comment by chesik-amd** [comment]
CodeXL is working fine on Ubuntu 16.04 now.  Please reopen if this issue is still seen
