### ISSUE TITLE
CodeXL 2.2 fails to start on Linux Mint 18.2 (Unbuntu 16.04 based) with AMD RX480

### ISSUE THREAD

**Issue by mapaton** [GPUOpen-Tools/CodeXL#92]
I do believe I have the amdgpu-pro driver installed and running but when I try and run CodeXL I get:

user@neptune ~/Downloads $ /opt/CodeXL_2.2-511/CodeXL
/opt/CodeXL_2.2-511/CodeXL
libGL error: pci id for fd 12: 1002:67df, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
libGL error: pci id for fd 12: 1002:67df, driver (null)
/opt/CodeXL_2.2-511/CodeXL: line 69:  5614 Segmentation fault      /opt/CodeXL_2.2-511/CodeXL-bin

----

Running: 
user@neptune ~/Downloads $ glxheads 
glxheads: exercise multiple GLX connections (any key = exit)
Usage:
  glxheads xdisplayname ...
Example:
  glxheads :0 mars:0 venus:1
Name: :0
  Display:     0x257e420
  Window:      0x2a00002
  Context:     0x258f280
  GL_VERSION:  4.5.13453 Compatibility Profile Context 16.40.5
  GL_VENDOR:   ATI Technologies Inc.
  GL_RENDERER: AMD Radeon (TM) RX 480 Graphics

Runs fine as do some other OpenGL based applications I have tried.

Any suggestions what I might try next? Might this be a problem with the application or do you think it is just my setup. Let me know if I can provide any additional information.

Talk to you later,
     Mark

**Comment by PROteinBY** [comment]
Nobody help you. I also have RX 480 and kubuntu 16.10, it can't work. On windows 10 also debugger not work

**Comment by mapaton** [comment]
No, your's is the first reply I have seen. I'm not sure how actively this site is monitored/read though. I have been doing some googling around but no luck yet. Kind of sad because I'd read hoped I could try out CodeXL as it seemed promising.

**Comment by PROteinBY** [comment]
When i use kubuntu 16.04, codexl work fine. But on 16.10 it say "AMD GPU not detected"...

**Comment by callan-amd** [comment]
Can you provide more information on the OS, Driver and hardware combination you are using?  I had the QA team at AMD run a quick test - here is their feedback

Linux Mint-18-cinnamon-64bit OS:
-        Installed amd gpu-pro driver from http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%E2%80%93Release-Notes.aspx
-        Installed CodeXL 2.2 DEB released version
-        Was able to run CodeXL as well as “glxheads” command
 
Linux Mint-18-KDE 64bit OS:
-        Installing AMD GPU Pro Driver throws “Unsupported OS” and exits

**Comment by mapaton** [comment]
callan-amd, thanks for looking into this issue. I will send detailed information a bit later when I'm in front of the machine. Here are the basics though: A Skylake 6700K CPU, SSD, AMD RX 480 graphics card. I was using an NVidia card in it before switching to the AMD one then installed the gpu-pro drives and codeXL as you described above. This is just an experimental machine so I could also try re-installing from scratch if that would help.

**Comment by mapaton** [comment]
Here is a bunch more information: Let me know if you want anything else otherwise I'll probably try a clean install and see if I have better luck. Thanks for your efforts.
   - Mark

----

OS:  Linux Mint Cinnamon-64bit version 18
uname -a:
   Linux neptune 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

lspci info:
00:00.0 Host bridge: Intel Corporation Sky Lake Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation Sky Lake PCIe Controller (x16) (rev 07)
00:14.0 USB controller: Intel Corporation Sunrise Point-H USB 3.0 xHCI Controller (rev 31)
00:16.0 Communication controller: Intel Corporation Sunrise Point-H CSME HECI #1 (rev 31)
00:17.0 SATA controller: Intel Corporation Sunrise Point-H SATA controller [AHCI mode] (rev 31)
00:1b.0 PCI bridge: Intel Corporation Sunrise Point-H PCI Root Port #17 (rev f1)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #1 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #9 (rev f1)
00:1d.1 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #10 (rev f1)
00:1d.2 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #11 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point-H LPC Controller (rev 31)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-H PMC (rev 31)
00:1f.3 Audio device: Intel Corporation Sunrise Point-H HD Audio (rev 31)
00:1f.4 SMBus: Intel Corporation Sunrise Point-H SMBus (rev 31)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (2) I219-V (rev 31)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 67df (rev c7)
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device aaf0
05:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
06:00.0 USB controller: ASMedia Technology Inc. ASM1142 USB 3.1 Host Controller


$ lspci | grep VGA ; lsmod | grep "kms\|drm" ; find /dev -group video ; \
> cat /proc/cmdline ; find /etc/modprobe.d/; cat /etc/modprobe.d/*kms* ; \
> ls /etc/X11/xorg.conf ; glxinfo | grep -i "vendor\|rendering" ; \
> grep LoadModule /var/log/Xorg.0.log
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 67df (rev c7)
drm_kms_helper        155648  2 i915_bpo,amdgpu
drm                   364544  10 ttm,i915_bpo,drm_kms_helper,amdgpu
fb_sys_fops            16384  1 drm_kms_helper
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
/dev/fb0
/dev/dri/card0
/dev/dri/renderD128
/dev/dri/controlD64
BOOT_IMAGE=/boot/vmlinuz-4.4.0-51-generic root=UUID=44b13e4e-ef07-4102-a4bd-bd513dc09469 ro quiet splash vt.handoff=7
/etc/modprobe.d/
/etc/modprobe.d/blacklist-watchdog.conf
/etc/modprobe.d/mlx4.conf
/etc/modprobe.d/dkms.conf
/etc/modprobe.d/blacklist.conf
/etc/modprobe.d/iwlwifi.conf
/etc/modprobe.d/blacklist-rare-network.conf
/etc/modprobe.d/blacklist-oss.conf
/etc/modprobe.d/fbdev-blacklist.conf
/etc/modprobe.d/blacklist-firewire.conf
/etc/modprobe.d/blacklist-modem.conf
/etc/modprobe.d/alsa-base.conf
/etc/modprobe.d/blacklist-ath_pci.conf
/etc/modprobe.d/blacklist-framebuffer.conf
/etc/modprobe.d/vmwgfx-fbdev.conf
/etc/modprobe.d/blacklist-radeon.conf
# modprobe information used for DKMS modules
#
# This is a stub file, should be edited when needed,
# used by default by DKMS.
ls: cannot access '/etc/X11/xorg.conf': No such file or directory
direct rendering: Yes
server glx vendor string: AMD
client glx vendor string: AMD
OpenGL vendor string: Advanced Micro Devices, Inc.
[     4.343] (II) LoadModule: "glx"
[     4.349] (II) LoadModule: "amdgpu"
[     4.350] (II) LoadModule: "ati"
[     4.350] (II) LoadModule: "radeon"
[     4.351] (II) LoadModule: "modesetting"
[     4.351] (II) LoadModule: "fbdev"
[     4.352] (II) LoadModule: "vesa"
[     4.371] (II) LoadModule: "fbdevhw"
[     4.371] (II) LoadModule: "fb"
[     4.371] (II) LoadModule: "dri2"
[     4.375] (II) LoadModule: "glamoregl"
[     4.562] (II) LoadModule: "ramdac"
[     4.646] (II) LoadModule: "evdev"

more xdpyinfo.txt 
name of display:    :0
version number:    11.0
vendor string:    The X.Org Foundation
vendor release number:    11803000
X.Org version: 1.18.3
maximum request size:  16777212 bytes
motion buffer size:  256
bitmap unit, bit order, padding:    32, LSBFirst, 32
image byte order:    LSBFirst
number of supported pixmap formats:    7
supported pixmap formats:
    depth 1, bits_per_pixel 1, scanline_pad 32
    depth 4, bits_per_pixel 8, scanline_pad 32
    depth 8, bits_per_pixel 8, scanline_pad 32
    depth 15, bits_per_pixel 16, scanline_pad 32
    depth 16, bits_per_pixel 16, scanline_pad 32
    depth 24, bits_per_pixel 32, scanline_pad 32
    depth 32, bits_per_pixel 32, scanline_pad 32
keycode range:    minimum 8, maximum 255
focus:  window 0x3400007, revert to Parent
number of extensions:    29
    BIG-REQUESTS
    Composite
    DAMAGE
    DOUBLE-BUFFER
    DPMS
    DRI2
    DRI3
    GLX
    Generic Event Extension
    MIT-SCREEN-SAVER
    MIT-SHM
    Present
    RANDR
    RECORD
    RENDER
    SECURITY
    SGI-GLX
    SHAPE
    SYNC
    X-Resource
    XC-MISC
    XFIXES
    XFree86-DGA
    XFree86-VidModeExtension
    XINERAMA
    XInputExtension
    XKEYBOARD
    XTEST
    XVideo
default screen number:    0
number of screens:    1

screen #0:
  dimensions:    3840x2160 pixels (1016x571 millimeters)
  resolution:    96x96 dots per inch
  depths (7):    24, 1, 4, 8, 15, 16, 32
  root window id:    0x15b
  depth of root window:    24 planes
  number of colormaps:    minimum 1, maximum 1
  default colormap:    0x20
  default number of colormap cells:    256
  preallocated pixels:    black 0, white 16777215
  options:    backing-store WHEN MAPPED, save-unders NO
  largest cursor:    128x128
... and lots more.

**Comment by smheidrich** [comment]
I'm getting the exact same issue with an RX 470 on Ubuntu 16.04 (which I installed specifically because it was supported by the AMDGPU-PRO driver).

Installing the AMDGPU-PRO driver as well as CodeXL worked just fine, running glxheads tells me that it ran fine via the RX 470 as well and I've been doing OpenCL calculations on this system without any problems as well. The only thing that doesn't work is starting CodeXL, because apparently it can't find a driver (weird considering that everything else I'd need a driver for works fine).

Please help me fix this, AMD. I'm running a supported OS so this really should work.

I don't know which information you need, here is some random stuff:
````
$ sudo lshw -c video
  *-display
       description: VGA compatible controller
       product: Advanced Micro Devices, Inc. [AMD/ATI]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: cf
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:29 memory:e0000000-efffffff memory:f0000000-f01fffff ioport:e000(size=256) memory:f7e00000-f7e3ffff memory:f7e40000-f7e5ffff
````

````
$ glxheads :0
Name: :0
  Display:     0x25f3010
  Window:      0x3c00002
  Context:     0x2603e90
  GL_VERSION:  4.5.13453 Compatibility Profile Context 16.40.5
  GL_VENDOR:   ATI Technologies Inc.
  GL_RENDERER: AMD Radeon (TM) RX 470 Graphics
````

````
$ lsmod | grep -E '(kms|drm|amd)'
amdtPwrProf            45056  0
amdkfd                131072  0
amd_iommu_v2           20480  1 amdkfd
amdgpu               1998848  49
i2c_algo_bit           16384  1 amdgpu
ttm                    94208  1 amdgpu
drm_kms_helper        155648  1 amdgpu
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
fb_sys_fops            16384  1 drm_kms_helper
drm                   364544  7 ttm,drm_kms_helper,amdgpu
````

Let me know what else you need and what the issue could be.

**Comment by reanimastudios** [comment]
CodeXL 2.2 crashes if you install the ROCm driver stack. Remove the stack on Debian and CodeXL 2.2 works as expected, albeit with a completely broken OpenCL stack, due to AMD not releasing actual Debian .deb packages thus handcuffing us with mesa-opencl-icd.

**Comment by whitespacer** [comment]
I know that CodeXL loads incorrect libGL, which leads to seg fault. To fix it you can provide path to correct libGL via setting env variable. So I go to CodeXL folder (/opt/CodeXL_2.2-511 in my case) and start CodeXL with command:
`SU_SYSTEM_MODULES_DIRS=/opt/amdgpu-pro/lib/x86_64-linux-gnu ./CodeXL`

**Comment by AmitBM** [comment]
Whitespacer, your observation is correct.
A fix for this issue has already been pushed, and it should be available in the next release (version 2.3).
If you build the product from the source code, you should have it fixed already.

**Comment by jstefanop** [comment]
I am having the same issue, though I am running a compute stack so my GL enviroment is running off intel openGL driver, and only have the compute components for AMDGPU-Pro. Can CodeXL run without the AMDGPU openGL components?

**Comment by AmitBM** [comment]
No, you will not be able to run the GUI application. You may use the command line tools which come with the CodeXL package in the meantime, or build the product from the latest source code.

**Comment by mapaton** [comment]
Thank you whitespacer!!! After trying a couple of clean installs with various updates I had given up but the SU_SYSTEM_MODULES_DIRS= ... did the trick. AMD people you should add this somewhere in the documentation... so much frustration would be saved.

**Comment by tangjie77wd** [comment]
@mapaton @PROteinBY @callan-amd @smheidrich @reanimastudios 
Hello!I create projects with OpenCL on linux . My machine : CentOS 7.3+eclipse + AMD Rx560 + amdgpu-pro-17.30-465504 + CodeXL_Linux_x86_64_2.4.60 .

1.    After I installed all tools above , go into the 'CodeXL_Linux_x86_64_2.4.60' folder and open a terminal ,run the command : ./CodeXL ,then CodeXL gui will appear .
2.    Click the 'Help' menu and then click 'Load the Teapot Sample' .
3.   Click the 'Profile' menu and then clike 'GPU:Performance Counters' .
4.    Press 'F5' on your keyboard and wait for a while.
5.    Close the 'AMD Teapot Example' gui and wait for a while , you will see many performance indicators in the CodeXL gui.
But I have a question these days : the Teapot sample is provided by CodeXL not myself (It exists in CodeXL as a 'CodeXL Teapot.cxl' file ,so we can load it directly in CodeXL. ) , how can i use CodeXL to test the performance of my own OpenCL projects (.cpp file and .cl file) written in the eclipse ( no .cxl file )? Any help will be much appriciate !
