### ISSUE TITLE
format isa output to 80 columns instead of 81

### ISSUE THREAD

**Issue by nerdralph** [GPUOpen-Tools/CodeXL#93]
CodeXL 2.2, isa output is 81 characters.  Here's an example:
`  s_waitcnt     lgkmcnt(0)                              // 000000005108: BF8C007F`
80 characters would avoid line wrap on 80-column terminals.

**Comment by AmitBM** [comment]
Hi nerdalph,

Thanks for the suggestion. Meanwhile, have you tried to increase the number of columns in your terminal?
