### ISSUE TITLE
The driver failed to start profiling.

### ISSUE THREAD

**Issue by tim-lebedkov** [GPUOpen-Tools/CodeXL#96]
The CPU time-based profiling does not work for me:

![image](https://cloud.githubusercontent.com/assets/831371/21311432/784df6ee-c5e7-11e6-8054-ea25c100f6b6.png)

**Comment by swarup-sahoo** [comment]
Looks like CPU Profiler is unable to capture the process, thread details from OS. Not very sure what caused this issue, but you may try following troubleshooting steps which may help us in debugging the issue:

1) Try running CodeXL with admin permission and see if that helps. This is not a solution, just to check if this workaround helps.

2) Reboot your system. Don't launch any other app. Start CodeXL Cpuprofiler and see if profiling works.

3) Uninstall CodeXL completely, and then reinstall CodeXL and see if that helps.

4) Also if you have access to any other system, you may try running CpuProfiler in that machine.

Let us know how the above steps go. Also let us know below information:

- Which OS version you are using?
- Which CodeXL version you are using?

**Comment by tim-lebedkov** [comment]
1. the same error message
2. the same error message
3. the same error message
4. it works on my older laptop

Microsoft Windows [Version 6.1.7601]  (Windows 7)
CodeXL 2.2.733.0

Is there a log for this driver?

**Comment by swarup-sahoo** [comment]
Thanks for your quick reply. Unfortunately that particular component is not sufficiently log enabled, hence the log file would not help.

Can you let us know the following details:
- Is it a Intel (x86? or x64?) or AMD processor (x64) ?
- Is it a 32-bit or 64-bit Win7?
- Do you see any error/warning dialogue during CodeXL installation?
- Is there any possibility of Windows TEMP or TMP folder being relocated to some other path?

**Comment by tim-lebedkov** [comment]
Your question about the %TEMP%/%TMP% variables solved the issue. The system %TEMP% pointed to "C:\Windows\Temp" and my %TEMP% pointed to "C:\Users\...\Local Settings\TEMP". I changed the %TEMP% and %TMP% for my user to point to "C:\Windows\Temp" and now it works!
