### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by petrkalos** [GPUOpen-Tools/CodeXL#98]
I am building CodeXL from sources using VS2015 and I want to create the installer (msi package), can anyone help with that?

**Comment by swarup-sahoo** [comment]
To create the CodeXL installer, you need to install "Advanced Installer" tool. The input file to Advanced Installer can be located at CodeXL/CodeXL/Installer/CodeXL/setup.aip

**Comment by petrkalos** [comment]
That's great, thank you very much!
Maybe an entry about it in the documentation would be nice!
