### ISSUE TITLE
CodeXL 2.2 Windows 7 unsigned driver issue

### ISSUE THREAD

**Issue by OrderNexus** [GPUOpen-Tools/CodeXL#99]
After installing CodeXL 2.2, my machine spits out anywhere from 1 to 3 messages at the end, saying that some combination of the AMDTPwrProf.sys, CpuProf.sys, and pcore.sys driver files aren't signed and thus cannot be installed. This issue is preventing certain features of CodeXL from working.

**Comment by kpenujee** [comment]
Hi,
We saw this issue with Win7 systems that are not licensed. Can you please confirm if the system/OS on which you are installing CodeXL is licensed or not.
Without AMDTPwrProf.sys, CpuProf.sys, and pcore.sys drivers, CPU profiling and Power profiling features will not be available in CodeXL.

Thanks,
Kalyan P

**Comment by OrderNexus** [comment]
Well, it looks like I'm going to have a word about this with someone. In the meantime, is there any way around this?

**Comment by kpontzolkova** [comment]
Hello. I have the same problem and i can confirm that my machine windows is not licensed. What can be done?

**Comment by kpenujee** [comment]
Hi,
this issue is specific to Win7 and occurs if its not licensed.
On Win10, we do not see this issue even on non-licensed systems.

Thanks,
Kalyan P

**Comment by OrderNexus** [comment]
So outside of upgrading to Windows 10, what other options are there to fix this issue? What about temporarily disabling driver signing?

**Comment by kpenujee** [comment]
Hi,
what features of CodeXL are you trying to use. 
If its CPU or Power profiling features that you are trying to use CodeXL for, at this point of time, either we should have licensed Win7 or Win10 OS.

Thanks,
Kalyan P

**Comment by 2FacedLove** [comment]
Ok sorry just wanted to check and make sure that wasent an his PC wasebt
thd
issue
